/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ASIHTTPRequest.h"
#import "DoodleJump-Structs.h"
#import "NSCopying.h"

@class NSMutableArray;

@interface ASIFormDataRequest : ASIHTTPRequest <NSCopying> {
	NSMutableArray* postData;
	NSMutableArray* fileData;
	int postFormat;
	unsigned stringEncoding;
}
@property(retain) NSMutableArray* postData;
@property(retain) NSMutableArray* fileData;
@property(assign) int postFormat;
@property(assign) unsigned stringEncoding;
+(id)requestWithURL:(id)url;
-(id)encodeURL:(id)url;
-(id)initWithURL:(id)url;
-(void)dealloc;
-(void)addPostValue:(id)value forKey:(id)key;
-(void)setPostValue:(id)value forKey:(id)key;
-(void)addFile:(id)file forKey:(id)key;
-(void)addFile:(id)file withFileName:(id)fileName andContentType:(id)type forKey:(id)key;
-(void)setFile:(id)file forKey:(id)key;
-(void)setFile:(id)file withFileName:(id)fileName andContentType:(id)type forKey:(id)key;
-(void)addData:(id)data forKey:(id)key;
-(void)addData:(id)data withFileName:(id)fileName andContentType:(id)type forKey:(id)key;
-(void)setData:(id)data forKey:(id)key;
-(void)setData:(id)data withFileName:(id)fileName andContentType:(id)type forKey:(id)key;
-(void)buildPostBody;
-(void)buildMultipartFormDataPostBody;
-(void)buildURLEncodedPostBody;
-(void)appendPostString:(id)string;
-(id)copyWithZone:(NSZone*)zone;
@end

