/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "ASIProgressDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "ASIHTTPRequestDelegate.h"
#import "DoodleJump-Structs.h"

@class NSDictionary;

@interface ASINetworkQueue : XXUnknownSuperclass <ASIProgressDelegate, ASIHTTPRequestDelegate, NSCopying> {
	id delegate;
	SEL requestDidStartSelector;
	SEL requestDidReceiveResponseHeadersSelector;
	SEL requestDidFinishSelector;
	SEL requestDidFailSelector;
	SEL queueDidFinishSelector;
	id uploadProgressDelegate;
	unsigned long long bytesUploadedSoFar;
	unsigned long long totalBytesToUpload;
	id downloadProgressDelegate;
	unsigned long long bytesDownloadedSoFar;
	unsigned long long totalBytesToDownload;
	BOOL shouldCancelAllRequestsOnFailure;
	int requestsCount;
	BOOL showAccurateProgress;
	NSDictionary* userInfo;
}
@property(assign) int requestsCount;
@property(assign) unsigned long long bytesUploadedSoFar;
@property(assign) unsigned long long totalBytesToUpload;
@property(assign) unsigned long long bytesDownloadedSoFar;
@property(assign) unsigned long long totalBytesToDownload;
@property(assign) BOOL shouldCancelAllRequestsOnFailure;
@property(assign, nonatomic, setter=setUploadProgressDelegate:) id uploadProgressDelegate;
@property(assign, nonatomic, setter=setDownloadProgressDelegate:) id downloadProgressDelegate;
@property(assign) SEL requestDidStartSelector;
@property(assign) SEL requestDidReceiveResponseHeadersSelector;
@property(assign) SEL requestDidFinishSelector;
@property(assign) SEL requestDidFailSelector;
@property(assign) SEL queueDidFinishSelector;
@property(assign) id delegate;
@property(assign) BOOL showAccurateProgress;
@property(retain) NSDictionary* userInfo;
+(id)queue;
-(id)init;
-(void)dealloc;
-(BOOL)isNetworkActive;
-(void)updateNetworkActivityIndicator;
-(void)setSuspended:(BOOL)suspended;
-(void)reset;
-(void)go;
-(void)cancelAllOperations;
-(void)resetProgressDelegate:(id)delegate;
-(void)addHEADOperation:(id)operation;
-(void)addOperation:(id)operation;
-(void)requestStarted:(id)started;
-(void)requestReceivedResponseHeaders:(id)headers;
-(void)requestFinished:(id)finished;
-(void)requestFailed:(id)failed;
-(void)request:(id)request didReceiveBytes:(long long)bytes;
-(void)request:(id)request didSendBytes:(long long)bytes;
-(void)request:(id)request incrementDownloadSizeBy:(long long)by;
-(void)request:(id)request incrementUploadSizeBy:(long long)by;
-(void)authenticationNeededForRequest:(id)request;
-(void)proxyAuthenticationNeededForRequest:(id)request;
-(BOOL)respondsToSelector:(SEL)selector;
-(id)copyWithZone:(NSZone*)zone;
@end

