/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ASIProgressDelegate <NSObject>
@optional
-(void)setProgress:(float)progress;
-(void)request:(id)request didReceiveBytes:(long long)bytes;
-(void)request:(id)request didSendBytes:(long long)bytes;
-(void)request:(id)request incrementDownloadSizeBy:(long long)by;
-(void)request:(id)request incrementUploadSizeBy:(long long)by;
@end

