/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BackgroundObject : XXUnknownSuperclass {
	CGPoint objPosition;
	int objTexture;
	float offsetDivider;
	int halfHeight;
}
@property(assign, nonatomic) CGPoint objPosition;
@property(assign, nonatomic) int objTexture;
-(id)initWithTextureId:(int)textureId position:(CGPoint)position;
-(id)initWithTextureId:(int)textureId position:(CGPoint)position size:(CGSize)size;
-(id)initWithTextureId:(int)textureId position:(CGPoint)position size:(CGSize)size offsetDivider:(float)divider;
-(float)objTopY;
-(void)moveWithOffsetY:(float)offsetY;
-(void)dealloc;
@end

