/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BonusObject : XXUnknownSuperclass {
	CGPoint objPosition;
	CGSize objSize;
	CGRect objFrame;
	float objSpeedH;
	int isMovingH;
	float posOffset;
	int objType;
	int objTexture;
	int objId;
	int isFinalMultiplayerSpring;
}
@property(assign, nonatomic) CGPoint objPosition;
@property(assign, nonatomic) CGSize objSize;
@property(assign, nonatomic) CGRect objFrame;
@property(assign, nonatomic) int isMovingH;
@property(assign, nonatomic) float posOffset;
@property(assign, nonatomic) int objType;
@property(assign, nonatomic) int objTexture;
@property(assign, nonatomic) float objSpeedH;
@property(assign, nonatomic) int objId;
@property(assign, nonatomic) int isFinalMultiplayerSpring;
+(void)setTotalObjectsCreated:(int)created;
+(int)totalObjectsCreated;
+(void)setHorzMoveBoundary:(float)boundary right:(float)right;
-(id)init;
-(void)setType:(int)type;
-(void)tick;
-(void)moveWithOffsetY:(float)offsetY;
-(void)dealloc;
@end

