/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class Texture2D, OALSound;

@interface BubbleParticles : XXUnknownSuperclass {
	Texture2D* particleTexture;
	unsigned pointVerticesBufferId;
	unsigned colorsBufferID;
	BubbleParticle* bubbleParticles;
	PointSprite* pointVertices;
	Color4ub* colors;
	int maxParticles;
	int particleIndex;
	int particleCount;
	int isEmitting;
	int emissionTimer;
	int addedParticles;
	OALSound* bubblesSound[2];
	int soundsOption;
	int sizeRangeStart;
	int sizeRangeEnd;
}
-(id)initWithMaxParticles:(int)maxParticles;
-(void)resetParticles;
-(void)setSoundsOption:(int)option;
-(BOOL)addParticleAtPosX:(float)posX posY:(float)y type:(int)type;
-(void)updateParticlesWithOffset:(float)offset playerPosX:(float)x playerPosY:(float)y;
-(void)dealloc;
@end

