/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class UIButton, NSString, UIImageView, UITextField, UITextView, UIScrollView, UIActivityIndicatorView, UILabel;

@interface CrittercismAddViewController : XXUnknownSuperclass <UIAlertViewDelegate> {
	NSString* feedbackTitle;
	NSString* category;
	UIImageView* backgroundImage;
	UILabel* titleLabel;
	UITextField* titleTextField;
	UILabel* nameLabel;
	UITextField* nameTextField;
	UILabel* descriptionLabel;
	UITextView* descriptionTextView;
	UIButton* ideaToggle;
	UIButton* bugToggle;
	UIButton* loveToggle;
	UIButton* questionToggle;
	UIButton* _categoryButton;
	UIActivityIndicatorView* indicator;
	UIButton* submittingButton;
	UIScrollView* addScrollView;
}
@property(retain, nonatomic) NSString* feedbackTitle;
@property(retain, nonatomic) NSString* category;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UITextField* titleTextField;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UITextField* nameTextField;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain, nonatomic) UITextView* descriptionTextView;
@property(retain, nonatomic) UIButton* ideaToggle;
@property(retain, nonatomic) UIButton* bugToggle;
@property(retain, nonatomic) UIButton* loveToggle;
@property(retain, nonatomic) UIButton* questionToggle;
@property(retain, nonatomic) UIActivityIndicatorView* indicator;
@property(retain, nonatomic) UIButton* submittingButton;
@property(retain, nonatomic) UIImageView* backgroundImage;
@property(retain, nonatomic) UIScrollView* addScrollView;
@property(retain, nonatomic) UIButton* categoryButton;
-(id)initWithTitle:(id)title andCategory:(id)category;
-(void)didRotate:(id)rotate;
-(void)bugHit:(id)hit;
-(void)ideaHit:(id)hit;
-(void)loveHit:(id)hit;
-(void)questionHit:(id)hit;
-(void)viewDidLoad;
-(void)changeToLandscape;
-(void)showWorking;
-(void)saveFeedback;
-(void)showErrorMsg;
-(void)feedbackButtonPressed;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
@end

