/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CrittercismRootViewController;

@interface CrittercismNavigationView : XXUnknownSuperclass {
	CrittercismRootViewController* rootController;
}
-(void)viewDidAppear:(BOOL)view;
-(void)setRoot:(id)root;
-(id)initWithRoot:(id)root;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
@end

