/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "NSMutableCopying.h"
#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSFastEnumeration.h"


@interface CrittercismJKDictionary : XXUnknownSuperclass <NSCopying, NSMutableCopying, NSFastEnumeration> {
	unsigned count;
	unsigned capacity;
	unsigned mutations;
	CrittercismJKHashTableEntry* entry;
}
+(id)allocWithZone:(NSZone*)zone;
-(void)dealloc;
-(unsigned)count;
-(id)objectForKey:(id)key;
-(void)getObjects:(id*)objects andKeys:(id*)keys;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)keyEnumerator;
-(void)setObject:(id)object forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
@end

