/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UITextView, NSString;

@interface CrittercismAddCommentViewController : XXUnknownSuperclass {
	UITextView* commentTextView;
	NSString* feedbackID;
	NSString* parentID;
}
@property(retain, nonatomic) UITextView* commentTextView;
@property(retain, nonatomic) NSString* feedbackID;
@property(retain, nonatomic) NSString* parentID;
-(id)initWithFeedbackID:(id)feedbackID andParentID:(id)anId;
-(void)feedbackButtonPressed;
-(void)saveHit;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
@end

