/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CrittercismNavigationView, CrittercismRootViewController, NSString;

@interface CrittercismViewController : XXUnknownSuperclass {
	NSString* appIDStr;
	NSString* keyStr;
	NSString* secretStr;
	float redTint;
	float greenTint;
	float blueTint;
	CrittercismNavigationView* navController;
	CrittercismRootViewController* crittercismRootViewController;
}
@property(retain, nonatomic) NSString* appIDStr;
@property(retain, nonatomic) NSString* keyStr;
@property(retain, nonatomic) NSString* secretStr;
-(id)initWithAppID:(id)appID andKey:(id)key andSecret:(id)secret;
-(void)setTintRed:(float)red green:(float)green blue:(float)blue;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
@end

