/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIScrollView, UIImageView, NSString, NSDictionary, NSMutableArray, UITextView, UIButton, UILabel;

@interface CrittercismDescriptionViewController : XXUnknownSuperclass {
	NSDictionary* feedbackDict;
	NSString* feedbackID;
	UITextView* commentTextView;
	UILabel* descriptionLabel;
	UILabel* titleLabel;
	UIImageView* categoryImage;
	UIImageView* avatarImage;
	UILabel* avatarLabel;
	UILabel* avatarSubmitLabel;
	UIButton* thumbsUpButton;
	UIButton* thumbsDownButton;
	UILabel* thumbsUpLabel;
	UILabel* thumbsDownLabel;
	UIScrollView* commentsScrollView;
	UIButton* feedbackBubble;
	UIButton* addCommentButton;
	UIButton* showVotesButton;
	NSMutableArray* addedComponents;
}
@property(retain, nonatomic) UITextView* commentTextView;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UIImageView* categoryImage;
@property(retain, nonatomic) UIImageView* avatarImage;
@property(retain, nonatomic) UILabel* avatarLabel;
@property(retain, nonatomic) UILabel* avatarSubmitLabel;
@property(retain, nonatomic) UIButton* thumbsUpButton;
@property(retain, nonatomic) UIButton* thumbsDownButton;
@property(retain, nonatomic) UILabel* thumbsUpLabel;
@property(retain, nonatomic) UILabel* thumbsDownLabel;
@property(retain, nonatomic) UIScrollView* commentsScrollView;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain) NSDictionary* feedbackDict;
@property(retain) NSMutableArray* addedComponents;
@property(retain, nonatomic) UIButton* feedbackBubble;
@property(retain, nonatomic) UIButton* addCommentButton;
@property(retain, nonatomic) NSString* feedbackID;
@property(retain, nonatomic) UIButton* showVotesButton;
-(id)initWithFeedbackID:(id)feedbackID;
-(void)addCommentHit:(id)hit;
-(void)viewDidLoad;
-(void)refreshView;
-(void)thumbsUpHit:(id)hit;
-(void)thumbsDownHit:(id)hit;
-(void)vote:(int)vote;
-(void)showVotesLeft;
-(void)hideVotes;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
@end

