/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CrittercismJKDictionaryEnumerator : XXUnknownSuperclass {
	id collection;
	unsigned nextObject;
}
-(id)initWithJKDictionary:(id)jkdictionary;
-(void)dealloc;
-(id)allObjects;
-(id)nextObject;
@end

