/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UIAlertViewDelegate.h"

@class UIView, UIImageView, UIActivityIndicatorView, UITableView, UIFont, NSMutableArray, UIAlertView;

@interface DocumentSelector : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate> {
	UIAlertView* alertView;
	UIView* tableBckgView;
	UIImageView* tableCoverImageView;
	UITableView* documentsTableView;
	NSMutableArray* deviceNameArray;
	NSMutableArray* modificationDateArray;
	int selectedIndexId;
	UIActivityIndicatorView* activityIndicator;
	UIFont* itemFont1;
	UIFont* itemFont2;
}
@property(retain, nonatomic) NSMutableArray* deviceNameArray;
@property(retain, nonatomic) NSMutableArray* modificationDateArray;
-(id)init;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)hide;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)refresh;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)showActivityIndicator;
-(void)hideActivityIndicator;
-(void)dealloc;
@end

