/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ASIHTTPRequest.h"
#import "ExtendedRequest.h"

@class OFXPRequest;

@interface ExtendedGetRequest : ASIHTTPRequest <ExtendedRequest> {
	OFXPRequest* xpRequest;
}
-(void)setXPRequest:(id)request;
-(void)requestFinished;
@end

