/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FBLoginDialogDelegate.h"

@class FBDialog, NSString, NSArray, FBRequest, NSDate;
@protocol FBSessionDelegate;

@interface Facebook : XXUnknownSuperclass <FBLoginDialogDelegate> {
	NSString* _accessToken;
	NSDate* _expirationDate;
	id<FBSessionDelegate> _sessionDelegate;
	FBRequest* _request;
	FBDialog* _loginDialog;
	FBDialog* _fbDialog;
	NSString* _appId;
	NSString* _localAppId;
	NSArray* _permissions;
}
@property(copy, nonatomic) NSString* accessToken;
@property(copy, nonatomic) NSDate* expirationDate;
@property(assign, nonatomic) id<FBSessionDelegate> sessionDelegate;
@property(retain, nonatomic) NSArray* permissions;
@property(copy, nonatomic) NSString* localAppId;
-(id)initWithAppId:(id)appId;
-(void)dealloc;
-(id)openUrl:(id)url params:(id)params httpMethod:(id)method delegate:(id)delegate;
-(id)getOwnBaseUrl;
-(void)authorizeWithFBAppAuth:(BOOL)fbappAuth safariAuth:(BOOL)auth;
-(id)parseURLParams:(id)params;
-(void)authorize:(id)authorize delegate:(id)delegate;
-(void)authorize:(id)authorize delegate:(id)delegate localAppId:(id)anId;
-(BOOL)handleOpenURL:(id)url;
-(void)logout:(id)logout;
-(id)requestWithParams:(id)params andDelegate:(id)delegate;
-(id)requestWithMethodName:(id)methodName andParams:(id)params andHttpMethod:(id)method andDelegate:(id)delegate;
-(id)requestWithGraphPath:(id)graphPath andDelegate:(id)delegate;
-(id)requestWithGraphPath:(id)graphPath andParams:(id)params andDelegate:(id)delegate;
-(id)requestWithGraphPath:(id)graphPath andParams:(id)params andHttpMethod:(id)method andDelegate:(id)delegate;
-(void)dialog:(id)dialog andDelegate:(id)delegate;
-(void)dialog:(id)dialog andParams:(id)params andDelegate:(id)delegate;
-(BOOL)isSessionValid;
-(void)fbDialogLogin:(id)login expirationDate:(id)date;
-(void)fbDialogNotLogin:(BOOL)login;
-(void)request:(id)request didFailWithError:(id)error;
@end

