/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, NSMutableData, NSURLConnection;
@protocol FBRequestDelegate;

@interface FBRequest : XXUnknownSuperclass {
	id<FBRequestDelegate> _delegate;
	NSString* _url;
	NSString* _httpMethod;
	NSMutableDictionary* _params;
	NSURLConnection* _connection;
	NSMutableData* _responseText;
}
@property(assign, nonatomic) id<FBRequestDelegate> delegate;
@property(copy, nonatomic) NSString* url;
@property(copy, nonatomic) NSString* httpMethod;
@property(retain, nonatomic) NSMutableDictionary* params;
@property(assign, nonatomic) NSURLConnection* connection;
@property(assign, nonatomic) NSMutableData* responseText;
+(id)getRequestWithParams:(id)params httpMethod:(id)method delegate:(id)delegate requestURL:(id)url;
+(id)serializeURL:(id)url params:(id)params;
+(id)serializeURL:(id)url params:(id)params httpMethod:(id)method;
-(void)utfAppendBody:(id)body data:(id)data;
-(id)generatePostBody;
-(id)formError:(int)error userInfo:(id)info;
-(id)parseJsonResponse:(id)response error:(id*)error;
-(void)failWithError:(id)error;
-(void)handleResponseData:(id)data;
-(BOOL)loading;
-(void)connect;
-(void)dealloc;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveData:(id)data;
-(id)connection:(id)connection willCacheResponse:(id)response;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
@end

