/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSMutableArray, FlurryFileCache;

@interface FlurryImageCache : XXUnknownSuperclass {
	FlurryFileCache* _fileCache;
	NSMutableDictionary* _index;
	int _maxImageCached;
	NSMutableArray* _lru;
	long long _cacheUpdateTimestamp;
}
@property(assign, nonatomic) long long cacheUpdateTimestamp;
@property(retain, nonatomic) FlurryFileCache* fileCache;
+(id)instance;
+(id)recreateInstanceWithFileCache:(id)fileCache;
+(id)createInstanceWithFileCache:(id)fileCache;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)imageIdToFileName:(id)fileName;
-(id)storedIds;
-(void)setAsMostRecentlyUsed:(id)used;
-(BOOL)remove:(id)remove;
-(id)get:(id)get;
-(void)save:(id)save imageId:(id)anId;
-(id)initWithFileCache:(id)fileCache;
@end

