/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface FlurryUtil : XXUnknownSuperclass {
}
+(BOOL)addSkipBackupAttributeToItemAtURL:(id)url;
+(int)getSystemVersionAsAnInteger;
+(BOOL)addToSet:(id)set obj:(id)obj;
+(BOOL)isIPad;
+(id)convertStrToNum:(id)num;
+(void)removeViewFromSuperview:(id)superview;
+(BOOL)canvasInPortraitUpsideDown;
+(BOOL)canvasInLandscapeLeft;
+(BOOL)canvasInLandscapeRight;
+(BOOL)canvasInLandscape;
+(id)getCanvasOrientation;
+(BOOL)canvasInPortraitUpsideDown:(id)portraitUpsideDown;
+(BOOL)canvasInLandscapeLeft:(id)landscapeLeft;
+(BOOL)canvasInLandscapeRight:(id)landscapeRight;
+(BOOL)canvasInLandscape:(id)landscape;
+(CGRect)screenBounds;
+(CGRect)screenBounds:(id)bounds;
+(void)handleException:(id)exception;
+(void)setShowErrorInLogEnabled:(BOOL)logEnabled;
+(BOOL)isDebugLogEnabled;
+(void)setDebugLogEnabled:(BOOL)enabled;
@end

