/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableData, NSDictionary, NSError;

@interface FlurryHTTPResponse : XXUnknownSuperclass {
	NSMutableData* _body;
	int _statusCode;
	NSError* _error;
	NSDictionary* _headers;
}
@property(readonly, assign, nonatomic) NSDictionary* headers;
@property(readonly, assign, nonatomic) NSError* error;
@property(readonly, assign, nonatomic) int statusCode;
@property(readonly, assign, nonatomic) NSMutableData* body;
+(id)filePath:(int)path;
+(id)readFromURL:(id)url;
-(void)saveToDisk;
-(id)description;
-(BOOL)isError;
-(BOOL)isSuccess;
-(void)dealloc;
-(id)initWithBody:(id)body statusCode:(int)code headers:(id)headers error:(id)error;
-(id)initWithResponse:(id)response body:(id)body error:(id)error;
@end

