/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSMutableDictionary, NSString, NSMutableArray, NSDate;

@interface FlurrySession : XXUnknownSuperclass <NSCoding> {
	int _serializationVersion;
	NSDate* _startTime;
	NSDate* _endTime;
	NSDate* _pauseTime;
	long long _totalPauseIntervalMillis;
	double _latitude;
	double _longitude;
	float _accuracy;
	BOOL _crashed;
	NSString* _apiKey;
	NSString* _appVersion;
	NSString* _userID;
	NSMutableDictionary* _eventCounts;
	NSMutableArray* _eventLog;
	BOOL _eventLogComplete;
	NSMutableArray* _errors;
	int _totalErrorCount;
	NSMutableArray* _adLog;
	NSMutableArray* _appSpotAdLog;
	BOOL _eventLoggingEnabled;
	BOOL _sessionReportsOnCloseEnabled;
	BOOL _sessionReportsOnPauseEnabled;
	int _pageViewCount;
	NSString* _locale;
	NSString* _timeZone;
	BOOL _internetAvailable;
	int _gender;
	NSDate* _age;
}
@property(retain, nonatomic) NSDate* endTime;
@property(assign, nonatomic) BOOL internetAvailable;
@property(assign, nonatomic) int pageViewCount;
@property(copy, nonatomic) NSString* appVersion;
@property(readonly, assign, nonatomic) NSString* apiKey;
@property(readonly, assign, nonatomic) NSDate* startTime;
@property(assign) BOOL crashed;
+(id)getCFUUIDBasedUIDWithChecksum:(id)checksum;
+(id)generateCFUUIDBasedUID;
+(id)getCFUUIDBasedUIDAndStatus:(int*)status;
+(id)generateCFUUID;
+(unsigned)generateCFUUIDBasedUIDChecksum:(id)checksum;
+(id)getMACUID;
+(id)getMACBasedUID;
+(id)hashDataToHexString:(char*)hexString length:(int)length;
+(id)hashData:(id)data;
+(id)flurryID;
+(id)phoneID;
+(double)reduceLocationPrecision:(double)precision;
+(void)sendAdStateCompleted:(id)completed saveData:(BOOL)data;
+(void)sendAdStateCompleted:(id)completed;
+(void)asyncNotifyAdStateCompleted:(id)completed;
+(id)initialTimestamp;
+(int)appendSessionsDataChecksum:(id)checksum;
+(void)generateChecksumTable;
+(id)dataForSessions:(id)sessions requestAppCircleAds:(BOOL)ads requestVideoAds:(BOOL)ads3 requestAppSpotAds:(BOOL)ads4 requestReengageAds:(BOOL)ads5;
+(id)dataForSessions:(id)sessions;
+(void)sendSessionsToServerWithTimeout:(BOOL)timeout useWebView:(BOOL)view requestAppCircleAds:(BOOL)ads requestVideoAds:(BOOL)ads4 requestAppSpotAds:(BOOL)ads5 requestReengageAds:(BOOL)ads6 sendCurrentSession:(BOOL)session;
+(void)sendSessionsToServerForAppCircle;
+(void)sendSessionsToServerForEndOfSession;
+(void)sendSessionsToServerForSessionPause;
+(void)sendSessionsToServerForAdditionalInfo;
+(id)getNetworkLock;
+(id)oldAdStateCallbacksFilePath;
+(id)adStateCallbacksFilePath;
+(id)oldInitialTimestampFilePath;
+(id)initialTimestampFilePath;
+(id)oldSessionSentFilePath;
+(id)sessionSentFilePath;
+(id)oldCurrentSessionFilePath;
+(id)currentSessionFilePath;
+(id)oldSessionsFilePath;
+(id)sessionsFilePath;
+(id)filePathDirectory;
+(void)removeAdStateCallbackIfExists:(id)exists;
+(id)removeOldAdStateCallbacksIfNecessary:(id)necessary;
+(void)addToSavedAdStateCallbacks:(id)savedAdStateCallbacks;
+(void)setSavedAdStateCallbacks:(id)callbacks;
+(id)savedAdStateCallbacks;
+(void)sendSavedAdStateCallbacks;
+(void)setMaxSessions:(int)sessions;
+(id)removeOldSessionsIfNecessary:(id)necessary;
+(void)addToSavedSessions:(id)savedSessions;
+(void)setSavedSessions:(id)sessions;
+(void)setSentSession;
+(BOOL)sentSession;
+(id)savedSessions;
+(id)iTunesMetadataPlist;
+(BOOL)appIsCracked;
+(BOOL)deviceIsJailbroken;
+(int)deviceCPUFrequency;
+(int)deviceMemory;
+(id)devicePlatform;
+(void)setCurrentSession:(id)session;
+(id)currentSession;
+(id)createActiveFlurrySession:(id)session;
+(void)setReEngageAdParser:(id)parser;
+(void)setAppSpotAdParser:(id)parser;
+(void)setVideoAdParser:(id)parser;
+(void)setAppCircleAdParser:(id)parser;
+(id)getAgentVersion;
-(void)dealloc;
-(long long)sessionLength;
-(long long)timeIntervalSinceSessionStart:(id)start;
-(id)data;
-(void)saveToDisk;
-(void)recordAppSpotAdImpression:(id)impression;
-(void)recordAdImpression:(id)impression;
-(void)recordError:(id)error message:(id)message exceptionString:(id)string;
-(void)recordError:(id)error message:(id)message error:(id)error3;
-(void)recordError:(id)error message:(id)message exception:(id)exception;
-(void)endTimedEvents;
-(void)endTimedEvent:(id)event withParameters:(id)parameters;
-(void)recordEvent:(id)event withParameters:(id)parameters timed:(BOOL)timed;
-(void)recordEvent:(id)event withParameters:(id)parameters;
-(void)setEventLoggingEnabled:(BOOL)enabled;
-(void)setAge:(int)age;
-(void)setGender:(id)gender;
-(void)setUserID:(id)anId;
-(id)userID;
-(void)setLatitude:(double)latitude longitude:(double)longitude horizontalAccuracy:(float)accuracy verticalAccuracy:(float)accuracy4;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)maybeIncrementPageView;
-(void)endSessionAndSend:(BOOL)send removeCurrentSession:(BOOL)session;
-(void)endSession;
-(void)saveSession;
-(void)resumeSession;
-(void)pauseSession;
-(id)initWithAPIKey:(id)apikey appVersion:(id)version;
-(BOOL)sessionReportsOnPauseEnabled;
-(void)setSessionReportsOnPauseEnabled:(BOOL)enabled;
-(BOOL)sessionReportsOnCloseEnabled;
-(void)setSessionReportsOnCloseEnabled:(BOOL)enabled;
@end

