/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FlurryHTTPEater : XXUnknownSuperclass {
}
+(id)urlWithProtocol:(id)protocol host:(id)host port:(int)port path:(id)path query:(id)query;
+(id)queryDictionaryToString:(id)string;
+(id)sendMethod:(id)method to:(id)to body:(id)body headerFields:(id)fields timeoutInterval:(int)interval useWebView:(BOOL)view;
+(id)post:(id)post body:(id)body headerFields:(id)fields;
+(id)post:(id)post body:(id)body;
+(id)get:(id)get headerFields:(id)fields;
+(id)get:(id)get;
@end

