/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITabBarControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UINavigationControllerDelegate.h"

@class FlurrySession;

@interface FlurryPageViewDelegate : XXUnknownSuperclass <UINavigationControllerDelegate, UITabBarControllerDelegate, UITableViewDelegate> {
	id<NSObject> _delegate;
	FlurrySession* _session;
}
@property(retain, nonatomic) FlurrySession* session;
@property(retain, nonatomic) id<NSObject> delegate;
+(id)createDelegateOnTarget:(id)target;
+(id)createInvocationOnSelector:(SEL)selector target:(id)target;
-(void)tabBarController:(id)controller didEndCustomizingViewControllers:(id)controllers changed:(BOOL)changed;
-(void)tabBarController:(id)controller willEndCustomizingViewControllers:(id)controllers changed:(BOOL)changed;
-(void)tabBarController:(id)controller willBeginCustomizingViewControllers:(id)controllers;
-(void)tabBarController:(id)controller didSelectViewController:(id)controller2;
-(BOOL)tabBarController:(id)controller shouldSelectViewController:(id)controller2;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)navigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithSession:(id)session delegate:(id)delegate;
@end

