/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"


@interface GameConfiguration : XXUnknownSuperclass {
	CGBoundary_tag worldBoundary_;
	CGBoundary_tag viewBoundary_;
	CGRect viewport_;
	float spawnBoundary_;
}
@property(assign, nonatomic) CGBoundary_tag worldBoundary;
@property(assign, nonatomic) CGBoundary_tag viewBoundary;
@property(assign, nonatomic) float spawnBoundary;
@property(assign, nonatomic) CGRect viewport;
+(id)currentConfiguration;
+(void)makeCurrentConfiguration:(id)configuration;
+(id)createDoodleJumpClassicConfiguration;
+(id)createDoodleJumpIPadConfiguration;
-(id)init;
-(void)dealloc;
-(CGRect)viewportRectToViewRect:(CGRect)viewRect;
-(CGSize)viewportSizeToViewSize:(CGSize)viewSize;
-(CGPoint)viewportPointToViewPoint:(CGPoint)viewPoint;
-(CGPoint)viewPointToViewportPoint:(CGPoint)viewportPoint;
@end

