/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class GKScore, GKAchievement;

@interface GCDeferredSubmission : XXUnknownSuperclass {
	GKAchievement* achievement;
	GKScore* score;
	id handler;
}
@property(retain, nonatomic) GKAchievement* achievement;
@property(retain, nonatomic) GKScore* score;
+(void)submitAchievement:(id)achievement andErrorHandler:(id)handler;
+(void)submitScore:(id)score andErrorHandler:(id)handler;
-(id)initWithAchievement:(id)achievement andErrorHandler:(id)handler;
-(id)initWithScore:(id)score andErrorHandler:(id)handler;
-(void)submit;
-(void)submitBackground;
-(void)callHandler:(id)handler;
@end

