/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

@interface HelperViewController : XXUnknownSuperclass {
	int contentViewDidAppear;
	SEL onContentAppearSelector;
	SEL onContentDisappearSelector;
	UIColor* backgroundColor;
	int useModal;
}
@property(assign, nonatomic) SEL onContentAppearSelector;
@property(assign, nonatomic) SEL onContentDisappearSelector;
@property(assign, nonatomic) int contentViewDidAppear;
@property(retain, nonatomic) UIColor* backgroundColor;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(void)loadView;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)presentModalViewController:(id)controller animated:(BOOL)animated;
-(void)dismissModalViewControllerAnimated:(BOOL)animated;
-(void)reset;
-(void)dealloc;
@end

