/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIButton;

@interface ImagePopUpView : XXUnknownSuperclass {
	UIButton* viewButton;
	SEL onAppearSelector;
	SEL onDisappearSelector;
	SEL onTouchSelector;
}
@property(assign, nonatomic) SEL onAppearSelector;
@property(assign, nonatomic) SEL onDisappearSelector;
@property(assign, nonatomic) SEL onTouchSelector;
-(id)initWithFrame:(CGRect)frame;
-(void)setImage:(id)image;
-(void)startAnimating;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)viewButtonTouched;
-(void)dealloc;
@end

