/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface KeychainWrapper : XXUnknownSuperclass {
}
+(id)sharedWrapper;
-(BOOL)saveGenericPassword:(id)password forAccount:(id)account service:(id)service accessGroup:(id)group;
-(id)getGenericPasswordForAccount:(id)account service:(id)service accessGroup:(id)group;
@end

