/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CFNetwork/_kCFHTTPAuthenticationPassword.h>


@interface LSTWTweetComposeViewController : _kCFHTTPAuthenticationPassword {
}
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
@end

