/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface MeteorObject : XXUnknownSuperclass {
	CGPoint objPosition;
	int objTexture;
	int objRotation;
	int objIsActive;
	float objScale;
	float vectorX;
	float vectorY;
	float animationCounter;
	int activationCounter;
	int movingDirection;
}
@property(assign, nonatomic) CGPoint objPosition;
@property(assign, nonatomic) int objTexture;
@property(assign, nonatomic) int objRotation;
@property(assign, nonatomic) float objScale;
@property(assign, nonatomic) int objIsActive;
-(id)init;
-(void)restartFallingObject;
-(void)tick;
-(void)moveWithOffsetY:(float)offsetY;
-(void)dealloc;
@end

