/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableData, NSURL, NSString;

@interface MGTwitterHTTPURLConnection : XXUnknownSuperclass {
	NSMutableData* _data;
	int _requestType;
	int _responseType;
	NSString* _identifier;
	NSURL* _URL;
}
-(id)initWithRequest:(id)request delegate:(id)delegate requestType:(int)type responseType:(int)type4;
-(void)dealloc;
-(void)resetDataLength;
-(void)appendData:(id)data;
-(id)identifier;
-(id)data;
-(id)URL;
-(int)requestType;
-(int)responseType;
-(id)description;
@end

