/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */
// Unknown library


@interface MonsterObject : NSObject {
	CGPoint objPosition;
	CGRect objFrame;
	int objTexture;
	int objType;
	int objEnergy;
	float objShouldFall;
	int objIsHit;
	float rangeX;
	float rangeY;
	float offsetX;
	float offsetY;
	float objSpeed;
	int textureStep;
	int textureChangeDelay;
	int movingType;
	int objId;
}
@property(assign, nonatomic) CGPoint objPosition;
@property(assign, nonatomic) CGRect objFrame;
@property(assign, nonatomic) int objTexture;
@property(assign, nonatomic) int objType;
@property(assign, nonatomic) int objEnergy;
@property(assign, nonatomic) float objShouldFall;
@property(assign, nonatomic) int objIsHit;
@property(assign, nonatomic) int objId;
@property(assign, nonatomic) float rangeY;
@property(assign, nonatomic) float offsetY;
@property(assign, nonatomic) float objSpeed;
+(void)setTotalObjectsCreated:(int)created;
+(int)totalObjectsCreated;
-(id)initWithObjType:(int)objType movingType:(int)type objPosition:(CGPoint)position;
-(void)tick;
-(void)hit;
-(void)moveWithOffsetY:(float)offsetY;
-(void)dealloc;
@end

