/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSURLResponse;

@interface MPOAuthURLResponse : XXUnknownSuperclass {
	NSURLResponse* _urlResponse;
	NSDictionary* _oauthParameters;
}
@property(retain, nonatomic) NSURLResponse* urlResponse;
@property(retain, nonatomic) NSDictionary* oauthParameters;
-(id)init;
-(oneway void)dealloc;
@end

