/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MPURLRequestParameter.h"


@interface MPOAuthSignatureParameter : MPURLRequestParameter {
}
+(id)signatureBaseStringUsingParameterString:(id)string forRequest:(id)request;
+(id)HMAC_SHA1SignatureForText:(id)text usingSecret:(id)secret;
-(id)initWithText:(id)text andSecret:(id)secret forRequest:(id)request usingMethod:(id)method;
-(id)initUsingHMAC_SHA1WithText:(id)text andSecret:(id)secret forRequest:(id)request;
-(oneway void)dealloc;
@end

