/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSError, MPOAuthConnection, MPOAuthCredentialConcreteStore, MPOAuthURLRequest, MPOAuthURLResponse, NSData, NSMutableData;
@protocol MPOAuthParameterFactory, MPOAuthCredentialStore;

@interface MPOAuthAPIRequestLoader : XXUnknownSuperclass {
	MPOAuthCredentialConcreteStore* _credentials;
	MPOAuthURLRequest* _oauthRequest;
	MPOAuthURLResponse* _oauthResponse;
	MPOAuthConnection* _activeConnection;
	NSMutableData* _dataBuffer;
	NSString* _dataAsString;
	NSError* _error;
	OFDelegate _onSuccess;
	OFDelegate _onFailure;
}
@property(retain, nonatomic) NSError* error;
@property(retain, nonatomic) id<MPOAuthParameterFactory, MPOAuthCredentialStore> credentials;
@property(retain, nonatomic) MPOAuthURLRequest* oauthRequest;
@property(retain, nonatomic) MPOAuthURLResponse* oauthResponse;
@property(retain, nonatomic) NSData* data;
@property(retain, nonatomic) NSString* responseString;
-(id)initWithURL:(id)url;
-(id)initWithRequest:(id)request;
-(oneway void)dealloc;
-(void)setOnSuccess:(const OFDelegate*)success;
-(void)setOnFailure:(const OFDelegate*)failure;
-(const OFDelegate*)getOnSuccess;
-(const OFDelegate*)getOnFailure;
-(id)getConfiguredRequest;
-(void)loadAsynch;
-(void)loadSynchronously:(BOOL)synchronously;
-(void)cancel;
-(void)forceSetData:(id)data;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connectionDidFinishLoading:(id)connection;
-(id)connection:(id)connection willCacheResponse:(id)response;
-(void)_interrogateResponseForOAuthData;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

