/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;

@protocol MPOAuthCredentialStore <NSObject>
@property(readonly, assign, nonatomic) NSString* consumerKey;
@property(readonly, assign, nonatomic) NSString* consumerSecret;
@property(readonly, retain, nonatomic) NSString* requestToken;
@property(readonly, retain, nonatomic) NSString* requestTokenSecret;
@property(readonly, retain, nonatomic) NSString* accessToken;
@property(readonly, retain, nonatomic) NSString* accessTokenSecret;
@end

