/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString;

@interface MPURLRequestParameter : XXUnknownSuperclass {
	NSString* _name;
	NSString* _value;
	NSData* _blob;
	NSString* _blobDataType;
}
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSString* value;
@property(copy, nonatomic) NSData* blob;
@property(copy, nonatomic) NSString* blobDataType;
+(id)parametersFromString:(id)string;
+(id)parametersFromDictionary:(id)dictionary;
+(id)parameterDictionaryFromString:(id)string;
+(id)parameterStringForParameters:(id)parameters;
+(id)parameterStringForDictionary:(id)dictionary;
-(id)init;
-(id)initWithName:(id)name andValue:(id)value;
-(id)initWithName:(id)name andBlob:(id)blob andDataType:(id)type;
-(oneway void)dealloc;
-(id)URLEncodedParameterString;
-(int)compare:(id)compare;
-(id)description;
@end

