/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface OAConsumer : XXUnknownSuperclass {
	NSString* key;
	NSString* secret;
}
@property(retain) NSString* key;
@property(retain) NSString* secret;
-(id)initWithKey:(id)key secret:(id)secret;
-(void)dealloc;
@end

