/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface OALSound : XXUnknownSuperclass {
	unsigned source;
	unsigned buffer;
	int error;
	double duration;
	unsigned char isLoopingSound;
	int soundType;
	int shouldResume;
	NSString* soundFileName;
	int pausedByteOffset;
}
@property(assign, nonatomic) int soundType;
@property(assign, nonatomic) unsigned source;
+(void)initSoundEngineWithAdditionalNumberOfSoundSources:(int)soundSources;
+(void)destroyAllSourcesAndBuffers;
+(void)recreateAllSourcesAndBuffers;
+(void)pauseAllSounds;
+(void)resumeAllSounds;
+(void)stopAllSounds;
-(id)initWithSoundFileName:(id)soundFileName shouldLoop:(BOOL)loop soundType:(int)type;
-(BOOL)initSound;
-(void)removeSound;
-(void)destroySourceAndBuffer;
-(void)dealloc;
-(BOOL)playWithVolume:(float)volume;
-(BOOL)stopSound;
-(BOOL)pauseSound;
-(BOOL)resumeSound;
-(BOOL)rewind;
-(BOOL)isPlaying;
-(BOOL)isPaused;
-(BOOL)setVolume:(float)volume;
@end

