/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLResponse, OAMutableURLRequest;

@interface OAServiceTicket : XXUnknownSuperclass {
	OAMutableURLRequest* request;
	NSURLResponse* response;
	BOOL didSucceed;
}
@property(retain) OAMutableURLRequest* request;
@property(retain) NSURLResponse* response;
@property(assign) BOOL didSucceed;
-(id)initWithRequest:(id)request response:(id)response didSucceed:(BOOL)succeed;
-(void)dealloc;
@end

