/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class NSString;

@interface OFAbridgedHighScore : OFResource <OFCallbackable> {
	long long score;
	NSString* leaderboardId;
	NSString* displayText;
	NSString* userId;
	NSString* userName;
	NSString* userProfilePictureUrl;
	unsigned userGamerScore;
	OFPointer<OFHttpService> mHttpService;
	OFPointer<OFImageViewHttpServiceObserver> mHttpServiceObserver;
}
@property(readonly, assign, nonatomic) long long score;
@property(readonly, assign, nonatomic) NSString* displayText;
@property(readonly, assign, nonatomic) NSString* userId;
@property(readonly, assign, nonatomic) NSString* userName;
@property(readonly, assign, nonatomic) NSString* userProfilePictureUrl;
@property(readonly, assign, nonatomic) unsigned userGamerScore;
+(void)setDelegate:(id)delegate;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(id)getProfilePicture;
-(void)_getProfilePictureSuccess:(id)success;
-(void)_getProfilePictureFailure;
-(void)setScore:(id)score;
-(void)setUserGamerScore:(id)score;
-(void)setLeaderboardId:(id)anId;
-(void)setDisplayText:(id)text;
-(void)setUserName:(id)name;
-(void)setUserId:(id)anId;
-(void)setUserProfilePictureUrl:(id)url;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

