/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFNotificationView.h"

@class UILabel, OFAchievement;

@interface OFAchievementNotificationView : OFNotificationView {
	OFAchievement* achievement;
	UILabel* achievementValueText;
}
@property(retain, nonatomic) UILabel* achievementValueText;
+(id)notificationViewName;
+(void)showAchievementNotice:(id)notice inView:(id)view;
-(void)_iconFinishedDownloading;
-(void)configureWithNotificationData:(id)notificationData inView:(id)view;
-(void)dealloc;
@end

