/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class NSString, NSDate;

@interface OFAchievement : OFResource <OFCallbackable> {
	NSString* title;
	NSString* description;
	unsigned gamerscore;
	NSString* iconUrl;
	BOOL isSecret;
	double percentComplete;
	NSDate* unlockDate;
	BOOL isUnlockedByComparedToUser;
	NSString* comparedToUserId;
	NSString* endVersion;
	NSString* startVersion;
	unsigned position;
	OFPointer<OFHttpService> mHttpService;
	OFPointer<OFImageViewHttpServiceObserver> mHttpServiceObserver;
}
@property(readonly, assign, nonatomic) NSString* title;
@property(readonly, assign, nonatomic) NSString* description;
@property(readonly, assign, nonatomic) unsigned gamerscore;
@property(readonly, assign, nonatomic) NSString* iconUrl;
@property(readonly, assign, nonatomic) BOOL isSecret;
@property(readonly, assign, nonatomic) NSDate* unlockDate;
@property(readonly, assign, nonatomic) BOOL isUnlockedByComparedToUser;
@property(readonly, assign, nonatomic) NSString* comparedToUserId;
@property(readonly, assign, nonatomic) NSString* endVersion;
@property(readonly, assign, nonatomic) NSString* startVersion;
@property(readonly, assign, nonatomic) unsigned position;
@property(readonly, assign, nonatomic) double percentComplete;
@property(readonly, assign, nonatomic) BOOL isUnlocked;
+(void)setDelegate:(id)delegate;
+(id)achievements;
+(id)achievement:(id)achievement;
+(id)submitDeferredAchievements;
+(void)setCustomUrlForSocialNotificaion:(id)socialNotificaion;
+(void)_submitDeferredSuccess;
+(void)_submitDeferredFailure;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
+(bool)canReceiveCallbacksNow;
+(void)_forceSyncGameCenterSuccess;
+(void)_forceSyncGameCenterFailure;
+(void)forceSyncGameCenterAchievements;
-(id)updateProgressionComplete:(double)complete andShowNotification:(BOOL)notification;
-(id)getIcon;
-(void)deferUpdateProgressionComplete:(double)complete andShowNotification:(BOOL)notification;
-(void)_getIconSuccess:(id)success;
-(void)_getIconFailure;
-(void)_updateProgressionSuccess;
-(void)_updateProgressionFailure;
-(id)initWithLocalSQL:(OFSqlQuery*)localSQL;
-(void)setTitle:(id)title;
-(void)setDescription:(id)description;
-(void)setGamerscoreFromString:(id)string;
-(void)setIconUrl:(id)url;
-(void)setIsSecretFromString:(id)string;
-(void)setPercentComplete:(id)complete;
-(void)setIsUnlockedByComparedToUserFromString:(id)string;
-(void)setComparedToUserId:(id)userId;
-(void)setUnlockDateFromString:(id)string;
-(void)setPositionFromString:(id)string;
-(void)setEndVersion:(id)version;
-(void)setStartVersion:(id)version;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(id)unlock;
-(void)unlockAndDefer;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

