/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFProfileFrame.h"
#import "OFTableSequenceControllerHelper.h"

@class NSString, OFTableCellHelper;

@interface OFAchievementListController : OFTableSequenceControllerHelper <OFProfileFrame> {
	NSString* applicationName;
	NSString* applicationId;
	NSString* applicationIconUrl;
	BOOL doesUserHaveApplication;
	OFTableCellHelper* achievementProgressionListLeading;
}
@property(retain, nonatomic) NSString* applicationName;
@property(retain, nonatomic) NSString* applicationId;
@property(retain, nonatomic) NSString* applicationIconUrl;
@property(assign, nonatomic) BOOL doesUserHaveApplication;
@property(retain, nonatomic) OFTableCellHelper* achievementProgressionListLeading;
-(BOOL)isComparingToOtherUser;
-(void)dealloc;
-(void)viewDidLoad;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getNoDataFoundMessage;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)_onDataLoaded:(id)loaded isIncremental:(BOOL)incremental;
-(bool)usePlainTableSectionHeaders;
-(void)populateContextualDataFromPlayedGame:(id)playedGame;
-(void)postPushAchievementListController;
-(BOOL)supportsComparison;
-(void)profileUsersChanged:(id)changed comparedToUser:(id)user;
-(void)onLeadingCellWasLoaded:(id)loaded forSection:(id)section;
-(id)getLeadingCellControllerNameForSection:(id)section;
-(id)getTableHeaderControllerName;
@end

