/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"


@interface OFAnnouncementBrowserController : OFTableSequenceControllerHelper {
}
+(id)announcementBrowser;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(bool)shouldAlwaysRefreshWhenShown;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)onResourcesDownloaded:(id)downloaded;
-(id)getNoDataFoundMessage;
-(id)getTableHeaderViewName;
-(void)onTableHeaderCreated:(id)created;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
@end

