/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFAnnouncementService.h"
#import "OFService.h"
#import "DoodleJump-Structs.h"

@class OFPaginatedSeries;

@interface OFAnnouncementService : OFService {
	OFPaginatedSeries* announcements;
	unsigned unseenAnnouncementCount;
}
@property(readonly, assign, nonatomic) OFPaginatedSeries* announcements;
@property(assign, nonatomic) unsigned unseenAnnouncementCount;
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(id)downloadAnnouncements;
+(id)downloadAnnouncementsOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getIndexOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)recentAnnouncementsForApplication:(id)application onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)markAllAnnouncementsAsRead;
+(void)clearLocalAnnouncements;
-(void)dealloc;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
-(id)_combineSections:(id)sections;
-(void)_combineSectionsAndSortStickyFirst:(id)first nextCall:(id)call;
-(void)_combineSectionsAndSort:(id)sort nextCall:(id)call;
-(void)_onAnnouncementsDownloaded:(id)downloaded;
@end

@interface OFAnnouncementService (Public)
+(void)getPostsForAnnouncement:(id)announcement page:(int)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(unsigned)unreadAnnouncements;
@end

