/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFApplicationDescription : OFResource {
	NSString* name;
	NSString* iconUrl;
	NSString* itunesId;
	NSString* price;
	NSString* currentVersion;
	NSString* briefDescription;
	NSString* extendedDescription;
	NSString* applicationId;
}
@property(readonly, retain, nonatomic) NSString* name;
@property(readonly, retain, nonatomic) NSString* iconUrl;
@property(readonly, retain, nonatomic) NSString* itunesId;
@property(readonly, retain, nonatomic) NSString* price;
@property(readonly, retain, nonatomic) NSString* currentVersion;
@property(readonly, retain, nonatomic) NSString* briefDescription;
@property(readonly, retain, nonatomic) NSString* extendedDescription;
@property(readonly, retain, nonatomic) NSString* applicationId;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setName:(id)name;
-(void)setIconUrl:(id)url;
-(void)setItunesId:(id)anId;
-(void)setPrice:(id)price;
-(void)setCurrentVersion:(id)version;
-(void)setBriefDescription:(id)description;
-(void)setExtendedDescription:(id)description;
-(void)setApplicationId:(id)anId;
-(void)dealloc;
@end

