/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableData, NSData;

@interface OFAsyncReadPacket : XXUnknownSuperclass {
	NSMutableData* buffer;
	int bytesDone;
	double timeout;
	int maxLength;
	long tag;
	NSData* term;
	BOOL readAllAvailableData;
}
-(id)initWithData:(id)data timeout:(double)timeout tag:(long)tag readAllAvailable:(BOOL)available terminator:(id)terminator maxLength:(long)length;
-(unsigned)readLengthForTerm;
-(unsigned)prebufferReadLengthForTerm;
-(long)searchForTermAfterPreBuffering:(long)termAfterPreBuffering;
-(void)dealloc;
@end

