/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSTimer, OFAsyncWritePacket, NSMutableArray, NSMutableData, OFAsyncReadPacket;

@interface OFAsyncSocket : XXUnknownSuperclass {
	CFSocketRef theSocket4;
	CFSocketRef theSocket6;
	CFReadStreamRef theReadStream;
	CFWriteStreamRef theWriteStream;
	CFRunLoopSourceRef theSource4;
	CFRunLoopSourceRef theSource6;
	CFRunLoopRef theRunLoop;
	struct {
		int version;
		void* info;
		/*function-pointer*/ void* retain;
		/*function-pointer*/ void* release;
		/*function-pointer*/ void* copyDescription;
	} theContext;
	NSArray* theRunLoopModes;
	NSTimer* theConnectTimer;
	NSMutableArray* theReadQueue;
	OFAsyncReadPacket* theCurrentRead;
	NSTimer* theReadTimer;
	NSMutableData* partialReadBuffer;
	NSMutableArray* theWriteQueue;
	OFAsyncWritePacket* theCurrentWrite;
	NSTimer* theWriteTimer;
	id theDelegate;
	unsigned short theFlags;
	long theUserData;
}
+(id)CRLFData;
+(id)CRData;
+(id)LFData;
+(id)ZeroData;
-(id)init;
-(id)initWithDelegate:(id)delegate;
-(id)initWithDelegate:(id)delegate userData:(long)data;
-(void)dealloc;
-(long)userData;
-(void)setUserData:(long)data;
-(id)delegate;
-(void)setDelegate:(id)delegate;
-(BOOL)canSafelySetDelegate;
-(CFSocketRef)getCFSocket;
-(CFReadStreamRef)getCFReadStream;
-(CFWriteStreamRef)getCFWriteStream;
-(float)progressOfReadReturningTag:(long*)readReturningTag bytesDone:(int*)done total:(int*)total;
-(float)progressOfWriteReturningTag:(long*)writeReturningTag bytesDone:(int*)done total:(int*)total;
-(void)runLoopAddSource:(CFRunLoopSourceRef)source;
-(void)runLoopRemoveSource:(CFRunLoopSourceRef)source;
-(void)runLoopAddTimer:(id)timer;
-(void)runLoopRemoveTimer:(id)timer;
-(void)runLoopUnscheduleReadStream;
-(void)runLoopUnscheduleWriteStream;
-(void)enablePreBuffering;
-(BOOL)moveToRunLoop:(id)runLoop;
-(BOOL)setRunLoopModes:(id)modes;
-(id)runLoopModes;
-(BOOL)acceptOnPort:(unsigned short)port error:(id*)error;
-(BOOL)acceptOnAddress:(id)address port:(unsigned short)port error:(id*)error;
-(BOOL)connectToHost:(id)host onPort:(unsigned short)port error:(id*)error;
-(BOOL)connectToHost:(id)host onPort:(unsigned short)port withTimeout:(double)timeout error:(id*)error;
-(BOOL)connectToAddress:(id)address error:(id*)error;
-(BOOL)connectToAddress:(id)address withTimeout:(double)timeout error:(id*)error;
-(void)startConnectTimeout:(double)timeout;
-(void)endConnectTimeout;
-(void)doConnectTimeout:(id)timeout;
-(CFSocketRef)newAcceptSocketForAddress:(id)address error:(id*)error;
-(BOOL)createSocketForAddress:(id)address error:(id*)error;
-(BOOL)attachSocketsToRunLoop:(id)runLoop error:(id*)error;
-(BOOL)configureSocketAndReturnError:(id*)error;
-(BOOL)connectSocketToAddress:(id)address error:(id*)error;
-(void)doAcceptWithSocket:(int)socket;
-(void)doSocketOpen:(CFSocketRef)open withCFSocketError:(long)cfsocketError;
-(BOOL)createStreamsFromNative:(int)native error:(id*)error;
-(BOOL)createStreamsToHost:(id)host onPort:(unsigned short)port error:(id*)error;
-(BOOL)attachStreamsToRunLoop:(id)runLoop error:(id*)error;
-(BOOL)configureStreamsAndReturnError:(id*)error;
-(BOOL)openStreamsAndReturnError:(id*)error;
-(void)doStreamOpen;
-(BOOL)setSocketFromStreamsAndReturnError:(id*)streamsAndReturnError;
-(void)closeWithError:(id)error;
-(void)recoverUnreadData;
-(void)emptyQueues;
-(void)close;
-(void)disconnect;
-(void)disconnectAfterReading;
-(void)disconnectAfterWriting;
-(void)disconnectAfterReadingAndWriting;
-(void)maybeScheduleDisconnect;
-(id)unreadData;
-(id)getErrnoError;
-(id)getSocketError;
-(id)getStreamError;
-(id)getAbortError;
-(id)getConnectTimeoutError;
-(id)getReadMaxedOutError;
-(id)getReadTimeoutError;
-(id)getWriteTimeoutError;
-(id)errorFromCFStreamError:(FrameData)cfstreamError;
-(BOOL)isConnected;
-(id)connectedHost;
-(unsigned short)connectedPort;
-(id)localHost;
-(unsigned short)localPort;
-(id)connectedHost:(CFSocketRef)host;
-(unsigned short)connectedPort:(CFSocketRef)port;
-(id)localHost:(CFSocketRef)host;
-(unsigned short)localPort:(CFSocketRef)port;
-(BOOL)isSocketConnected;
-(BOOL)areStreamsConnected;
-(id)addressHost:(CFDataRef)host;
-(unsigned short)addressPort:(CFDataRef)port;
-(BOOL)isIPv4;
-(BOOL)isIPv6;
-(id)description;
-(void)readDataToLength:(long)length withTimeout:(double)timeout tag:(long)tag;
-(void)readDataToData:(id)data withTimeout:(double)timeout tag:(long)tag;
-(void)readDataToData:(id)data withTimeout:(double)timeout maxLength:(long)length tag:(long)tag;
-(void)readDataWithTimeout:(double)timeout tag:(long)tag;
-(void)scheduleDequeueRead;
-(void)maybeDequeueRead;
-(BOOL)hasBytesAvailable;
-(long)readIntoBuffer:(char*)buffer maxLength:(long)length;
-(void)doBytesAvailable;
-(void)completeCurrentRead;
-(void)endCurrentRead;
-(void)doReadTimeout:(id)timeout;
-(void)writeData:(id)data withTimeout:(double)timeout tag:(long)tag;
-(void)scheduleDequeueWrite;
-(void)maybeDequeueWrite;
-(void)doSendBytes;
-(void)completeCurrentWrite;
-(void)endCurrentWrite;
-(void)doWriteTimeout:(id)timeout;
-(void)startTLS:(id)tls;
-(void)maybeStartTLS;
-(void)onTLSStarted:(BOOL)started;
-(void)doCFSocketCallback:(unsigned long)callback forSocket:(CFSocketRef)socket withAddress:(id)address withData:(const void*)data;
-(void)doCFReadStreamCallback:(unsigned long)callback forStream:(CFReadStreamRef)stream;
-(void)doCFWriteStreamCallback:(unsigned long)callback forStream:(CFWriteStreamRef)stream;
-(BOOL)enableKeepAlive;
@end

