/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface OFAsyncWritePacket : XXUnknownSuperclass {
	NSData* buffer;
	int bytesDone;
	long tag;
	double timeout;
}
-(id)initWithData:(id)data timeout:(double)timeout tag:(long)tag;
-(void)dealloc;
@end

