/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class OFBannerCell, OFFramedContentWrapperView;

@interface OFBannerFrame : XXUnknownSuperclass {
	OFFramedContentWrapperView* wrapperView;
	OFBannerCell* bannerSubview;
}
@property(retain, nonatomic) OFBannerCell* bannerSubview;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
@end

