/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class OFUser, OFGameProfilePageInfo, NSString;

@interface OFBootstrap : OFResource {
	unsigned minimumOpenFeintVersionSupported;
	unsigned pollingFrequencyInChat;
	unsigned pollingFrequencyDefault;
	BOOL loggedInUserHasSetName;
	BOOL loggedInUserHasNonDeviceCredential;
	BOOL loggedInUserHasHttpBasicCredential;
	BOOL loggedInUserHasFbconnectCredential;
	BOOL loggedInUserHasTwitterCredential;
	BOOL loggedInUserIsNewUser;
	BOOL loggedInUserHadFriendsOnBootup;
	OFGameProfilePageInfo* gameProfilePageInfo;
	OFUser* user;
	NSString* accessToken;
	NSString* accessTokenSecret;
	NSString* clientApplicationId;
	NSString* clientApplicationIconUrl;
	unsigned unviewedChallengesCount;
	unsigned pendingFriendsCount;
	unsigned imsUnreadCount;
	unsigned subscribedThreadsUnreadCount;
	unsigned invitesUnreadCount;
	unsigned unfulfilledInvitesCount;
	NSString* suggestionsForumId;
	NSString* initialDashboardScreen;
	NSString* initialDashboardModalContentURL;
	BOOL initializePresenceService;
	BOOL pipeHttpOverPresenceService;
	NSString* presenceQueue;
	BOOL loggedInUserHasShareLocationEnabled;
}
@property(readonly, assign, nonatomic) unsigned minimumOpenFeintVersionSupported;
@property(readonly, assign, nonatomic) unsigned pollingFrequencyInChat;
@property(readonly, assign, nonatomic) unsigned pollingFrequencyDefault;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasSetName;
@property(readonly, assign, nonatomic) BOOL loggedInUserIsNewUser;
@property(readonly, retain, nonatomic) OFGameProfilePageInfo* gameProfilePageInfo;
@property(readonly, retain, nonatomic) OFUser* user;
@property(readonly, retain, nonatomic) NSString* accessToken;
@property(readonly, retain, nonatomic) NSString* accessTokenSecret;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasNonDeviceCredential;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasHttpBasicCredential;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasFbconnectCredential;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasTwitterCredential;
@property(readonly, retain, nonatomic) NSString* clientApplicationId;
@property(readonly, retain, nonatomic) NSString* clientApplicationIconUrl;
@property(readonly, assign, nonatomic) BOOL loggedInUserHadFriendsOnBootup;
@property(readonly, assign, nonatomic) unsigned unviewedChallengesCount;
@property(readonly, assign, nonatomic) unsigned pendingFriendsCount;
@property(readonly, assign, nonatomic) unsigned imsUnreadCount;
@property(readonly, assign, nonatomic) unsigned subscribedThreadsUnreadCount;
@property(readonly, assign, nonatomic) unsigned invitesUnreadCount;
@property(readonly, assign, nonatomic) unsigned unfulfilledInvitesCount;
@property(readonly, assign, nonatomic) NSString* suggestionsForumId;
@property(readonly, assign, nonatomic) NSString* initialDashboardScreen;
@property(readonly, assign, nonatomic) NSString* initialDashboardModalContentURL;
@property(readonly, assign, nonatomic) BOOL initializePresenceService;
@property(readonly, assign, nonatomic) BOOL pipeHttpOverPresenceService;
@property(readonly, retain, nonatomic) NSString* presenceQueue;
@property(readonly, assign, nonatomic) BOOL loggedInUserHasShareLocationEnabled;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
-(id)init;
-(void)setMinimumOpenFeintVersionSupported:(id)supported;
-(void)setPollingFrequencyInChat:(id)chat;
-(void)setPollingFrequencyDefault:(id)aDefault;
-(void)setGameProfilePageInfo:(id)info;
-(void)setUser:(id)user;
-(void)setLoggedInUserHadFriendsOnBootup:(id)userHadFriendsOnBootup;
-(void)setLoggedInUserHasSetName:(id)userHasSetName;
-(void)setLoggedInUserHasNonDeviceCredential:(id)userHasNonDeviceCredential;
-(void)setLoggedInUserHasHttpBasicCredential:(id)userHasHttpBasicCredential;
-(void)setLoggedInUserHasFbconnectCredential:(id)userHasFbconnectCredential;
-(void)setLoggedInUserHasTwitterCredential:(id)userHasTwitterCredential;
-(void)setLoggedInUserIsNewUser:(id)userIsNewUser;
-(void)setAccessTokenSecret:(id)secret;
-(void)setAccessToken:(id)token;
-(void)setPresenceQueue:(id)queue;
-(void)setInitializePresenceService:(id)service;
-(void)setPipeHttpOverPresenceService:(id)service;
-(void)setClientApplicationId:(id)anId;
-(void)setClientApplicationIconUrl:(id)url;
-(void)setInitialDashboardScreen:(id)screen;
-(void)setInitialDashboardModalContentURL:(id)url;
-(void)setUnviewedChallengesCount:(id)count;
-(void)setPendingFriendsCount:(id)count;
-(void)setImsUnreadCount:(id)count;
-(void)setSubscribedThreadsUnreadCount:(id)count;
-(void)setInvitesUnreadCount:(id)count;
-(void)setUnfulfilledInvitesCount:(id)count;
-(void)setSuggestionsForumId:(id)anId;
-(void)setLoggedInUserHasShareLocationEnabled:(id)userHasShareLocationEnabled;
-(void)dealloc;
@end

