/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFBootstrapService : OFService {
	BOOL bootstrapInProgress;
	OFDelegate success;
	OFDelegate failure;
}
@property(assign, nonatomic) BOOL bootstrapInProgress;
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(BOOL)bootstrapInProgress;
+(void)doBootstrapWithNewAccount:(BOOL)newAccount userId:(id)anId onSucceededLoggingIn:(const OFDelegate*)anIn onFailedLoggingIn:(const OFDelegate*)anIn4;
-(id)init;
-(void)dealloc;
-(void)registerPolledResources:(id)resources;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
-(void)bootstrapSucceededOnBootstrapThread:(id)thread;
-(void)bootstrapSucceeded:(id)succeeded;
-(void)bootstrapFailed:(id)failed;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

