/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

@interface OFButtonPanelEntry : XXUnknownSuperclass {
	UIView* button;
	UIView* decoration;
}
@property(readonly, assign, nonatomic) UIView* button;
@property(readonly, assign, nonatomic) UIView* decoration;
+(id)entryWithButton:(id)button;
-(void)dealloc;
-(void)replaceDecoration:(id)decoration;
@end

