/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFProfileFrame.h"
#import "OFTableSequenceControllerHelper.h"

@class NSString, OFChallengeDefinitionStats;

@interface OFChallengeListController : OFTableSequenceControllerHelper <OFProfileFrame> {
	int selectedSegment;
	int listType;
	NSString* clientApplicationId;
	OFChallengeDefinitionStats* challengeDefinitionStats;
}
@property(retain, nonatomic) NSString* clientApplicationId;
@property(assign, nonatomic) int listType;
@property(retain, nonatomic) OFChallengeDefinitionStats* challengeDefinitionStats;
-(void)dealloc;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(id)getComparisonUser;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getTableHeaderControllerName;
-(void)onPendingSelected;
-(void)onHistorySelected;
-(void)onTableHeaderCreated:(id)created;
-(id)getNoDataFoundMessage;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(bool)usePlainTableSectionHeaders;
-(id)createPlainTableSectionHeader:(unsigned)header;
-(void)onSectionsCreated:(id)created;
-(BOOL)supportsComparison;
-(void)profileUsersChanged:(id)changed comparedToUser:(id)user;
@end

