/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class OFChallengeDefinition;

@interface OFChallengeDefinitionStats : OFResource {
	OFChallengeDefinition* challengeDefinition;
	int localUsersWins;
	int localUsersLosses;
	int localUsersTies;
	int comparedUsersWins;
	int comparedUsersLosses;
	BOOL comparison;
}
@property(readonly, retain, nonatomic) OFChallengeDefinition* challengeDefinition;
@property(readonly, assign, nonatomic) int localUsersWins;
@property(readonly, assign, nonatomic) int localUsersLosses;
@property(readonly, assign, nonatomic) int localUsersTies;
@property(readonly, assign, nonatomic) int comparedUsersWins;
@property(readonly, assign, nonatomic) int comparedUsersLosses;
@property(readonly, assign, nonatomic) BOOL comparison;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setChallengeDefinition:(id)definition;
-(void)setLocalUsersWins:(id)wins;
-(void)setLocalUsersLosses:(id)losses;
-(void)setLocalUsersTies:(id)ties;
-(void)setComparedUsersWins:(id)wins;
-(void)setComparedUsersLosses:(id)losses;
-(void)dealloc;
@end

