/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFChallengeService.h"
#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFChallengeService : OFService {
	OFPointer<OFHttpService> mHttpService;
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)displaySendChallengeModal:(id)modal challengeText:(id)text challengeData:(id)data;
+(void)displayChallengeCompletedModal:(id)modal resultData:(id)data resultDescription:(id)description reChallengeDescription:(id)description4;
+(id)sendChallenge:(id)challenge challengeText:(id)text challengeData:(id)data userMessage:(id)message hiddenText:(id)text5 toUsers:(id)users inResponseToChallenge:(id)challenge7 onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(id)submitChallengeResult:(id)result result:(int)result2 resultDescription:(id)description onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getChallengeToUserWithId:(id)anId onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(id)rejectChallenge:(id)challenge onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(id)downloadChallengeData:(id)data onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)writeChallengeToUserToFile:(id)file challengeToUser:(id)user;
+(id)readChallengeToUserFromFile:(id)file;
+(void)getChallengeHistoryAcrossAllTypes:(unsigned)types onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getChallengeHistoryForType:(id)type clientApplicationId:(id)anId pageIndex:(int)index onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getChallengeHistoryForType:(id)type clientApplicationId:(id)anId pageIndex:(int)index comparedToUserId:(id)userId onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
-(OFHttpService*)createHttpService;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

@interface OFChallengeService (Private)
+(void)getChallengeToUserAndShowNotification:(id)userAndShowNotification;
+(void)getChallengeToUserAndShowDetailView:(id)userAndShowDetailView;
+(void)getSentChallengesForLocalUserAndLocalApplication:(unsigned)localUserAndLocalApplication onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getCompletedChallengesForLocalUserAndLocalApplication:(unsigned)localUserAndLocalApplication onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPendingChallengesForLocalUserAndApplication:(id)localUserAndApplication pageIndex:(unsigned)index onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPendingChallengesForLocalUserAndLocalApplication:(unsigned)localUserAndLocalApplication onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPendingChallengesForLocalUserAndApplication:(id)localUserAndApplication pageIndex:(unsigned)index comparedToUserId:(id)userId onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getUsersWhoReceivedChallengeWithId:(id)anId clientApplicationId:(id)anId2 pageIndex:(unsigned)index onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getUsersToChallenge:(id)challenge pageIndex:(unsigned)index onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)_getChallengeToUserAndShowDetailView:(id)userAndShowDetailView;
-(void)_chainedGetChallengeToUserAndShowDetailView:(id)userAndShowDetailView challengeId:(id)anId;
-(void)_onChallengeReceivedNotification:(id)notification;
-(void)_onChallengeReceivedDetailView:(id)view;
-(void)_onChallengeReceivedFailed;
@end

