/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class NSString;

@interface OFChallengeDefinition : OFResource <OFCallbackable> {
	NSString* title;
	NSString* clientApplicationId;
	NSString* iconUrl;
	BOOL multiAttempt;
	OFPointer<OFHttpService> mHttpService;
	OFPointer<OFImageViewHttpServiceObserver> mHttpServiceObserver;
}
@property(readonly, assign, nonatomic) NSString* title;
@property(readonly, assign, nonatomic) NSString* iconUrl;
@property(readonly, assign, nonatomic) BOOL multiAttempt;
@property(readonly, assign, nonatomic) NSString* clientApplicationId;
+(void)setDelegate:(id)delegate;
+(id)downloadAllChallengeDefinitions;
+(id)downloadChallengeDefinitionWithId:(id)anId;
+(void)_downloadAllChallengeDefinitionsSuccess:(id)success;
+(void)_downloadAllChallengeDefinitionsFail;
+(void)_downloadChallengeDefinitionWithIdSuccess:(id)idSuccess;
+(void)_downloadChallengeDefinitionWithIdFail;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
+(bool)canReceiveCallbacksNow;
-(id)getIcon;
-(void)_getIconSuccess:(id)success;
-(void)_getIconFailure;
-(void)setTitle:(id)title;
-(void)setClientApplicationId:(id)anId;
-(void)setIconUrl:(id)url;
-(void)setMultiAttempt:(id)attempt;
-(id)getMultiAttemptAsString;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

