/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFChatRoomInstance : OFResource {
	NSString* roomName;
	NSString* roomType;
	int numUsersInRoom;
	int maxNumUsersInRoom;
}
@property(readonly, assign, nonatomic) NSString* roomName;
@property(readonly, assign, nonatomic) NSString* roomType;
@property(readonly, assign, nonatomic) int numUsersInRoom;
@property(readonly, assign, nonatomic) int maxNumUsersInRoom;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setRoomName:(id)name;
-(void)setRoomType:(id)type;
-(void)setNumUsersInRoom:(id)room;
-(void)setMaxNumUsersInRoom:(id)room;
-(BOOL)isDeveloperRoom;
-(BOOL)isGlobalRoom;
-(BOOL)isApplicationRoom;
-(void)dealloc;
@end

