/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class NSObject, NSArray;
@protocol OFChoiceListDelegate;

@interface OFChoiceListController : XXUnknownSuperclass {
	NSObject<OFChoiceListDelegate>* delegate;
	NSArray* choices;
	CGPoint location;
}
@property(retain, nonatomic) NSObject<OFChoiceListDelegate>* delegate;
@property(retain, nonatomic) NSArray* choices;
@property(assign, nonatomic) CGPoint location;
-(void)dismissWithAnswer:(int)answer;
-(void)dismissSelf;
-(void)loadView;
-(id)initWithDelegate:(id)delegate location:(CGPoint)location choices:(id)choices;
-(void)dealloc;
@end

