/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFTableSequenceControllerHelper.h"
#import "UIAlertViewDelegate.h"

@class NSString, NSData, UIAlertView, OFChallengeToUser;

@interface OFChallengeDetailController : OFTableSequenceControllerHelper <OFCallbackable, UIAlertViewDelegate> {
	OFChallengeToUser* userChallenge;
	NSString* challengeId;
	NSString* clientApplicationId;
	int list;
	UIAlertView* oneShotAlertView;
	BOOL challengeCompleted;
	NSData* challengeData;
}
@property(retain, nonatomic) OFChallengeToUser* userChallenge;
@property(retain, nonatomic) NSString* challengeId;
@property(assign, nonatomic) int list;
@property(assign, nonatomic) BOOL challengeCompleted;
@property(retain, nonatomic) NSString* clientApplicationId;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getTableHeaderControllerName;
-(bool)usePlainTableSectionHeaders;
-(void)onSectionsCreated:(id)created;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundMessage;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getService;
-(void)startChallenge;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
-(void)acceptChallenge:(id)challenge;
-(void)_challengeDataDownloaded:(id)downloaded;
-(void)_challengeDataDownloadFailed;
-(void)onResourcesDownloaded:(id)downloaded;
-(bool)canReceiveCallbacksNow;
@end

