/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, OFChatRoomController, UILabel;

@interface OFChatRoomChatMessageCell : OFTableCellHelper {
	OFChatRoomController* owner;
	OFImageView* profilePictureView;
	OFImageView* gamePictureView;
	UILabel* playerNameLabel;
	UILabel* gameNameLabel;
	UILabel* chatMessageLabel;
}
@property(assign, nonatomic) OFChatRoomController* owner;
@property(retain, nonatomic) OFImageView* profilePictureView;
@property(retain, nonatomic) OFImageView* gamePictureView;
@property(retain, nonatomic) UILabel* playerNameLabel;
@property(retain, nonatomic) UILabel* gameNameLabel;
@property(retain, nonatomic) UILabel* chatMessageLabel;
-(bool)shouldGameNameLink:(id)link;
-(void)onClickedFeintName;
-(void)onClickedGameName;
-(void)layoutSubviews;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

