/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <AddressBook/_kABPersonPhoneProperty.h>


@interface OFChoiceList : _kABPersonPhoneProperty {
}
+(void)showChoiceListWithDelegate:(id)delegate location:(CGPoint)location choices:(id)choices;
@end

