/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFService.h"


@interface OFChatRoomDefinitionService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)getIndexOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPage:(int)page includeGlobalRooms:(bool)rooms includeDeveloperRooms:(bool)rooms3 includeApplicationRooms:(bool)rooms4 includeLastVisitedRoom:(bool)room onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

