/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFProfileFrame.h"
#import "DoodleJump-Structs.h"
#import "OFFormControllerHelper.h"

@class UITextField, NSString;

@interface OFChangePasswordController : OFFormControllerHelper <OFProfileFrame> {
	UITextField* oldPasswordField;
	UITextField* passwordField;
	UITextField* passwordConfirmationField;
	NSString* oldPassword;
	NSString* password;
	NSString* passwordConfirmation;
}
@property(retain, nonatomic) UITextField* oldPasswordField;
@property(retain, nonatomic) UITextField* passwordField;
@property(retain, nonatomic) UITextField* passwordConfirmationField;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(void)viewWillAppear:(BOOL)view;
-(void)onBeforeFormSubmitted;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(void)registerActionsNow;
-(void)onFormSubmitted:(id)submitted;
-(id)singularResourceName;
-(id)getFormSubmissionUrl;
-(id)getHTTPMethod;
-(void)dealloc;
@end

