/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class OFUser, NSString;

@interface OFChatMessage : OFResource {
	NSString* message;
	NSString* date;
	NSString* playerCurrentGameIconUrl;
	BOOL doesLocalPlayerOwnGame;
	OFUser* user;
}
@property(readonly, assign, nonatomic) NSString* message;
@property(readonly, assign, nonatomic) NSString* date;
@property(readonly, assign, nonatomic) NSString* playerCurrentGameIconUrl;
@property(readonly, assign, nonatomic) BOOL doesLocalPlayerOwnGame;
@property(readonly, assign, nonatomic) OFUser* user;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setMessage:(id)message;
-(void)setDate:(id)date;
-(void)setPlayerCurrentGameIconUrl:(id)url;
-(void)setDoesLocalPlayerOwnGame:(id)game;
-(void)setUser:(id)user;
-(void)dealloc;
@end

