/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFClientApplicationService.h"
#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFClientApplicationService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)getPlayedGamesForUser:(id)user favoriteGamesOnly:(bool)only withPage:(int)page andCountPerPage:(int)page4 onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPlayedGamesForUser:(id)user withPage:(int)page andCountPerPage:(int)page3 onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getFavoriteGamesForUser:(id)user withPage:(int)page andCountPerPage:(int)page3 onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPlayedGamesInScope:(id)scope page:(int)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPlayedGamesForLocalUsersFriends:(int)localUsersFriends onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getGameProfilePageInfo:(id)info onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getGameProfilePageComparisonInfo:(id)info comparedToUserId:(id)userId onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getPlayerReviewForGame:(id)game byUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

@interface OFClientApplicationService (Private)
+(id)setGameIsFavorite:(id)favorite favorite:(bool)favorite2 review:(id)review onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(id)makeGameFavorite:(id)favorite reviewText:(id)text onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)unfavoriteGame:(id)game onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)viewedFanClub:(id)club;
+(void)removeGameFromLocalUsersList:(id)localUsersList onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
@end

