/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFCloudStorageBlob : OFResource {
	NSString* userId;
	NSString* keyStr;
}
@property(readonly, retain, nonatomic) NSString* userId;
@property(readonly, retain, nonatomic) NSString* keyStr;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setUserId:(id)anId;
-(void)setKeyStr:(id)str;
-(void)dealloc;
@end

