/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFCloudStorage : XXUnknownSuperclass <OFCallbackable> {
}
+(void)setDelegate:(id)delegate;
+(id)upload:(id)upload withKey:(id)key;
+(id)downloadKeysForCurrentUser;
+(id)downloadDataWithKey:(id)key;
+(void)_uploadSuccess;
+(void)_uploadFail:(id)fail;
+(void)_downloadSuccess:(id)success;
+(void)_downloadFail:(id)fail;
+(void)_downloadKeysForCurrentUserSuccess:(id)currentUserSuccess;
+(void)_downloadKeysForCurrentUserFail;
+(bool)canReceiveCallbacksNow;
-(bool)canReceiveCallbacksNow;
@end

