/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFUser, OFImageView, UIImageView, UILabel;

@interface OFConversationCell : OFTableCellHelper {
	OFImageView* authorPictureView;
	UILabel* authorLabel;
	UILabel* bodyLabel;
	UILabel* dateLabel;
	UIImageView* greenBubbleView;
	UIImageView* greyBubbleView;
	UIImageView* bubbleView;
	UIImageView* arrowView;
	OFUser* author;
}
-(void)dealloc;
-(void)awakeFromNib;
-(void)onResourceChanged:(id)changed;
-(void)clickedAuthorProfileView;
@end

