/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"


@interface OFContentFrameView : XXUnknownSuperclass {
	BOOL roundedCorners;
}
@property(assign, nonatomic) BOOL roundedCorners;
+(UIEdgeInsets)getContentInsets;
-(void)_commonInit;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)setFrameImage:(id)image;
-(void)dealloc;
@end

