/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCustomBottomView.h"
#import "OFTableSequenceControllerHelper.h"
#import "OFKeyboardAdjustment.h"
#import "OFExpandableSinglelineTextFieldDelegate.h"

@class NSString, OFPoller, OFUser, OFConversationMessageBoxController;

@interface OFConversationController : OFTableSequenceControllerHelper <OFCustomBottomView, OFExpandableSinglelineTextFieldDelegate, OFKeyboardAdjustment> {
	NSString* conversationId;
	OFUser* conversationUser;
	OFConversationMessageBoxController* messageBox;
	BOOL isKeyboardShown;
	OFPoller* poller;
	BOOL hasCompletedInitialIndex;
	float mViewOriginYWithoutKeyboardiPad;
}
@property(retain, nonatomic) NSString* conversationId;
@property(retain, nonatomic) OFUser* conversationUser;
+(id)conversationWithId:(id)anId withUser:(id)user;
+(id)conversationWithId:(id)anId withUser:(id)user initialText:(id)text;
-(id)initWithConversationId:(id)conversationId withConversationUser:(id)conversationUser initialText:(id)text;
-(void)dealloc;
-(void)_initialIndexComplete:(id)complete nextCall:(id)call;
-(void)_adjustTableOffsetY:(float)y animated:(BOOL)animated;
-(void)_startedConversation:(id)conversation;
-(void)_errorStartingConversation;
-(void)_pollingFailed:(id)failed;
-(void)loadView;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(bool)shouldAlwaysRefreshWhenShown;
-(bool)isNewContentShownAtBottom;
-(bool)allowPagination;
-(bool)shouldRefreshAfterNotification;
-(id)getNotificationToRefreshAfter;
-(bool)isNotificationResourceValid:(id)valid;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getNoDataFoundMessage;
-(id)getTableHeaderViewName;
-(void)onTableHeaderCreated:(id)created;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)configureCell:(id)cell asLeading:(BOOL)leading asTrailing:(BOOL)trailing asOdd:(BOOL)odd;
-(id)getBottomView;
-(void)multilineTextFieldDidResize:(id)multilineTextField;
-(float)_keyboardAdjustment;
-(void)_keyboardWillShow:(id)_keyboard;
-(void)_keyboardWillHide:(id)_keyboard;
-(void)_userDidChangePresence:(id)_user;
-(void)_updateOnlineStatusWithUser:(id)user isOnline:(BOOL)online;
@end

