/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIImageView, UILabel;

@interface OFContactCell : OFTableCellHelper {
	OFImageView* profilePictureView;
	UILabel* nameLabel;
	UILabel* numberOrEmail;
	UIImageView* phoneOrEmailIcon;
}
@property(retain, nonatomic) OFImageView* profilePictureView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UILabel* numberOrEmail;
@property(retain, nonatomic) UIImageView* phoneOrEmailIcon;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

