/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface OFCompressableData : XXUnknownSuperclass {
	unsigned uncompressedSize;
	NSData* data;
}
@property(assign, nonatomic) unsigned uncompressedSize;
@property(retain, nonatomic) NSData* data;
+(void)setDisableCompression:(BOOL)compression;
+(void)setVerbose:(BOOL)verbose;
+(id)dataWithBytes:(const void*)bytes length:(unsigned long)length compress:(BOOL)compress;
+(id)dataWithNSData:(id)nsdata compress:(BOOL)compress;
+(id)dataWithSerializedData:(id)serializedData;
+(id)uncompressedDataFromSerializedData:(id)serializedData;
+(id)serializedDataFromData:(id)data;
+(void)runTests;
-(void)compress;
-(id)internalUncompressedData;
-(void)uncompress;
-(id)uncompressedData;
-(id)serializedData;
-(unsigned long)length;
@end

