/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFCurrentUser : XXUnknownSuperclass <OFCallbackable> {
}
+(void)setDelegate:(id)delegate;
+(id)currentUser;
+(id)favoriteCurrentGame:(id)game;
+(id)sendFriendRequest:(id)request;
+(id)unfriend:(id)unfriend;
+(id)checkConnectedToSocialNetwork;
+(BOOL)hasFriends;
+(int)unviewedChallengesCount;
+(BOOL)allowsAutoSocialNotifications;
+(int)OpenFeintBadgeCount;
+(void)_favoriteCurrentGameSuccess;
+(void)_favoriteCurrentGameFailure;
+(void)_checkConnectedToSocialNetworkSuccess:(id)socialNetworkSuccess;
+(void)_checkConnectedToSocialNetworkFailure;
+(void)_currentUserSendFriendRequestSuccess;
+(void)_currentUserSendFriendRequestFailure;
+(void)_currentUserUnfriendSuccess;
+(void)_currentUserUnfriendFailure;
+(bool)canReceiveCallbacksNow;
-(bool)canReceiveCallbacksNow;
@end

