/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, UIWindow;

@interface OFCustomImagePickerController : XXUnknownSuperclass {
	UIWindow* windowFor2x;
	UIViewController* controllerFor2x;
	BOOL statusBarWasHiddenFor2x;
	int statusBarOrientationFor2x;
	int statusBarStyleFor2x;
}
-(void)show;
-(void)hide;
@end

