/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFDashboardNotificationView : XXUnknownSuperclass {
}
+(id)notificationWithText:(id)text;
-(id)initWithText:(id)text;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)dealloc;
@end

