/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"

@class OFDefaultTextField;

@interface OFDefaultTextFieldDelegate : XXUnknownSuperclass <UITextFieldDelegate> {
	BOOL closeKeyboardOnReturn;
	BOOL manageScrollViewOnFocus;
	OFDefaultTextField* owner;
	float mViewHeightWithoutKeyboard;
	BOOL mIsKeyboardShown;
}
@property(assign, nonatomic) BOOL closeKeyboardOnReturn;
@property(assign, nonatomic) BOOL manageScrollViewOnFocus;
@property(assign, nonatomic) OFDefaultTextField* owner;
-(id)init;
-(void)dealloc;
-(id)getScrollView;
-(void)_KeyboardDidShow:(id)_Keyboard;
-(void)_KeyboardDidHide:(id)_Keyboard;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

