/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"

@class NSString, OFDefaultButton, UILabel;

@interface OFDeadEndErrorController : OFViewController {
	NSString* mMessage;
	UILabel* mMessageView;
	OFDefaultButton* mOfflineButton;
}
@property(retain, nonatomic) NSString* message;
@property(retain, nonatomic) UILabel* messageView;
@property(retain, nonatomic) OFDefaultButton* offlineButton;
+(id)mustBeOnlineErrorWithMessage:(id)message;
+(id)deadEndErrorWithMessage:(id)message;
+(id)deadEndErrorWithMessageAndOfflineButton:(id)messageAndOfflineButton;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)dismiss;
-(void)awakeFromNib;
-(void)offlinePressed;
-(void)dealloc;
-(void)registerActionsNow;
@end

