/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSData, NSString;

@interface OFDeviceContact : OFResource {
	int recordId;
	NSString* name;
	NSString* number;
	NSString* email;
	NSData* imageData;
}
@property(assign, nonatomic) int recordId;
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* number;
@property(retain, nonatomic) NSString* email;
@property(retain, nonatomic) NSData* imageData;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
-(void)dealloc;
@end

