/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIView, UILabel;

@interface OFDefaultLeadingCell : OFTableCellHelper {
	UILabel* headerLabel;
	UIView* headerContainerView;
	OFImageView* leftIconView;
	OFImageView* rightIconView;
	OFImageView* secondFromRightIconView;
	id mCallbackTarget;
	SEL mLeftIconSelector;
}
@property(retain, nonatomic) UILabel* headerLabel;
@property(retain, nonatomic) UIView* headerContainerView;
@property(retain, nonatomic) OFImageView* leftIconView;
@property(retain, nonatomic) OFImageView* rightIconView;
@property(retain, nonatomic) OFImageView* secondFromRightIconView;
-(void)dealloc;
-(void)onClickedLeftIcon;
-(void)onClickedRightIcon;
-(void)onClickedSecondFromRightIcon;
-(void)setCallbackTarget:(id)target;
-(void)setLeftIconSelector:(SEL)selector;
-(void)_setImageViewImage:(id)image imageUrl:(id)url defaultImageName:(id)name;
-(void)enableLeftIconView;
-(void)enableLeftIconViewWithImageUrl:(id)imageUrl andDefaultImage:(id)image;
-(void)_disableRightAlignedView:(id)view;
-(void)_enableRightAlignedView:(id)view;
-(void)enableRightIconView;
-(void)enableSecondFromRightIconView;
-(void)disableRightIconView;
-(void)disableSecondFromRightIconView;
-(void)disableBothRightIconViews;
-(void)enableBothRightIconViews;
-(void)populateRightIconsAsComparison:(id)comparison;
@end

