/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIImageView;

@interface OFDefaultTextView : XXUnknownSuperclass {
	UIImageView* bgView;
}
-(void)didMoveToSuperview;
-(void)removeFromSuperview;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
@end

