/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"

@class UIActivityIndicatorView, UILabel;

@interface OFDoBootstrapController : OFViewController <OFCallbackable> {
	UILabel* titleLabel;
	UILabel* messageLabel;
	UIActivityIndicatorView* activityIndicator;
	OFDelegate mCompleteDelegate;
}
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UILabel* messageLabel;
@property(retain, nonatomic) UIActivityIndicatorView* activityIndicator;
-(void)_showMessageAndHideLoading:(id)loading;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(void)dismiss;
-(void)_findUsersSucceeded:(id)succeeded;
-(void)_findUsersFailed;
-(void)_bootstrapSucceded;
-(void)_bootstrapFailed;
-(void)_skip;
-(void)setCompleteDelegate:(OFDelegate*)delegate;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

