/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFFormControllerHelper.h"

@class UITextField;

@interface OFEnableParentalControlsController : OFFormControllerHelper {
	UITextField* password;
	UITextField* passwordConfirmation;
}
@property(retain, nonatomic) UITextField* password;
@property(retain, nonatomic) UITextField* passwordConfirmation;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)usesXP;
-(id)getResourceRequest;
-(void)onBeforeFormSubmitted;
-(void)onAfterFormSubmitted;
-(void)onFormSubmitted:(id)submitted;
-(void)dealloc;
@end

