/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "OFCallbackable.h"

@class UIButton, UILabel;

@interface OFEnableOpenFeintInDashboardController : OFViewController <OFCallbackable> {
	UILabel* appNameLabel;
	UIButton* enableOpenFeintButton;
	UIButton* leaderboardsButton;
}
@property(retain, nonatomic) UILabel* appNameLabel;
@property(retain, nonatomic) UIButton* enableOpenFeintButton;
@property(retain, nonatomic) UIButton* leaderboardsButton;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)clickedEnableOpenFeint;
-(void)clickedLeaderboards;
-(void)_switchToOnlineMode;
-(void)_stayInOfflineMode;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

