/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextViewDelegate.h"

@class UITextField, OFTextView;
@protocol OFExpandableSinglelineTextFieldDelegate;

@interface OFExpandableSinglelineTextField : XXUnknownSuperclass <UITextViewDelegate> {
	UITextField* internalTextField;
	OFTextView* internalTextView;
	float lineHeight;
	int minLines;
	int maxLines;
	BOOL shouldModifySize;
	id<OFExpandableSinglelineTextFieldDelegate> multilineTextFieldDelegate;
}
@property(assign) int minLines;
@property(assign) int maxLines;
@property(assign) id<OFExpandableSinglelineTextFieldDelegate> multilineTextFieldDelegate;
@property(assign) BOOL shouldModifySize;
-(void)dealloc;
-(void)awakeFromNib;
-(void)setText:(id)text;
-(id)text;
-(BOOL)canBecomeFirstResponder;
-(BOOL)becomeFirstResponder;
-(BOOL)canResignFirstResponder;
-(BOOL)resignFirstResponder;
-(BOOL)isFirstResponder;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
@end

