/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFExtendedCredentialController.h"
#import "OFFacebookAccountController.h"


@interface OFFacebookExtendedCredentialController : OFFacebookAccountController <OFExtendedCredentialController> {
	OFDelegate onSuccess;
	OFDelegate onFailure;
	OFDelegate onCancel;
}
-(void)viewWillAppear:(BOOL)view;
-(void)dialogDidCancel:(id)dialog;
-(void)onFormSubmitted:(id)submitted;
-(void)displayError:(id)error;
-(id)singularResourceName;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(bool)canReceiveCallbacksNow;
-(void)getExtendedCredentials:(const OFDelegate*)credentials onFailure:(const OFDelegate*)failure onCancel:(const OFDelegate*)cancel;
-(void)registerActionsNow;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

