/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFBDialogDelegate.h"
#import "OFFBRequestDelegate.h"
#import "OFFBSessionDelegate.h"
#import "DoodleJump-Structs.h"
#import "OFAccountSetupBaseController.h"

@class UIView, UIImageView, NSURL, OFFBDialog, OFFBSession;

@interface OFFacebookAccountController : OFAccountSetupBaseController <OFFBSessionDelegate, OFFBDialogDelegate, OFFBRequestDelegate> {
	unsigned long long fbuid;
	OFFBSession* fbSession;
	NSURL* urlToLaunch;
	UIImageView* fbLoggedInStatusImageView;
	int orientationBeforeFix;
	UIView* invisibleKeyboardTrap;
	BOOL getPostingPermission;
	OFFBDialog* loginDialog;
	bool skipLoginOnAppear;
	bool updateServerPostingPermissions;
}
@property(assign, nonatomic) unsigned long long fbuid;
@property(retain, nonatomic) NSURL* urlToLaunch;
@property(retain, nonatomic) UIImageView* fbLoggedInStatusImageView;
@property(retain, nonatomic) OFFBSession* fbSession;
@property(assign, nonatomic) BOOL getPostingPermission;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(id)getFormSubmissionUrl;
-(void)onAfterFormSubmitted;
-(void)closeLoginDialog;
-(id)_getFormSubmissionUrl;
-(void)_session:(id)session didLogin:(unsigned long long)login;
-(bool)shouldUseOAuth;
-(void)registerActionsNow;
-(void)logoutFromFacebook;
-(void)promptToLogin;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)session:(id)session didLogin:(unsigned long long)login;
-(void)dialogDidCancel:(id)dialog;
-(void)dialogDidSucceed:(id)dialog;
-(void)displayError:(id)error;
-(void)request:(id)request didFailWithError:(id)error;
-(void)requestWasCancelled;
-(void)dialog:(id)dialog didFailWithError:(id)error;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onPresentingErrorDialog;
-(BOOL)dialog:(id)dialog shouldOpenURLInExternalBrowser:(id)externalBrowser;
-(void)dealloc;
@end

