/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFFacebookAccountController.h"

@class OFTFBDialog, UILabel, UIViewController;

@interface OFFacebookAccountLoginController : OFFacebookAccountController {
	UILabel* findFriendsLabel;
	UIViewController* controllerToPopTo;
	BOOL isComplete;
	BOOL wantToUpdatePostingPermissions;
	BOOL initialFormHasBeenSubmitted;
	OFTFBDialog* successfulExtendedCredentialsDialog;
}
@property(retain, nonatomic) UILabel* findFriendsLabel;
@property(retain, nonatomic) UIViewController* controllerToPopTo;
@property(retain, nonatomic) OFTFBDialog* successfulExtendedCredentialsDialog;
-(void)viewWillAppear:(BOOL)view;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(id)singularResourceName;
-(id)_getFormSubmissionUrl;
-(void)_session:(id)session didLogin:(unsigned long long)login;
-(id)getLoadingScreenText;
-(id)controllerToPushOnCompletion;
-(BOOL)isComplete;
-(void)onAfterFormSubmitted;
-(void)dialogDidSucceed:(id)dialog;
-(void)onFormSubmitted:(id)submitted;
-(id)getControllerToPopTo;
-(void)dialogDidCancel:(id)dialog;
-(void)dealloc;
@end

