/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFFormControllerHelper.h"
#import "OFCallbackable.h"

@class OFMultilineTextField, UIView, UIButton, UILabel;

@interface OFFavoriteThisGameController : OFFormControllerHelper <OFCallbackable> {
	UIButton* favoriteButton;
	UILabel* descriptionLabel;
	BOOL isFavorite;
	OFMultilineTextField* reviewTextField;
	UIView* reviewArea;
}
@property(retain, nonatomic) UIButton* favoriteButton;
@property(retain, nonatomic) OFMultilineTextField* reviewTextField;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain, nonatomic) UIView* reviewArea;
-(void)dealloc;
-(id)getClientApplicationId;
-(id)getClientApplicationName;
-(void)setReviewAreaAvailable:(BOOL)available animate:(BOOL)animate;
-(void)viewWillAppear:(BOOL)view;
-(void)setButtonImage:(id)image;
-(void)onGameIsFavorite:(id)favorite;
-(void)onGameIsNotFavorite;
-(void)onReviewLoaded:(id)loaded;
-(void)onRequestSucceeded;
-(void)onIsFavoriteChanged;
-(void)onRequestFailed;
-(void)updateState:(BOOL)state makeFavorite:(BOOL)favorite successDelegate:(OFDelegate)delegate;
-(void)onReviewSubmitted;
-(void)onFavoritePressed;
-(void)onSubmitReviewPressed;
-(bool)canReceiveCallbacksNow;
-(id)getFormSubmissionUrl;
-(void)registerActionsNow;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(id)singularResourceName;
-(void)onFormSubmitted:(id)submitted;
@end

