/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol OFFBSessionDelegate <NSObject>
-(void)session:(id)session didLogin:(unsigned long long)login;
@optional
-(void)sessionDidNotLogin:(id)session;
-(void)session:(id)session willLogout:(unsigned long long)logout;
-(void)sessionDidLogout:(id)session;
@end

