/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFBRequestDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSError, NSConditionLock;

@interface OFFBUploadResultReceiver : XXUnknownSuperclass <OFFBRequestDelegate> {
	NSConditionLock* _uploadLock;
	int _uploadResult;
	NSError* _uploadError;
}
@property(retain, nonatomic) NSConditionLock* _uploadLock;
@property(assign, nonatomic) int _uploadResult;
@property(retain, nonatomic) NSError* _uploadError;
-(id)init;
-(void)dealloc;
-(void)requestWithParams:(id)params;
-(void)requestAndReceiveResult:(id)result;
-(void)request:(id)request didLoad:(id)load;
-(void)request:(id)request didFailWithError:(id)error;
@end

