/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFBSessionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class OFFBSession, UIImageView;

@interface OFFBLoginButton : XXUnknownSuperclass <OFFBSessionDelegate> {
	int _style;
	OFFBSession* _session;
	UIImageView* _imageView;
}
@property(retain, nonatomic) OFFBSession* session;
@property(assign, nonatomic) int style;
+(void)initialize;
-(id)buttonImage;
-(id)buttonHighlightedImage;
-(void)updateImage;
-(void)touchUpInside;
-(void)initButton;
-(id)initWithFrame:(CGRect)frame;
-(void)awakeFromNib;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(void)setHighlighted:(BOOL)highlighted;
-(void)session:(id)session didLogin:(unsigned long long)login;
-(void)sessionDidLogout:(id)session;
-(BOOL)isAccessibilityElement;
-(unsigned long long)accessibilityTraits;
-(id)accessibilityLabel;
@end

