/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFBRequestDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFFBNativeStringUploader : XXUnknownSuperclass <OFFBRequestDelegate> {
}
+(int)uploadStringSet:(id)set error:(id*)error;
@end

