/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFBRequestDelegate.h"
#import "OFTFBDialog.h"

@class OFFBRequest;

@interface OFFBLoginDialog : OFTFBDialog <OFFBRequestDelegate> {
	OFFBRequest* _getSessionRequest;
}
-(void)connectToGetSession:(id)getSession;
-(void)loadLoginPage;
-(id)initWithSession:(id)session;
-(void)dealloc;
-(void)load;
-(void)dialogWillDisappear;
-(void)dialogDidSucceed:(id)dialog;
-(void)request:(id)request didLoad:(id)load;
-(void)request:(id)request didFailWithError:(id)error;
@end

