/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, NSString, NSMutableArray, NSDate;

@interface OFFBSession : XXUnknownSuperclass {
	NSMutableArray* _delegates;
	NSString* _apiKey;
	NSString* _apiSecret;
	NSString* _getSessionProxy;
	unsigned long long _uid;
	NSString* _sessionKey;
	NSString* _sessionSecret;
	NSDate* _expirationDate;
	NSMutableArray* _requestQueue;
	NSDate* _lastRequestTime;
	int _requestBurstCount;
	NSTimer* _requestTimer;
}
@property(readonly, assign, nonatomic) NSMutableArray* delegates;
@property(readonly, assign, nonatomic) NSString* apiKey;
@property(readonly, assign, nonatomic) NSString* apiSecret;
@property(readonly, assign, nonatomic) NSString* getSessionProxy;
@property(readonly, assign, nonatomic) unsigned long long uid;
@property(readonly, assign, nonatomic) NSString* sessionKey;
@property(readonly, assign, nonatomic) NSString* sessionSecret;
@property(readonly, assign, nonatomic) NSDate* expirationDate;
@property(readonly, assign, nonatomic) BOOL isConnected;
@property(readonly, assign, nonatomic) NSString* apiSecureURL;
@property(readonly, assign, nonatomic) NSString* apiURL;
+(id)session;
+(void)setSession:(id)session;
+(id)sessionForApplication:(id)application secret:(id)secret delegate:(id)delegate;
+(id)sessionForApplication:(id)application getSessionProxy:(id)proxy delegate:(id)delegate;
-(void)save;
-(void)unsave;
-(void)startFlushTimer;
-(void)enqueueRequest:(id)request;
-(BOOL)performRequest:(id)request enqueue:(BOOL)enqueue;
-(void)flushRequestQueue;
-(void)requestTimerReady;
-(id)initWithKey:(id)key secret:(id)secret getSessionProxy:(id)proxy;
-(void)dealloc;
-(void)begin:(unsigned long long)begin sessionKey:(id)key sessionSecret:(id)secret expires:(id)expires;
-(BOOL)resume;
-(void)cancelLogin;
-(void)logout;
-(void)send:(id)send;
-(void)deleteFacebookCookies;
@end

