/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFGameDiscoveryImageHyperlinkCell.h"
#import "OFCallbackable.h"

@class NSTimer, UIImageView, NSMutableArray;

@interface OFFeaturedGameCell : OFGameDiscoveryImageHyperlinkCell <OFCallbackable> {
	UIImageView* bgImageView;
	NSMutableArray* imageHyperlinks;
	unsigned currentHyperlinkIndex;
	NSTimer* cyclingTimer;
	float inProgressTransitionRemainingSeconds;
	BOOL viewIsAppeared;
	BOOL hasDownloadedLinks;
}
@property(retain, nonatomic) NSMutableArray* imageHyperlinks;
@property(assign, nonatomic) unsigned currentHyperlinkIndex;
@property(retain, nonatomic) NSTimer* cyclingTimer;
-(id)_getCurrentImageHyperlink;
-(void)_stopCyclingHyperlinks;
-(void)_scheduleNextHyperlinkTransitionIn:(float)anIn;
-(void)_fadeToNextFeaturedGame;
-(void)onFeaturedGamesDownloaded:(id)downloaded;
-(id)_bannerSuffix;
-(void)_changeBannerToOnline;
-(void)_changeBannerToOffline;
-(void)_commonInit;
-(id)initOFTableCellHelper:(id)helper;
-(void)dealloc;
-(bool)canReceiveCallbacksNow;
-(void)viewDidAppear;
-(void)viewDidDisappear;
-(void)onResourceChanged:(id)changed;
@end

