/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UISearchBarDelegate.h"
#import "OFTableSequenceControllerHelper.h"


@interface OFFindUserController : OFTableSequenceControllerHelper <UISearchBarDelegate> {
	OFRetainedPtr<NSString> mCurrentName;
}
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundMessage;
-(id)getDataNotLoadedYetMessage;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)onTableHeaderCreated:(id)created;
-(bool)autoLoadData;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(id)getTableHeaderControllerName;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

