/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"

@class OFForumTopic, UIButton, OFForumThread;

@interface OFForumThreadViewController : OFTableSequenceControllerHelper {
	OFForumThread* thread;
	OFForumTopic* topic;
	BOOL hideSubscribeAndReplyButtons;
	UIButton* subscribeButton;
}
@property(retain, nonatomic) OFForumThread* thread;
@property(retain, nonatomic) OFForumTopic* topic;
@property(retain, nonatomic) UIButton* subscribeButton;
+(id)threadView:(id)view topic:(id)topic;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(bool)shouldAlwaysRefreshWhenShown;
-(bool)usePlainTableSectionHeaders;
-(id)getLeadingCellControllerNameForSection:(id)section;
-(void)setSubscribeButtonForSubscriptionStatus:(BOOL)subscriptionStatus;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getNoDataFoundMessage;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(BOOL)shouldEnableNextButtonWithSection:(id)section indexPath:(id)path;
-(void)_reply;
-(void)_subscribeSuccess;
-(void)_subscribeFailure;
-(void)_subscribe;
@end

