/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"

@class OFForumTopic;

@interface OFForumThreadListController : OFTableSequenceControllerHelper {
	OFForumTopic* topic;
	BOOL justPostedNewThread;
}
@property(retain) OFForumTopic* topic;
+(id)threadBrowser:(id)browser;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(bool)shouldAlwaysRefreshWhenShown;
-(bool)usePlainTableSectionHeaders;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getNoDataFoundMessage;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)_post;
@end

