/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UITextViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "OFFormControllerHelper.h"
#import "OFCallbackable.h"
#import "OFViewController.h"

@class UIView, UIScrollView;

@interface OFFormControllerHelper : OFViewController <OFCallbackable, UITextFieldDelegate, UITextViewDelegate> {
	map<int,OFDelegate,std::less<int>,std::allocator<std::pair<const int, OFDelegate> > > mTagActions;
	UIScrollView* mScrollContainerView;
	UIView* mActiveTextField;
	OFPointer<OFViewDataMap> mViewDataMap;
	OFPointer<OFHttpService> mHttpService;
	bool mIsKeyboardShown;
	float mViewHeightWithoutKeyboard;
	float mViewOriginYWithoutKeyboardiPad;
	BOOL mIsSubmitting;
}
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(void)onTriggerAction:(id)action;
-(void)onTriggerBarAction:(id)action;
-(void)registerAction:(OFDelegate)action forTag:(int)tag;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

@interface OFFormControllerHelper (EditingSupport)
-(void)_scrollToActiveTextField;
-(void)_KeyboardDidShow:(id)_Keyboard;
-(void)_KeyboardDidHide:(id)_Keyboard;
-(void)textViewDidBeginEditing:(id)textView;
-(void)textViewDidEndEditing:(id)textView;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

@interface OFFormControllerHelper (Overridables)
-(void)onBeforeFormSubmitted;
-(void)onAfterFormSubmitted;
-(void)onPresentingErrorDialog;
-(id)getResourceRequest;
-(id)getFormSubmissionUrl;
-(void)registerActionsNow;
-(id)singularResourceName;
-(void)onFormSubmitted:(id)submitted;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(id)getLoadingScreenText;
-(bool)shouldUseOAuth;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(bool)shouldShowLoadingScreenWhileSubmitting;
-(bool)shouldDismissKeyboardWhenSubmitting;
-(BOOL)usesXP;
-(id)getHTTPMethod;
@end

@interface OFFormControllerHelper (Submit)
-(void)_submitFormOFServer;
-(void)_submitFormXPServer;
-(void)submitForm;
-(void)_requestRespondedBehaviorXP:(id)xp;
-(void)_requestRespondedBehavior:(id)behavior;
-(void)_requestErroredBehavior:(id)behavior;
-(void)_requestErroredWithMessage:(id)message;
-(void)onSubmitForm:(id)form;
@end

