/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UIImageView, UILabel;

@interface OFForumThreadCell : OFTableCellHelper {
	UILabel* titleLabel;
	UILabel* stickyLabel;
	UILabel* postsCountLabel;
	UILabel* lastPostByLabel;
	UIImageView* favoritedIcon;
	UIImageView* threadStatusIcon;
}
-(void)dealloc;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
@end

