/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UIImageView, UILabel;

@interface OFForumTopicCell : OFTableCellHelper {
	UILabel* titleLabel;
	UIImageView* topicIcon;
}
-(BOOL)hasConstantHeight;
-(void)dealloc;
-(void)onResourceChanged:(id)changed;
@end

