/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFUser, OFImageView, UIView, UILabel;

@interface OFForumPostCell : OFTableCellHelper {
	UIView* contentWrapperView;
	OFImageView* authorPictureView;
	UILabel* authorLabel;
	UILabel* gameLabel;
	UILabel* bodyLabel;
	OFUser* author;
}
-(void)dealloc;
-(void)layoutSubviews;
-(void)onResourceChanged:(id)changed;
-(void)_goToProfile;
@end

