/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIView;
@protocol OFFramedContentWrapperViewDelegate;

@interface OFFramedContentWrapperView : XXUnknownSuperclass {
	UIView* wrappedView;
	UIEdgeInsets contentInsets;
	id<OFFramedContentWrapperViewDelegate> delegate;
}
@property(retain, nonatomic) UIView* wrappedView;
@property(assign, nonatomic) id<OFFramedContentWrapperViewDelegate> delegate;
-(id)initWithWrappedView:(id)wrappedView;
-(void)_updateWrappedView;
-(void)setContentInsets:(UIEdgeInsets)insets;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
@end

