/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, OFGameProfilePageInfo, OFUser, OFBannerCell;

@interface OFFramedControllerInfo : XXUnknownSuperclass {
	UIViewController* controller;
	OFBannerCell* banner;
	OFUser* user;
	OFUser* comparedToUser;
	OFGameProfilePageInfo* clientApplicationInfo;
}
@property(retain, nonatomic) OFUser* user;
@property(retain, nonatomic) OFUser* comparedToUser;
@property(retain, nonatomic) OFGameProfilePageInfo* clientApplicationInfo;
@property(readonly, assign, nonatomic) UIViewController* controller;
@property(retain, nonatomic) OFBannerCell* banner;
+(id)withController:(id)controller andClientApplicationInfo:(id)info;
-(void)dealloc;
@end

