/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

@interface OFFriendImporter : XXUnknownSuperclass <OFCallbackable> {
	UIViewController* mController;
	OFRetainedPtr<NSString> mImportCompleteMessage;
	OFRetainedPtr<NSString> mCredentialType;
	OFRetainedPtr<NSString> mLinkCredentialControllerName;
}
+(id)friendImporterWithController:(id)controller;
-(void)pushCompleteControllerWithMessage:(id)message andTitle:(id)title;
-(void)importFriendsSucceeded;
-(void)importFriendsFailed;
-(void)onUsersCredentialsDownloaded:(id)downloaded;
-(void)importFromSocialNetwork;
-(void)importFromTwitter;
-(void)importFromFacebook;
-(void)findByName;
-(void)dealloc;
-(bool)canReceiveCallbacksNow;
-(void)controllerDealloced;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

