/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFTableSequenceControllerHelper.h"

@class UIPopoverController, NSString;
@protocol OFFriendPickerDelegate;

@interface OFFriendPickerController : OFTableSequenceControllerHelper <OFCallbackable> {
	id<OFFriendPickerDelegate> delegate;
	NSString* promptText;
	NSString* scopedByApplicationId;
	UIPopoverController* owningPopoverController;
}
@property(retain, nonatomic) id<OFFriendPickerDelegate> delegate;
@property(retain, nonatomic) NSString* promptText;
@property(retain, nonatomic) NSString* scopedByApplicationId;
@property(assign, nonatomic) UIPopoverController* owningPopoverController;
+(void)launchPickerWithDelegate:(id)delegate;
+(void)launchPickerWithDelegate:(id)delegate promptText:(id)text;
+(void)launchPickerWithDelegate:(id)delegate promptText:(id)text mustHaveApplicationId:(id)anId;
-(void)dealloc;
-(bool)canReceiveCallbacksNow;
-(void)viewWillAppear:(BOOL)view;
-(void)dismiss;
-(void)_customFailHandler;
-(OFDelegate)getOnFailureDelegate;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundViewController;
-(id)getNoDataFoundMessage;
-(void)onLeadingCellWasLoaded:(id)loaded forSection:(id)section;
-(id)getLeadingCellControllerNameForSection:(id)section;
-(id)getTableHeaderControllerName;
-(bool)usePlainTableSectionHeaders;
-(void)onTableHeaderCreated:(id)created;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)cancel;
-(bool)allowPagination;
-(BOOL)shouldAlwaysShowNavBar;
@end

