/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTabbedPageHeaderController.h"
#import "OFTableControllerHeader.h"


@interface OFFriendsHeaderController : OFTabbedPageHeaderController <OFTableControllerHeader> {
	BOOL isForLocalUser;
}
-(void)setIsDisplayingForLocalUser:(BOOL)localUser;
-(void)resizeView:(id)view;
-(void)dealloc;
@end

