/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"

@class UIViewController, UILabel;

@interface OFFullScreenImportFriendsMessage : OFViewController {
	UIViewController* owner;
	UILabel* messageLabel;
}
@property(assign, nonatomic) UIViewController* owner;
@property(assign, nonatomic) UILabel* messageLabel;
-(void)dealloc;
-(void)onImportFriendsPressed;
-(void)setMissingCredentials:(id)credentials withNotice:(id)notice;
@end

