/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIImageView, UILabel;

@interface OFGameDiscoveryNewsItemCell : OFTableCellHelper {
	UIImageView* iconFrame;
	OFImageView* iconView;
	UILabel* titleLabel;
	UILabel* subtitleLabel;
}
@property(retain, nonatomic) UIImageView* iconFrame;
@property(retain, nonatomic) OFImageView* iconView;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UILabel* subtitleLabel;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

