/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFWebViewController.h"

@class OFGameDiscoveryNewsItem;

@interface OFGameDiscoveryNewsItemController : OFWebViewController {
	OFGameDiscoveryNewsItem* mNewsItem;
}
@property(retain, nonatomic) OFGameDiscoveryNewsItem* newsItem;
-(id)getAction;
-(id)getTitle;
-(void)dealloc;
@end

