/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"


@interface OFGamerscore : OFResource {
	unsigned userId;
	unsigned gamerscore;
}
@property(readonly, assign, nonatomic) unsigned userId;
@property(readonly, assign, nonatomic) unsigned gamerscore;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setUserId:(id)anId;
-(void)setGamerscore:(id)gamerscore;
-(void)dealloc;
@end

