/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSString;

@interface OFGameDiscoveryCategory : OFResource {
	NSString* iconUrl;
	NSString* name;
	NSString* subtext;
	NSString* secondaryText;
	NSString* targetDiscoveryActionName;
	NSString* targetDiscoveryPageTitle;
}
@property(retain, nonatomic) NSString* iconUrl;
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* subtext;
@property(retain, nonatomic) NSString* secondaryText;
@property(retain, nonatomic) NSString* targetDiscoveryActionName;
@property(retain, nonatomic) NSString* targetDiscoveryPageTitle;
+(OFResourceDataMap*)getDataMap;
+(id)getService;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)dealloc;
@end

