/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class OFGameProfilePageInfo;

@interface OFGameProfilePageComparisonInfo : OFResource {
	OFGameProfilePageInfo* gameProfilePageInfo;
	int localUsersAchievementsScore;
	int comparedUsersAchievementsScore;
	int localUsersChallengesScore;
	int comparedUsersChallengesScore;
	int localUsersLeaderboardsScore;
	int comparedUsersLeaderboardsScore;
}
@property(readonly, assign, nonatomic) OFGameProfilePageInfo* gameProfilePageInfo;
@property(readonly, assign, nonatomic) int localUsersAchievementsScore;
@property(readonly, assign, nonatomic) int comparedUsersAchievementsScore;
@property(readonly, assign, nonatomic) int localUsersChallengesScore;
@property(readonly, assign, nonatomic) int comparedUsersChallengesScore;
@property(readonly, assign, nonatomic) int localUsersLeaderboardsScore;
@property(readonly, assign, nonatomic) int comparedUsersLeaderboardsScore;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setGameProfilePageInfo:(id)info;
-(void)setLocalUsersAchievementsScore:(id)score;
-(void)setComparedUsersAchievementsScore:(id)score;
-(void)setLocalUsersChallengesScore:(id)score;
-(void)setComparedUsersChallengesScore:(id)score;
-(void)setLocalUsersLeaderboardsScore:(id)score;
-(void)setComparedUsersLeaderboardsScore:(id)score;
-(void)dealloc;
@end

