/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSString;

@interface OFGameDiscoveryNewsItem : OFResource {
	NSString* iconUrl;
	NSString* title;
	NSString* subtitle;
}
@property(retain, nonatomic) NSString* iconUrl;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* subtitle;
+(OFResourceDataMap*)getDataMap;
+(id)getService;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)dealloc;
@end

