/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class OFUser, NSString;

@interface OFGamePlayer : OFResource {
	OFUser* user;
	NSString* applicationId;
	unsigned applicationGamerscore;
	BOOL isFavorite;
}
@property(readonly, assign, nonatomic) OFUser* user;
@property(readonly, assign, nonatomic) NSString* applicationId;
@property(readonly, assign, nonatomic) unsigned applicationGamerscore;
@property(readonly, assign, nonatomic) BOOL isFavorite;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setIsFavorite:(id)favorite;
-(void)setApplicationId:(id)anId;
-(void)setApplicationGamerscore:(id)gamerscore;
-(void)setUser:(id)user;
-(void)dealloc;
@end

