/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFGameCenterHighScore : XXUnknownSuperclass <OFCallbackable> {
	vector<OFPointer<OFHighScoreBatchEntry>,std::allocator<OFPointer<OFHighScoreBatchEntry> > > scores;
	BOOL silently;
	NSString* message;
	OFDelegate successDelegate;
	OFDelegate failureDelegate;
	OFDelegate uploadBlobDelegate;
	unsigned openFeintStatus;
	unsigned gameCenterStatus;
	unsigned gameCenterCount;
}
@property(assign, nonatomic) BOOL silently;
@property(retain, nonatomic) NSString* message;
-(id)initWithSeries:(vector<OFPointer<OFHighScoreBatchEntry>,std::allocator<OFPointer<OFHighScoreBatchEntry> > >*)series;
-(void)dealloc;
-(id)submitOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure onUploadBlob:(const OFDelegate*)blob;
-(void)openFeintSuccess:(id)success;
-(void)openFeintFailure;
-(void)testCompletion;
-(void)testCompletion:(id)completion;
-(bool)canReceiveCallbacksNow;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

