/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFPlayedGameController.h"
#import "OFProfileFrame.h"
#import "DoodleJump-Structs.h"


@interface OFGameDiscoveryController : OFPlayedGameController <OFProfileFrame> {
}
-(void)viewWillAppear:(BOOL)view;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundMessage;
-(bool)allowEditing;
-(void)_createAndDisplayTableHeader;
@end

