/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"

@class UILabel;

@interface OFGameCenterIntegrationController : OFViewController {
	UILabel* nowPlayingLabel;
}
@property(retain, nonatomic) UILabel* nowPlayingLabel;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)onContinue;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
@end

