/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFHighScore.h"
#import "OFResource.h"
#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"

@class NSString, NSData, OFUser, OFS3UploadParameters;

@interface OFHighScore : OFResource <OFCallbackable> {
	OFUser* user;
	long long score;
	int rank;
	NSString* leaderboardId;
	NSString* displayText;
	NSString* customData;
	NSData* blob;
	NSString* blobUrl;
	NSString* toHighRankText;
	unsigned gameCenterSeconds;
	NSString* gameCenterId;
	NSString* gameCenterName;
	OFS3UploadParameters* blobUploadParameters;
	double latitude;
	double longitude;
	double distance;
}
@property(readonly, assign, nonatomic) double latitude;
@property(readonly, assign, nonatomic) double longitude;
@property(readonly, assign, nonatomic) double distance;
@property(retain, nonatomic) NSData* blob;
@property(readonly, retain, nonatomic) NSString* blobUrl;
@property(readonly, assign, nonatomic) OFUser* user;
@property(readonly, assign, nonatomic) int rank;
@property(readonly, retain, nonatomic) NSString* leaderboardId;
@property(readonly, assign, nonatomic) unsigned gameCenterSeconds;
@property(readonly, retain, nonatomic) NSString* gameCenterId;
@property(retain, nonatomic) NSString* gameCenterName;
@property(assign, nonatomic) long long score;
@property(retain, nonatomic) NSString* displayText;
@property(retain, nonatomic) NSString* customData;
@property(readonly, retain, nonatomic) OFS3UploadParameters* blobUploadParameters;
@property(readonly, retain, nonatomic) NSString* toHighRankText;
+(void)setDelegate:(id)delegate;
+(id)allHighScoresForCurrentUser;
+(id)getHighScoresNearCurrentUserForLeaderboard:(id)leaderboard andBetterCount:(unsigned)count andWorseCount:(unsigned)count3;
+(void)_getHighScoresNearCurrentUserSuccess:(id)success;
+(void)_getHighScoresNearCurrentUserFailure;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
+(bool)canReceiveCallbacksNow;
-(id)initForSubmissionWithScore:(long long)score;
-(void)submitTo:(id)to;
-(id)downloadBlob;
-(void)_submitToSuccess;
-(void)_submitToFailure;
-(void)_downloadBlobSuccess:(id)success;
-(void)_downloadBlobFailure;
-(id)initWithLocalSQL:(OFSqlQuery*)localSQL forUser:(id)user rank:(unsigned)rank;
-(BOOL)hasBlob;
-(void)setUser:(id)user;
-(void)_setScore:(id)score;
-(void)setRank:(id)rank;
-(void)setLeaderboardId:(id)anId;
-(void)_setDisplayText:(id)text;
-(void)setToHighRankText:(id)highRankText;
-(void)_setCustomData:(id)data;
-(void)setBlobUrl:(id)url;
-(void)setBlobUploadParameters:(id)parameters;
-(void)_setBlob:(id)blob;
-(void)setLatitude:(id)latitude;
-(void)setLongitude:(id)longitude;
-(void)setDistance:(id)distance;
-(void)setGameCenterSeconds:(id)seconds;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

@interface OFHighScore (GameCenter)
-(id)initWithOfScore:(id)score withRank:(int)rank;
-(id)initWithGkScore:(id)gkScore withRank:(int)rank;
-(void)setOverrideRank:(int)rank;
-(id)description;
@end

