/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class OFImageView;

@interface OFHighScoreAnnotationView : XXUnknownSuperclass {
	OFImageView* profilePictureView;
	OFImageView* mapImageView;
}
-(id)initWithAnnotation:(id)annotation reuseIdentifier:(id)identifier;
-(void)setHighScoreAnnotation:(id)annotation;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)dealloc;
@end

