/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "MKMapViewDelegate.h"
#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"

@class NSString, CLLocation, OFLeaderboard_Sync, OFHighScoreAnnotation, MKMapView, OFDefaultButton, NSMutableArray;

@interface OFHighScoreMapViewController : OFViewController <MKMapViewDelegate, OFCallbackable> {
	MKMapView* mapView;
	CLLocation* locationOfUser;
	OFLeaderboard_Sync* leaderboardInfo;
	NSString* leaderboardId;
	OFHighScoreAnnotation* annotationForUser;
	bool receivedScores;
	bool zoomToLocation;
	CLLocation* locationOfCenter;
	double smallestBoarderDistance;
	OFDefaultButton* refreshButton;
	OFDefaultButton* findMeButton;
	OFDefaultButton* closeButton;
	XXStruct_zYrK5D boundaryCoordNE;
	XXStruct_zYrK5D boundaryCoordSW;
	int dontShowit;
	NSMutableArray* annotations;
}
@property(retain, nonatomic) OFLeaderboard_Sync* leaderboardInfo;
@property(retain) CLLocation* locationOfUser;
@property(retain) CLLocation* locationOfCenter;
-(void)dealloc;
-(void)viewDidLoad;
-(void)loadAnnotationsFromHighScores:(id)highScores;
-(void)setBoundaryCoordinates;
-(bool)isNewCoordinateInsideView;
-(void)setLeaderboard:(id)leaderboard;
-(void)determineIfResetShouldShow;
-(void)doIndexAction:(id)action radius:(int)radius userMapMode:(id)mode;
-(void)getScores;
-(void)_clickedRefresh;
-(void)findMe;
-(id)getAnnotationForHighScore:(id)highScore;
-(void)rankVisibleAnnotations;
-(id)getAnnotationView:(id)view;
-(void)mapView:(id)view regionDidChangeAnimated:(BOOL)region;
-(void)mapViewDidFinishLoadingMap:(id)mapView;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)mapView:(id)view annotationView:(id)view2 calloutAccessoryControlTapped:(id)tapped;
-(bool)canReceiveCallbacksNow;
@end

