/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIImageView, OFUserRelationshipIndicator, UIButton, UILabel;

@interface OFHighScoreCell : OFTableCellHelper {
	OFImageView* profilePictureView;
	UILabel* nameLabel;
	UILabel* distLabel;
	UILabel* scoreLabel;
	UIImageView* disclosureIndicator;
	UIButton* downloadBlobButton;
	OFUserRelationshipIndicator* relationshipIndicator;
}
@property(retain, nonatomic) UIImageView* disclosureIndicator;
@property(retain, nonatomic) UIButton* downloadBlobButton;
@property(retain, nonatomic) OFImageView* profilePictureView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UILabel* distLabel;
@property(retain, nonatomic) UILabel* scoreLabel;
@property(retain, nonatomic) OFUserRelationshipIndicator* relationshipIndicator;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)awakeFromNib;
-(void)downloadBlobClicked;
-(void)dealloc;
@end

