/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFViewController.h"


@interface OFImportFriendsController : OFViewController {
	OFRetainedPtr<OFFriendImporter> mImporter;
}
-(void)onImportFromTwitter;
-(void)onImportFromFacebook;
-(void)onFindByName;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)setController:(id)controller;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

