/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"


@interface OFInvitationsController : OFTableSequenceControllerHelper {
	BOOL reloadOnWillAppear;
}
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)_updateEditButtonState;
-(void)_toggleEditing;
-(bool)allowEditing;
-(void)onResourcesDownloaded:(id)downloaded;
-(void)onResourceWasDeleted:(id)deleted;
-(void)viewWillAppear:(BOOL)view;
-(void)notifyInviteIgnored:(id)ignored;
-(id)getNoDataFoundMessage;
-(bool)usePlainTableSectionHeaders;
-(void)viewDidLoad;
@end

