/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFInboxController.h"


@interface OFInboxIMConversationsController : OFInboxController {
}
-(void)loadView;
-(void)viewWillAppear:(BOOL)view;
-(id)getNoDataFoundMessage;
-(void)onBeforeResourcesProcessed:(id)processed;
-(void)onResourcesDownloaded:(id)downloaded;
@end

