/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIView, UILabel;

@interface OFInviteCell : OFTableCellHelper {
	OFImageView* inviteIcon;
	UILabel* gameTitle;
	UILabel* invitedBy;
	UILabel* userMessage;
	UIView* freshnessIndicator;
}
@property(retain, nonatomic) OFImageView* inviteIcon;
@property(retain, nonatomic) UILabel* gameTitle;
@property(retain, nonatomic) UILabel* invitedBy;
@property(retain, nonatomic) UILabel* userMessage;
@property(retain, nonatomic) UIView* freshnessIndicator;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

