/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class NSString;

@interface OFInviteDefinition : OFResource <OFCallbackable> {
	NSString* clientApplicationName;
	NSString* clientApplicationID;
	NSString* inviteIdentifier;
	NSString* senderParameter;
	NSString* receiverParameter;
	NSString* inviteIconURL;
	NSString* developerMessage;
	NSString* receiverNotification;
	NSString* senderNotification;
	NSString* senderIncentiveText;
	NSString* suggestedSenderMessage;
	OFPointer<OFHttpService> mHttpService;
	OFPointer<OFImageViewHttpServiceObserver> mHttpServiceObserver;
}
@property(readonly, assign, nonatomic) NSString* clientApplicationName;
@property(readonly, assign, nonatomic) NSString* clientApplicationID;
@property(readonly, assign, nonatomic) NSString* inviteIdentifier;
@property(readonly, assign, nonatomic) NSString* senderParameter;
@property(readonly, assign, nonatomic) NSString* receiverParameter;
@property(readonly, assign, nonatomic) NSString* inviteIconURL;
@property(readonly, assign, nonatomic) NSString* developerMessage;
@property(readonly, assign, nonatomic) NSString* receiverNotification;
@property(readonly, assign, nonatomic) NSString* senderNotification;
@property(readonly, assign, nonatomic) NSString* senderIncentiveText;
@property(readonly, assign, nonatomic) NSString* suggestedSenderMessage;
+(void)setDelegate:(id)delegate;
+(id)getPrimaryInviteDefinition;
+(id)getInviteDefinition:(id)definition;
+(void)_getPrimaryInviteDefinitionSuccess:(id)success;
+(void)_getPrimaryInviteDefinitionFailure;
+(void)_getInviteDefinitionSuccess:(id)success;
+(void)_getInviteDefinitionFailure;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(bool)canReceiveCallbacksNow;
-(id)getInviteIcon;
-(void)_getInviteIconSuccess:(id)success;
-(void)_getInviteIconFailure;
-(void)setClientApplicationName:(id)name;
-(void)setClientApplicationID:(id)anId;
-(void)setInviteIdentifier:(id)identifier;
-(void)setSenderParameter:(id)parameter;
-(void)setReceiverParameter:(id)parameter;
-(void)setInviteIconURL:(id)url;
-(void)setDeveloperMessage:(id)message;
-(void)setReceiverNotification:(id)notification;
-(void)setSenderNotification:(id)notification;
-(void)setSenderIncentiveText:(id)text;
-(void)setSuggestedSenderMessage:(id)message;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

