/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelperActionCell.h"

@class UIView;

@interface OFInboxIMActionCell : OFTableCellHelperActionCell {
	UIView* inlayView;
}
@property(retain, nonatomic) UIView* inlayView;
-(void)addInlay;
-(void)awakeFromNib;
-(void)dealloc;
@end

