/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UIActionSheetDelegate.h"
#import "OFTableSequenceControllerHelper.h"
#import "OFFriendPickerDelegate.h"

@class OFUser, NSIndexPath;

@interface OFInboxController : OFTableSequenceControllerHelper <OFFriendPickerDelegate, UIActionSheetDelegate> {
	OFUser* pendingConversationUser;
	BOOL userPreviouslySelected;
	NSIndexPath* actionIndexPath;
}
@property(retain, nonatomic) NSIndexPath* actionIndexPath;
-(void)dealloc;
-(void)_conversationStarted:(id)started;
-(id)getNoDataFoundMessage;
-(void)_conversationError;
-(void)pickerFinishedWithSelectedUser:(id)selectedUser;
-(void)pickerCancelled;
-(id)initAndBeginConversationWith:(id)with;
-(void)beginConversationWith:(id)with;
-(bool)autoLoadData;
-(void)_newMessagePressed;
-(void)viewDidAppear:(BOOL)view;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(bool)shouldAlwaysRefreshWhenShown;
-(bool)allowPagination;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getTableHeaderViewName;
-(void)onTableHeaderCreated:(id)created;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)actionCellClassName;
-(void)deletionWasSuccessful;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)actionPressedForTag:(unsigned)tag indexPath:(id)path;
@end

