/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextViewDelegate.h"
#import "OFTableControllerHeader.h"

@class OFInviteFriendsController, UITextView, UILabel;

@interface OFInviteFriendsHeaderController : XXUnknownSuperclass <OFTableControllerHeader, UITextViewDelegate> {
	BOOL finishedDownloadingChallenge;
	BOOL inviteTextHasDefaultText;
	OFInviteFriendsController* inviteFriendsController;
	UILabel* titleLabel;
	UITextView* inviteText;
	OFRetainedPtr<NSObject> selfRetainer;
	OFRetainedPtr<NSObject> parentRetainer;
}
@property(assign, nonatomic) OFInviteFriendsController* inviteFriendsController;
@property(readonly, assign, nonatomic) UILabel* titleLabel;
@property(readonly, assign, nonatomic) UITextView* inviteText;
-(void)awakeFromNib;
-(BOOL)textViewShouldBeginEditing:(id)textView;
-(BOOL)textViewShouldEndEditing:(id)textView;
-(void)textViewDidBeginEditing:(id)textView;
-(void)textViewDidEndEditing:(id)textView;
-(void)resizeView:(id)view;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

