/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UILabel, OFImageView;

@interface OFInviteNotificationController : XXUnknownSuperclass {
	UILabel* headerText;
	UILabel* notificationText;
	OFImageView* userIcon;
	UIImageView* bgImage;
}
@property(retain, nonatomic) UILabel* headerText;
@property(retain, nonatomic) UILabel* notificationText;
@property(retain, nonatomic) OFImageView* userIcon;
@property(retain, nonatomic) UIImageView* bgImage;
+(void)showInviteNotification:(id)notification withUser:(id)user withHeaderText:(id)headerText;
-(void)viewDidLoad;
-(void)dismiss;
-(void)dealloc;
@end

