/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFNotificationInputResponse.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationController, NSString;

@interface OFInputResponsePushController : XXUnknownSuperclass <OFNotificationInputResponse> {
	NSString* mControllerName;
	UINavigationController* mNavController;
	BOOL mShowAsModal;
}
+(id)responseWithControllerName:(id)controllerName andNavController:(id)controller andShowAsModal:(BOOL)modal;
-(id)initWithControllerName:(id)controllerName andNavController:(id)controller andShowAsModal:(BOOL)modal;
-(void)respondToInput;
-(void)dealloc;
@end

