/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"

@class OFNavigationController, OFContentFrameView, UIView;

@interface OFIntroNavigationController : OFViewController {
	OFContentFrameView* contentFrameView;
	OFNavigationController* navController;
	BOOL fullscreenFrame;
	UIView* loadingView;
}
@property(retain, nonatomic) OFContentFrameView* contentFrameView;
@property(retain, nonatomic) OFNavigationController* navController;
+(id)activeIntroNavigationController;
-(id)initWithNavigationController:(id)navigationController;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)dealloc;
-(void)fullscreenFrameOn;
-(void)fullscreenFrameOff;
-(void)setFullscreenFrame:(BOOL)frame;
-(BOOL)fullscreenFrame;
-(void)setFullscreenFrame:(BOOL)frame animated:(BOOL)animated;
-(float)bottomPadding;
-(void)displayLoadingView:(id)view;
-(void)removeLoadingView;
-(void)setApproved;
@end

