/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFShowMessageAndReturnController.h"

@class OFImageView, UIImageView;

@interface OFInviteCompleteController : OFShowMessageAndReturnController {
	OFImageView* inviteIcon;
	UIImageView* inviteIconFrame;
}
@property(retain, nonatomic) OFImageView* inviteIcon;
@property(retain, nonatomic) UIImageView* inviteIconFrame;
-(void)awakeFromNib;
-(void)dealloc;
@end

