/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFNotificationInputResponse.h"
#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

@interface OFInputResponseOpenDashboard : XXUnknownSuperclass <OFNotificationInputResponse> {
	OFRetainedPtr<NSString> mStartingTab;
	OFRetainedPtr<NSString> mControllerName;
	UIViewController* mStartingController;
}
-(id)initWithTab:(id)tab andController:(id)controller;
-(id)initWithTab:(id)tab andControllerName:(id)name;
-(void)dealloc;
-(void)respondToInput;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

