/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OFJsonValueType : XXUnknownSuperclass {
	SEL selector;
}
+(id)valueWithSelector:(SEL)selector;
-(id)initWithSelector:(SEL)selector;
-(void)setValue:(id)value onObject:(id)object;
@end

