/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFJsonValueType.h"


@interface OFJsonUrlValue : OFJsonValueType {
}
+(id)valueWithSelector:(SEL)selector;
-(void)setValue:(id)value onObject:(id)object;
@end

