/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFJsonParser : XXUnknownSuperclass {
	yajl_handle_t* handle;
	XXStruct_ZMV16B* callbacks;
	id delegate;
}
@property(assign, nonatomic) id delegate;
-(id)init;
-(void)dealloc;
-(void)parse:(id)parse;
-(void)parseData:(id)data;
-(void)finishParsing;
@end

