/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFJsonValueType.h"


@interface OFJsonObjectValue : OFJsonValueType {
	Class objectKlass;
}
@property(assign, nonatomic) Class objectKlass;
+(id)valueWithKnownClass:(Class)knownClass selector:(SEL)selector;
+(id)valueWithSelector:(SEL)selector;
-(void)setValue:(id)value onObject:(id)object;
@end

