/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol OFJsonParserDelegate
-(void)jsonParserDidStartObject:(id)jsonParser;
-(void)jsonParserDidEndObject:(id)jsonParser;
-(void)jsonParserDidStartArray:(id)jsonParser;
-(void)jsonParserDidEndArray:(id)jsonParser;
-(void)jsonParser:(id)parser didEncounterKey:(id)key;
-(void)jsonParser:(id)parser didEncounterValue:(id)value;
@end

