/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class OFHighScore, NSString;

@interface OFLeaderboard : OFResource <OFCallbackable> {
	NSString* name;
	OFHighScore* currentUserScore;
	OFHighScore* comparedUserScore;
	BOOL descendingScoreOrder;
	int filter;
}
@property(readonly, assign, nonatomic) int filter;
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) OFHighScore* currentUserScore;
@property(readonly, assign, nonatomic) BOOL descendingScoreOrder;
@property(readonly, assign, nonatomic) NSString* leaderboardId;
+(void)setDelegate:(id)delegate;
+(id)leaderboards;
+(id)leaderboard:(id)leaderboard;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)submitScore:(id)score;
-(id)highScoreForCurrentUser;
-(id)locallySubmittedScores;
-(id)downloadHighScoresWithFilter:(int)filter;
-(id)initWithLocalSQL:(OFSqlQuery*)localSQL localUserScore:(id)score comparedUserScore:(id)score3;
-(bool)isComparison;
-(id)comparedToUser;
-(void)_downloadedHighScores:(id)scores;
-(void)_failedDownloadingHighScores;
-(void)setName:(id)name;
-(void)setDescendingScoreOrder:(id)order;
-(void)setCurrentUsersScore:(id)score;
-(void)setComparedToUsersScore:(id)usersScore;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

