/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class OFLeaderboard, OFHighScore;

@interface OFLeaderboardPost : XXUnknownSuperclass <OFCallbackable> {
	OFHighScore* score_;
	OFLeaderboard* leaderboard_;
}
-(id)init;
-(void)post:(id)post toLeaderboard:(id)leaderboard;
-(void)postScore;
-(void)didFailGetServerTime;
-(void)didGetServerTime:(id)time;
-(bool)canReceiveCallbacksNow;
-(void)onScoreSubmissionComplete:(id)complete;
-(void)dealloc;
@end

