/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UILabel, UIImageView;

@interface OFLeaderboardCell : OFTableCellHelper {
	UIImageView* leaderboardIcon;
	UILabel* titleLabel;
}
-(void)awakeFromNib;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

