/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFLeaderboardDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class OFRequestHandle, NSMutableArray;

@interface OFLeaderboardRequest : XXUnknownSuperclass <OFLeaderboardDelegate> {
	NSMutableArray* resultSet_;
	id userInfo_;
	id delegate_;
	id target_;
	OFRequestHandle* handle_;
}
@property(readonly, assign, nonatomic) NSMutableArray* resultSet;
@property(assign, nonatomic) id delegate;
@property(retain, nonatomic) id target;
@property(retain, nonatomic) id userInfo;
@property(retain, nonatomic) OFRequestHandle* handle;
-(id)init;
-(void)dealloc;
-(void)writeResultSet:(id)set OFLeaderboard:(id)leaderboard;
-(void)didDownloadHighScores:(id)scores OFLeaderboard:(id)leaderboard;
-(void)didFailDownloadHighScoresOFLeaderboard:(id)leaderboard;
@end

