/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol OFLeaderboardDelegate
@optional
-(void)didDownloadHighScores:(id)scores OFLeaderboard:(id)leaderboard;
-(void)didFailDownloadHighScoresOFLeaderboard:(id)leaderboard;
@end

