/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "DoodleJump-Structs.h"

@class OFTextButton, OFFriendImporter, UISwitch, UILabel;

@interface OFLinkSocialNetworksController : OFViewController {
	OFFriendImporter* mImporter;
	UILabel* mAppNameLabel;
	OFTextButton* mBtnConnectTwitter;
	OFTextButton* mBtnConnectFacebook;
	UISwitch* mShareLocationSwitch;
	UISwitch* mShareOnlineStatusSwitch;
	BOOL mShareLocationOriginalState;
	BOOL mShareOnlineStatusOriginalState;
	OFDelegate mOnCompletionDelegate;
}
@property(retain, nonatomic) OFTextButton* mBtnConnectTwitter;
@property(retain, nonatomic) OFTextButton* mBtnConnectFacebook;
@property(retain, nonatomic) UISwitch* mShareLocationSwitch;
@property(retain, nonatomic) UISwitch* mShareOnlineStatusSwitch;
@property(assign, nonatomic) BOOL mShareLocationOriginalState;
@property(assign, nonatomic) BOOL mShareOnlineStatusOriginalState;
+(BOOL)hasSessionSeenLinkSocialNetworksScreen;
+(void)invalidateSessionSeenLinkSocialNetworksScreen;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)onImportFromTwitter;
-(void)onImportFromFacebook;
-(void)onSkip;
-(void)setCompleteDelegate:(OFDelegate*)delegate;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

