/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"
#import "CLLocationManagerDelegate.h"

@class CLLocationManager, CLLocation;

@interface OFLocation : XXUnknownSuperclass <CLLocationManagerDelegate, OFCallbackable> {
	CLLocationManager* locationManager;
	CLLocation* userLocation;
	BOOL userAllowed;
	BOOL locationUpdating;
}
@property(retain, nonatomic) CLLocationManager* locationManager;
@property(retain, nonatomic) CLLocation* userLocation;
-(id)init;
-(void)dealloc;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)locationManager:(id)manager didFailWithError:(id)error;
-(BOOL)isLocationUpdating;
-(void)stopUpdatingLocation;
-(id)getUserLocation;
-(void)updateUserLocation;
-(bool)canReceiveCallbacksNow;
-(void)_onSetLocationFailed:(id)failed;
@end

