/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UITextField;

@interface OFMultilineTextField : XXUnknownSuperclass {
	UITextField* backgroundTextField;
}
-(void)dealloc;
-(void)awakeFromNib;
-(void)setContentOffset:(CGPoint)offset;
-(void)setContentInset:(UIEdgeInsets)inset;
@end

