/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFDeadEndErrorController.h"


@interface OFMustBeOnlineErrorController : OFDeadEndErrorController <OFCallbackable> {
	OFPointer<OFReachabilityObserver> mReachabilityObserver;
}
-(void)_onReachabilityStatusChanged:(id)changed;
-(void)viewWillAppear:(BOOL)view;
-(bool)canReceiveCallbacksNow;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

