/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "OFBannerProvider.h"
#import "DoodleJump-Structs.h"

@class OFBadgeView, UIView, UILabel;

@interface OFMyFeintController : OFViewController <OFBannerProvider> {
	OFBadgeView* friendsBadge;
	OFBadgeView* inboxBadge;
	UILabel* friendsPlayingThisGame;
	UIView* inboxContainer;
	UIView* settingsContainer;
	UIView* helpContainer;
	CGRect originalSettingsFrame;
	CGRect originalHelpFrame;
}
-(void)_pendingFriendsChanged:(id)changed;
-(void)_inboxCountChanged:(id)changed;
-(void)awakeFromNib;
-(void)dealloc;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)onMyFriends;
-(void)onMyGames;
-(void)onMessageCenter;
-(void)onSettings;
-(void)onHelp;
-(bool)isBannerAvailableNow;
-(id)bannerCellControllerName;
-(id)getBannerResource;
-(void)onBannerClicked;
@end

