/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "OFViewController.h"
#import "OFCallbackable.h"

@class UISwitch, UILabel;

@interface OFNewsLetterController : OFViewController <OFCallbackable, UIActionSheetDelegate> {
	UILabel* summaryLabel;
	UILabel* descriptionLabel;
	UISwitch* subscriptionSwitch;
	BOOL securingAccount;
}
@property(retain, nonatomic) UILabel* summaryLabel;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain, nonatomic) UISwitch* subscriptionSwitch;
-(void)dealloc;
-(id)getClientApplicationId;
-(void)setSubscriptionState:(BOOL)state;
-(void)subscriptionChanged;
-(void)onSubscriptionChanged:(id)changed;
-(void)onSubscriptionFailedToChange;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)viewWillAppear:(BOOL)view;
-(void)doServerAction;
-(void)viewDidAppear:(BOOL)view;
-(void)onRetrievedSetting:(id)setting;
-(void)onFailedRetrievingSetting;
-(void)viewDidLoad;
-(bool)canReceiveCallbacksNow;
@end

