/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class OFUser;

@interface OFNewsletterSubscription : OFResource {
	OFUser* user;
	OFUser* developer;
}
@property(readonly, retain, nonatomic) OFUser* user;
@property(readonly, retain, nonatomic) OFUser* developer;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setUser:(id)user;
-(void)setDeveloper:(id)developer;
-(void)dealloc;
@end

