/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFFormControllerHelper.h"
#import "OFCallbackable.h"

@class OFImageView, UIView, UIButton, UITextField, NSString, UILabel, OFDefaultButton;

@interface OFNewAccountController : OFFormControllerHelper <OFCallbackable> {
	BOOL hasBeenDismissed;
	NSString* desiredName;
	UIView* loadingView;
	UIView* contentView;
	UIView* feintLogoLargeView;
	UILabel* appNameLabel;
	UITextField* nameEntryField;
	OFImageView* profileImageView;
	OFDefaultButton* acceptNameButton;
	UIButton* useDefaultNameButton;
	UIButton* alreadyHaveAccountButton;
	OFDelegate mOnCompletionDelegate;
	OFDelegate mOnCancelDelegate;
	BOOL hideNavigationBar;
	BOOL allowNavigatingBack;
	BOOL closeDashboardOnCompletion;
	BOOL areIntroFlowViewsHidden;
}
@property(retain, nonatomic) UIView* contentView;
@property(retain, nonatomic) UIView* feintLogoLargeView;
@property(retain, nonatomic) UILabel* appNameLabel;
@property(retain, nonatomic) UITextField* nameEntryField;
@property(retain, nonatomic) OFImageView* profileImageView;
@property(retain, nonatomic) OFDefaultButton* acceptNameButton;
@property(retain, nonatomic) UIButton* useDefaultNameButton;
@property(retain, nonatomic) UIButton* alreadyHaveAccountButton;
@property(assign, nonatomic) BOOL hideNavigationBar;
@property(assign, nonatomic) BOOL allowNavigatingBack;
@property(assign, nonatomic) BOOL closeDashboardOnCompletion;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidLoad;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
-(void)popBackToMe;
-(void)continueFlow;
-(void)cancelled;
-(void)dismiss;
-(void)_showNameLoadingView;
-(void)showNameLoadingView:(id)view;
-(void)hideNameLoadingView;
-(void)onSubmitForm:(id)form;
-(void)_useDefaultName;
-(void)_alreadyCreatedAccount;
-(void)registerActionsNow;
-(id)getFormSubmissionUrl;
-(void)onFormSubmitted:(id)submitted;
-(id)singularResourceName;
-(id)getHTTPMethod;
-(void)onPresentingErrorDialog;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(bool)shouldShowLoadingScreenWhileSubmitting;
-(bool)shouldDismissKeyboardWhenSubmitting;
-(void)setCompleteDelegate:(OFDelegate*)delegate;
-(void)setCancelDelegate:(OFDelegate*)delegate;
-(void)hideContentFrame;
-(void)hideIntroFlowViews;
-(void)_KeyboardDidShow:(id)_Keyboard;
-(void)_KeyboardDidHide:(id)_Keyboard;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

