/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CFNetwork/_kCFStreamPropertySSLSettings.h>
#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"

@class OFImageView, UIView, UILabel;

__attribute__((visibility("hidden")))
@interface OFNotificationView : _kCFStreamPropertySSLSettings <OFCallbackable> {
	UILabel* notice;
	OFImageView* statusIndicator;
	OFImageView* backgroundImage;
	OFImageView* notificationImage;
	BOOL mParentViewIsRotatedInternally;
	BOOL mPresenting;
	float mNotificationDuration;
	UIView* presentationView;
	UIView* viewToMove;
}
@property(retain, nonatomic) UILabel* notice;
@property(retain, nonatomic) OFImageView* statusIndicator;
@property(retain, nonatomic) OFImageView* backgroundImage;
@property(retain, nonatomic) OFImageView* notificationImage;
@property(retain, nonatomic) UIView* viewToMove;
+(id)notificationViewName;
+(void)showNotificationWithText:(id)text andImageNamed:(id)named andStatus:(id)status inView:(id)view;
+(void)showNotificationWithRequest:(id)request andNotice:(id)notice inView:(id)view;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)_animateKeypath:(id)keypath fromValue:(float)value toValue:(float)value3 overTime:(float)time animationDelegate:(id)delegate removeOnCompletion:(BOOL)completion fillMode:(id)mode;
-(void)_animateFromPosition:(CGPoint)position toPosition:(CGPoint)position2 overTime:(float)time animationDelegate:(id)delegate removeOnCompletion:(BOOL)completion fillMode:(id)mode;
-(void)_dismiss;
-(void)_presentForDuration:(float)duration;
-(void)_makeStatusIconActiveAndDismiss:(id)dismiss;
-(void)_requestSucceeded:(id)succeeded nextCall:(id)call;
-(void)_requestFailed:(id)failed nextCall:(id)call;
-(BOOL)isParentViewRotatedInternally:(id)internally;
-(CGPoint)_calcOffScreenPosition:(CGPoint)position;
-(void)_calcFrameAndTransform;
-(id)_getBackgroundImageName;
-(void)_setPresentationView:(id)view;
-(void)_buildViewWithText:(id)text;
-(void)setupDefaultImages;
-(void)configureWithText:(id)text andImageNamed:(id)named andStatus:(id)status inView:(id)view;
-(void)configureWithRequest:(id)request andNotice:(id)notice inView:(id)view;
-(bool)canReceiveCallbacksNow;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)dealloc;
@end

