/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface OFNotificationData : XXUnknownSuperclass {
	NSString* notificationText;
	NSString* imageName;
	int notificationCategory;
	int notificationType;
	id notificationUserData;
}
@property(retain, nonatomic) NSString* notificationText;
@property(assign, nonatomic) int notificationCategory;
@property(assign, nonatomic) int notificationType;
@property(retain, nonatomic) id notificationUserData;
@property(retain, nonatomic) NSString* imageName;
+(id)foreGroundDataWithText:(id)text;
+(id)dataWithText:(id)text andCategory:(int)category;
+(id)dataWithText:(id)text andCategory:(int)category andType:(int)type;
-(void)dealloc;
@end

