/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFService.h"


@interface OFOfflineService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)shareKnownResources:(OFResourceNameMap*)resources;
+(void)setupOfflineSupport;
+(void)migrateOfflineData;
+(void)syncOfflineData:(id)data bootStrap:(id)strap;
+(void)getBootstrapCallParams:(OFHttpNestedQueryStringWriter*)params userId:(id)anId;
+(int)getTableVersion:(id)version;
+(bool)setTableVersion:(id)version version:(int)version2;
+(id)getFormattedAppVersion;
-(id)init;
-(void)dealloc;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
-(void)sendPendingData:(id)data;
@end

