/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSMutableArray;

@interface OFOffline : OFResource {
	NSMutableArray* achievements;
	NSMutableArray* leaderboards;
	NSMutableArray* leaderboardAggregations;
}
@property(readonly, retain, nonatomic) NSMutableArray* achievements;
@property(readonly, retain, nonatomic) NSMutableArray* leaderboards;
@property(readonly, retain, nonatomic) NSMutableArray* leaderboardAggregations;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
-(void)setLeaderboards:(id)leaderboards;
-(void)setAchievements:(id)achievements;
-(void)setLeaderboardAggregations:(id)aggregations;
-(void)dealloc;
@end

