/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFOnlineStatus, UILabel;

@interface OFOnlineStatusCell : OFTableCellHelper {
	OFOnlineStatus* status;
	UILabel* textLabel;
}
@property(retain) OFOnlineStatus* status;
@property(retain) UILabel* textLabel;
-(void)dealloc;
-(void)onResourceChanged:(id)changed;
@end

