/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIImage, OFContentFrameView;

@interface OFPatternedGradientView : XXUnknownSuperclass {
	CGGradientRef mGradient;
	UIImage* mPattern;
	CGPoint mDirection;
	OFContentFrameView* contentFrameView;
}
@property(readonly, assign, nonatomic) UIImage* patternImage;
+(CGGradientRef)createDefaultGradient;
+(CGGradientRef)createLightGradient;
+(id)defaultView:(CGRect)view;
+(id)introView;
-(id)initWithFrame:(CGRect)frame gradient:(CGGradientRef)gradient patternImage:(id)image;
-(void)dealloc;
-(void)setGradientAngle:(float)angle;
-(void)drawRect:(CGRect)rect;
@end

