/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSFastEnumeration.h"

@class OFPaginatedSeriesHeader, NSMutableArray;

@interface OFPaginatedSeries : XXUnknownSuperclass <NSFastEnumeration> {
	NSMutableArray* tableMetaDataObjects;
	NSMutableArray* objects;
	OFPaginatedSeriesHeader* header;
	int httpResponseStatusCode;
}
@property(retain, nonatomic) NSMutableArray* objects;
@property(retain, nonatomic) NSMutableArray* tableMetaDataObjects;
@property(retain, nonatomic) OFPaginatedSeriesHeader* header;
@property(assign, nonatomic) int httpResponseStatusCode;
+(id)paginatedSeries;
+(id)paginatedSeriesWithObject:(id)object;
+(id)paginatedSeriesFromSeries:(id)series;
+(id)paginatedSeriesFromArray:(id)array;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)init;
-(void)prependObject:(id)object;
-(void)addObject:(id)object;
-(void)dealloc;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)index;
@end

