/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFViewController.h"
#import "OFTableControllerHeader.h"

@class UIImageView, UILabel;

@interface OFPlainTableHeaderController : OFViewController <OFTableControllerHeader> {
	UILabel* headerLabel;
	UIImageView* bgView;
}
@property(retain, nonatomic) UILabel* headerLabel;
-(void)awakeFromNib;
-(void)resizeView:(id)view;
-(void)dealloc;
@end

