/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class OFUser, NSString;

@interface OFPlayerReview : OFResource {
	OFUser* user;
	BOOL favorite;
	NSString* review;
}
@property(readonly, retain, nonatomic) OFUser* user;
@property(readonly, assign, nonatomic) BOOL favorite;
@property(readonly, assign, nonatomic) NSString* review;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setUser:(id)user;
-(void)setfavorite:(id)setfavorite;
-(void)setReview:(id)review;
-(void)dealloc;
@end

