/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UILabel;

@interface OFPlainMessageTrailingCell : OFTableCellHelper {
	UILabel* messageLabel;
}
@property(retain, nonatomic) UILabel* messageLabel;
-(void)dealloc;
@end

