/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UIViewController, OFImageView, UIImageView, NSString, UIView, UIButton, UILabel;

@interface OFPlayedGameCell : OFTableCellHelper {
	UILabel* nameLabel;
	UILabel* friendsWithAppLabel;
	OFImageView* iconView;
	UIView* firstStatView;
	UIView* secondStatView;
	UILabel* firstGamerScoreLabel;
	UILabel* secondGamerScoreLabel;
	UIButton* shoppingCartButton;
	UIViewController* owner;
	NSString* clientApplicationId;
	UIImageView* firstGamerScoreIcon;
	UIImageView* secondGamerScoreIcon;
	UIImageView* firstFavoritedIcon;
	UIImageView* secondFavoritedIcon;
	UIImageView* comparisonDividerIcon;
	OFImageView* miniScreenshotOneView;
	OFImageView* miniScreenshotTwoView;
}
@property(retain, nonatomic) OFImageView* iconView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UILabel* friendsWithAppLabel;
@property(retain, nonatomic) UIView* secondStatView;
@property(retain, nonatomic) UIView* firstStatView;
@property(retain, nonatomic) UILabel* firstGamerScoreLabel;
@property(retain, nonatomic) UILabel* secondGamerScoreLabel;
@property(retain, nonatomic) UIButton* shoppingCartButton;
@property(assign, nonatomic) UIViewController* owner;
@property(retain, nonatomic) UIImageView* firstGamerScoreIcon;
@property(retain, nonatomic) UIImageView* secondGamerScoreIcon;
@property(retain, nonatomic) OFImageView* miniScreenshotOneView;
@property(retain, nonatomic) OFImageView* miniScreenshotTwoView;
@property(retain, nonatomic) UIImageView* firstFavoritedIcon;
@property(retain, nonatomic) UIImageView* secondFavoritedIcon;
@property(retain, nonatomic) UIImageView* comparisonDividerIcon;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)showIPurchasePage;
-(void)showAppStorePage;
-(void)dealloc;
@end

