/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UITextViewDelegate.h"
#import "OFFormControllerHelper.h"

@class OFForumThread, OFForumTopic, UIView, UITextField, UITextView;

@interface OFPostNewMessage : OFFormControllerHelper <UITextViewDelegate> {
	UIView* subjectView;
	UIView* bodyView;
	UITextField* subjectField;
	UITextView* bodyField;
	OFForumTopic* topic;
	OFForumThread* thread;
}
@property(retain) OFForumTopic* topic;
@property(retain) OFForumThread* thread;
+(id)postNewMessageInTopic:(id)topic;
+(id)postNewMessageInThread:(id)thread topic:(id)topic;
-(void)dealloc;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(bool)canReceiveCallbacksNow;
-(void)onSubmitForm:(id)form;
-(void)registerActionsNow;
-(id)getFormSubmissionUrl;
-(void)onFormSubmitted:(id)submitted;
-(id)singularResourceName;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(void)toggleSubjectView:(BOOL)view;
@end

