/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"
#import "DoodleJump-Structs.h"

@class NSMutableDictionary, NSObject, NSString, NSTimer;
@protocol OFProviderProtocol;

@interface OFPoller : XXUnknownSuperclass <OFCallbackable> {
	NSObject<OFProviderProtocol>* mProvider;
	OFResourceNameMap mRegisteredResources;
	NSMutableDictionary* mChronologicalResourceTypes;
	NSTimer* mHeartbeat;
	bool mInPoll;
	bool mQueuedPoll;
	NSString* mSourceUrl;
}
-(id)initWithProvider:(id)provider sourceUrl:(id)url;
-(void)dealloc;
-(Class)getRegisteredResourceClassWithName:(id)name;
-(void)resetToDefaultPollingFrequency;
-(void)changePollingFrequency:(double)frequency;
-(void)stopPolling;
-(void)registerResourceClass:(Class)aClass;
-(void)clearCacheForResourceClass:(Class)resourceClass;
-(void)clearCacheAndForceLastSeenId:(long long)anId forResourceClass:(Class)resourceClass;
-(void)_onPollComplete;
-(void)_onSucceededDownloading:(id)downloading;
-(void)_onFailedDownloading;
-(void)pollNow;
-(double)getPollingFrequency;
-(bool)canReceiveCallbacksNow;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

