/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"


@protocol OFProviderProtocol
-(bool)isAuthenticated;
-(void)performAction:(id)action withParameters:(id)parameters withHttpMethod:(id)httpMethod withSuccess:(const OFDelegate*)success withFailure:(const OFDelegate*)failure withRequestType:(int)requestType withNotice:(id)notice;
@end

