/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFPresenceQueue : OFResource {
	NSString* name;
}
@property(readonly, retain, nonatomic) NSString* name;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
-(void)setName:(id)name;
-(void)dealloc;
@end

