/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, OFUser, OFImageView;

@interface OFProfileComparisonUser : XXUnknownSuperclass {
	OFUser* user;
	UILabel* score;
	OFImageView* avatar;
}
@property(retain, nonatomic) OFUser* user;
-(void)awakeFromNib;
-(void)dealloc;
@end

