/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFProfileService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)getLocalPlayerProfileOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getProfileForUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)getGamerscoreForUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)viewedOwnProfilePage;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

