/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFPushNotificationService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)setDeviceToken:(id)token onSuccess:(OFDelegate)success onFailure:(OFDelegate)failure;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

