/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableArray;

@interface OFRequestHandlesForModule : XXUnknownSuperclass {
	id module;
	NSMutableArray* handles;
}
@property(retain, nonatomic) NSObject* module;
@property(retain, nonatomic) NSMutableArray* handles;
+(void)addHandle:(id)handle forModule:(id)module;
+(void)cancelAllRequestsForModule:(id)module;
+(void)completeRequest:(id)request;
-(void)dealloc;
@end

