/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFBadgeView.h"
#import "DoodleJump-Structs.h"


@interface OFRedBadgeView : OFBadgeView {
}
-(id)initWithCoder:(id)coder;
@end

