/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UIActionSheetDelegate.h"
#import "OFFormControllerHelper.h"
#import "OFCallbackable.h"

@class NSString, UILabel, OFDefaultButton;

@interface OFRemoveCredentialController : OFFormControllerHelper <OFCallbackable, UIActionSheetDelegate> {
	UILabel* warningText;
	UILabel* warningTextTwo;
	UILabel* headerTitle;
	OFDefaultButton* submitButton;
	NSString* credentialType;
	NSString* credentialSpokenName;
	OFDelegate submittedDelegate;
}
@property(retain, nonatomic) UILabel* warningText;
@property(retain, nonatomic) UILabel* warningTextTwo;
@property(retain, nonatomic) UILabel* headerTitle;
@property(retain, nonatomic) NSString* credentialType;
@property(retain, nonatomic) NSString* credentialSpokenName;
@property(retain, nonatomic) OFDefaultButton* submitButton;
-(void)dealloc;
-(bool)canReceiveCallbacksNow;
-(id)getFormSubmissionUrl;
-(void)registerActionsNow;
-(id)singularResourceName;
-(id)getHTTPMethod;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(void)onFormSubmitted:(id)submitted;
-(void)onSubmitPressed;
-(void)viewWillAppear:(BOOL)view;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)_logoutFacebookSession;
-(void)setupForFacebook;
-(void)setupForTwitter;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

