/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFProfileFrame.h"
#import "DoodleJump-Structs.h"
#import "OFFormControllerHelper.h"

@class OFDefaultButton;

@interface OFResetPasswordController : OFFormControllerHelper <OFProfileFrame> {
	OFDefaultButton* resetButton;
}
@property(retain, nonatomic) OFDefaultButton* resetButton;
-(void)viewWillAppear:(BOOL)view;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(void)registerActionsNow;
-(void)onFormSubmitted:(id)submitted;
-(id)singularResourceName;
-(id)getFormSubmissionUrl;
-(id)getHTTPMethod;
-(void)dealloc;
@end

