/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OFRequestHandle : XXUnknownSuperclass {
	id request;
	Class requestKlass;
}
@property(assign, nonatomic) id request;
+(id)requestHandle:(id)handle;
-(id)initWithRequest:(id)request;
-(void)dealloc;
-(void)cancel;
@end

