/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFXPResponseJSON.h"
#import "OFXPResponseText.h"
#import "OFXPRequest.h"


@interface OFResourceRequest : OFXPRequest <OFXPResponseJSON, OFXPResponseText> {
	id target;
	SEL selector;
	id resources;
	unsigned httpResponseCode;
}
@property(retain, nonatomic) id resources;
@property(assign, nonatomic) unsigned httpResponseCode;
-(void)execute;
-(void)onResponseText:(id)text withResponseCode:(unsigned)responseCode;
-(void)onResponseJSON:(id)json withResponseCode:(unsigned)responseCode;
-(id)onRespondTarget:(id)target selector:(SEL)selector;
@end

