/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, NSString, UIImageView, UIView;

@interface OFRootController : XXUnknownSuperclass {
	UIView* containerView;
	UIView* bgOverlay;
	UIImageView* bgDropShadow;
	UIViewController* contentController;
	UIViewController* nonFullscreenModalController;
	NSString* transitionIn;
	NSString* transitionOut;
	BOOL keyboardShowing;
}
@property(retain, nonatomic) UIView* containerView;
@property(retain, nonatomic) UIView* bgOverlay;
@property(retain, nonatomic) UIImageView* bgDropShadow;
@property(readonly, assign, nonatomic) UIViewController* contentController;
@property(retain, nonatomic) UIViewController* nonFullscreenModalController;
@property(retain, nonatomic) NSString* transitionIn;
@property(retain, nonatomic) NSString* transitionOut;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)_adjustController:(id)controller toCompensateForKeyboard:(BOOL)keyboard;
-(void)_adjustForKeyboard:(int)keyboard;
-(void)_keyboardWillShow:(id)_keyboard;
-(void)_keyboardWillHide:(id)_keyboard;
-(void)_dashboardWillRotate:(id)_dashboard;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)showController:(id)controller;
-(void)hideController;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)presentNonFullScreenModalViewController:(id)controller animated:(BOOL)animated;
-(void)dismissNonFullScreenModalViewControllerAnimated:(BOOL)animated;
-(void)presentModalViewController:(id)controller animated:(BOOL)animated;
-(void)dismissModalViewControllerAnimated:(BOOL)animated;
-(id)modalViewController;
-(void)cleanupSubviews;
-(void)dealloc;
@end

