/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIImage, UIColor;

@interface OFRoundedRectView : XXUnknownSuperclass {
	UIImage* mRoundedRect;
	UIColor* mBackgroundColor;
}
-(void)_commonInit;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setBackgroundColor:(id)color;
-(void)drawRect:(CGRect)rect;
@end

