/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OFRunLoopThread : XXUnknownSuperclass {
	id runLoopHolder;
}
+(id)runLoop;
-(id)initWithHolder:(id)holder;
-(void)terminateRunLoop;
@end

