/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSObject;

@interface OFS3Response : XXUnknownSuperclass {
	NSData* data;
	NSObject* userParam;
	int statusCode;
}
@property(retain, nonatomic) NSData* data;
@property(retain, nonatomic) NSObject* userParam;
@property(assign, nonatomic) int statusCode;
-(id)initWithData:(id)data andUserParam:(id)param andStatusCode:(int)code;
-(void)dealloc;
@end

