/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class NSString;

@interface OFS3UploadParameters : OFResource {
	NSString* action;
	NSString* key;
	NSString* AWSAccessKeyId;
	NSString* acl;
	NSString* policy;
	NSString* signature;
}
@property(readonly, assign, nonatomic) NSString* action;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
+(id)getMultiPartBoundary;
-(void)setKey:(id)key;
-(void)setAction:(id)action;
-(void)setAWSAccessKeyId:(id)anId;
-(void)setAcl:(id)acl;
-(void)setPolicy:(id)policy;
-(void)setSignature:(id)signature;
-(id)getBoundaryMarkerStart;
-(id)getBoundaryMarkerEnd;
-(void)dealloc;
-(id)getHeaderSpacer;
-(void)addParamToData:(id)data boundary:(id)boundary paramName:(id)name paramValue:(id)value;
-(id)createS3HttpBodyForBlob:(id)blob;
@end

