/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"

@class OFRequestHandle, NSString, NSArray;

@interface OFScoreEnumerator : XXUnknownSuperclass <OFCallbackable> {
	BOOL isCurrentUserPage;
	int pageSize;
	int currentPage;
	int totalPages;
	NSArray* scores;
	int filter;
	NSString* leaderboardId;
	OFRequestHandle* activeRequest;
}
@property(readonly, assign, nonatomic) int pageSize;
@property(readonly, assign, nonatomic) int currentPage;
@property(readonly, assign, nonatomic) int totalPages;
@property(readonly, assign, nonatomic) NSArray* scores;
@property(readonly, assign, nonatomic) BOOL isCurrentUserPage;
@property(retain, nonatomic) NSString* leaderboardId;
@property(retain, nonatomic) OFRequestHandle* activeRequest;
@property(readonly, assign, nonatomic) BOOL hasScores;
+(void)setDelegate:(id)delegate;
+(id)scoreEnumeratorForLeaderboard:(id)leaderboard pageSize:(int)size filter:(int)filter;
-(id)initWithLeaderboardId:(id)leaderboardId pageSize:(int)size filter:(int)filter;
-(void)dealloc;
-(void)setCurrentPage:(int)page;
-(void)setPageSize:(int)size;
-(BOOL)nextPage;
-(BOOL)previousPage;
-(void)pageWithCurrentUser;
-(void)jumpToPage:(int)page;
-(void)_downloadFinished:(id)finished;
-(void)_downloadFailed;
-(bool)canReceiveCallbacksNow;
@end

