/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"

@class OFSelectInviteTypeController, NSMutableArray;

@interface OFSelectContactsToInviteController : OFTableSequenceControllerHelper {
	OFSelectInviteTypeController* inviteTypeController;
	NSMutableArray* selectedContacts;
	NSMutableArray* addedContacts;
}
@property(retain, nonatomic) OFSelectInviteTypeController* inviteTypeController;
@property(retain, nonatomic) NSMutableArray* selectedContacts;
@property(retain, nonatomic) NSMutableArray* addedContacts;
+(id)inviteController:(id)controller withAlreadyAddedContacts:(id)alreadyAddedContacts withAlreadySelectedContacts:(id)alreadySelectedContacts;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundMessage;
-(bool)shouldDisplayEmptyDataSet;
-(id)getDataNotLoadedYetMessage;
-(id)getTableHeaderControllerName;
-(bool)usePlainTableSectionHeaders;
-(void)onTableHeaderCreated:(id)created;
-(void)onSectionsCreated:(id)created;
-(void)onCell:(id)cell resourceChanged:(id)changed;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)done;
-(void)addPersonWithId:(int)anId andName:(id)name andImageData:(id)data andEmail:(id)email;
-(void)addPersonWithId:(int)anId andName:(id)name andImageData:(id)data andPhoneNumber:(id)number;
-(BOOL)shouldAlwaysShowNavBar;
-(void)dealloc;
@end

