/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"
#import "OFProfileFrame.h"


@interface OFSelectChatRoomDefinitionController : OFTableSequenceControllerHelper <OFProfileFrame> {
	BOOL includeGlobalRooms;
	BOOL includeApplicationRooms;
	BOOL includeDeveloperRooms;
}
@property(assign) BOOL includeGlobalRooms;
@property(assign) BOOL includeApplicationRooms;
@property(assign) BOOL includeDeveloperRooms;
-(bool)usePlainTableSectionHeaders;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(BOOL)hideLoadingScreenIfInHiddenTab;
-(void)onFailedLoadingInstances;
-(void)attemptToJoinRoom:(id)joinRoom;
-(void)onLoadedInstances:(id)instances;
-(void)onClickedButton;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)onJoinedRoom;
-(void)onFailedToJoinRoom;
-(id)getTableHeaderControllerName;
-(id)getNoDataFoundMessage;
-(void)onTableHeaderCreated:(id)created;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
@end

