/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFTableControllerHeader.h"

@class OFImageView, UIImageView, UILabel;

@interface OFSelectInviteTypeHeaderController : XXUnknownSuperclass <OFTableControllerHeader> {
	UILabel* enticeLabel;
	OFImageView* inviteIcon;
	UIImageView* inviteIconFrame;
}
@property(readonly, assign, nonatomic) UILabel* enticeLabel;
@property(readonly, assign, nonatomic) OFImageView* inviteIcon;
@property(readonly, assign, nonatomic) UIImageView* inviteIconFrame;
-(void)awakeFromNib;
-(void)resizeView:(id)view;
@end

