/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UIImageView, UIView, UILabel;

@interface OFSendSocialNotificationCell : OFTableCellHelper {
	UIView* connetedView;
	UIView* notConnetedView;
	UILabel* connectToNeworkLabel;
	UIImageView* connectToNetworkImageView;
	UILabel* postToNetworkLabel;
	UIImageView* connectedNetworkIconView;
	UIImageView* sendToNetworkCheckBoxView;
	BOOL connectedToNetwork;
	BOOL checked;
	int networkType;
	UIImageView* connectToNetworkImage;
	UIImageView* connectedNetworkIcon;
}
@property(retain, nonatomic) UIView* connetedView;
@property(retain, nonatomic) UIView* notConnetedView;
@property(retain, nonatomic) UILabel* connectToNeworkLabel;
@property(retain, nonatomic) UIImageView* connectToNetworkImage;
@property(retain, nonatomic) UILabel* postToNetworkLabel;
@property(retain, nonatomic) UIImageView* connectedNetworkIcon;
@property(retain, nonatomic) UIImageView* sendToNetworkCheckBoxView;
@property(assign, nonatomic) BOOL connectedToNetwork;
@property(assign, nonatomic) BOOL checked;
@property(assign, nonatomic) int networkType;
-(void)_refreshViews;
-(void)onResourceChanged:(id)changed;
@end

