/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFTableSequenceControllerHelper.h"

@class NSString, NSData, NSMutableArray, OFChallengeToUser;

@interface OFSendChallengeController : OFTableSequenceControllerHelper <OFCallbackable> {
	NSString* challengeDefinitionId;
	NSString* challengeText;
	NSString* hiddenText;
	NSData* challengeData;
	NSData* resultData;
	NSMutableArray* mSelectedUsers;
	OFChallengeToUser* userChallenge;
	bool isCompleted;
	bool rechallenge;
	bool stallNextRefresh;
}
@property(retain, nonatomic) NSString* challengeDefinitionId;
@property(retain, nonatomic) NSString* challengeText;
@property(retain, nonatomic) NSData* challengeData;
@property(retain, nonatomic) NSData* resultData;
@property(retain, nonatomic) NSString* hiddenText;
@property(assign, nonatomic) bool isCompleted;
@property(retain, nonatomic) OFChallengeToUser* userChallenge;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundViewController;
-(id)getNoDataFoundMessage;
-(bool)usePlainTableSectionHeaders;
-(id)getTableHeaderControllerName;
-(void)onTableHeaderCreated:(id)created;
-(void)onSectionsCreated:(id)created;
-(void)toggleSelectionOfUser:(id)user;
-(void)onCell:(id)cell resourceChanged:(id)changed;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)showNoFriendsSelectedMessage;
-(void)showNoConnectionMessage;
-(void)showSubmitFailedMessage;
-(id)getUserMessage:(id)message;
-(void)submitChallenge;
-(void)submitChallengeBack;
-(void)tryChallengeAgain;
-(void)cancel;
-(void)challengeSubmittedSuccess;
-(void)challengeSubmittedFailure;
-(bool)canReceiveCallbacksNow;
-(BOOL)shouldAlwaysShowNavBar;
-(void)_refreshData;
-(void)_refreshDataNow;
-(void)dealloc;
@end

