/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableControllerHelper.h"
#import "DoodleJump-Structs.h"

@class OFSocialNotification, OFSendSocialNotificationCell, OFSendSocialNotificationSubmitTextCell, UIViewController;
@protocol OFExtendedCredentialController;

@interface OFSendSocialNotificationController : OFTableControllerHelper {
	OFSendSocialNotificationCell* sendSocialNotificationCell[2];
	BOOL initChecked[2];
	OFSendSocialNotificationSubmitTextCell* submitTextCell;
	OFSocialNotification* notification;
	int onlyCheckNetwork;
	BOOL needCredentialsForNetwork[2];
	int currentGettingCredentialForNetwork;
	UIViewController<OFExtendedCredentialController>* currentExtendedCredentialsController;
}
@property(retain, nonatomic) OFSendSocialNotificationSubmitTextCell* submitTextCell;
@property(retain, nonatomic) OFSocialNotification* notification;
@property(retain, nonatomic) UIViewController<OFExtendedCredentialController>* currentExtendedCredentialsController;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)send;
-(void)activateSendButton;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)createCell:(id)cell withType:(int)type andConnectToNetworkText:(id)networkText andPostToNetworkText:(id)networkText4 andConnectToNetworkImageName:(id)networkImageName andConnectedToNeworkIconName:(id)neworkIconName andConnectedToNetwork:(BOOL)network;
-(void)_onDataLoaded:(id)loaded isIncremental:(BOOL)incremental;
-(void)configureCell:(id)cell asLeading:(BOOL)leading asTrailing:(BOOL)trailing asOdd:(BOOL)odd;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)setPrepopulatedText:(id)text andOriginalMessage:(id)message;
-(void)setImageUrl:(id)url defaultImage:(id)image;
-(void)setImageName:(id)name linkedUrl:(id)url;
-(void)setImageType:(id)type imageId:(id)anId linkedUrl:(id)url;
-(void)setDismissDashboardWhenSent:(BOOL)sent;
-(void)setUseNetwork:(int)network;
-(void)dismiss;
-(BOOL)_extendedCredentialsRequiredFor:(const char*)aFor withDocument:(id)document;
-(void)_sendSuccess;
-(void)_sendFailure:(id)failure;
-(BOOL)_getNextCredential;
-(void)_extendedCredentialsSuccess;
-(void)_extendedCredentialsFailure;
-(void)_extendedCredentialsCancel;
-(void)_clearNeedingExtendedCredentials;
-(void)_launchFacebookLoginFlow;
-(void)_launchTwitterLoginFlow;
-(void)dealloc;
@end

