/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"

@class NSInvocation, OFUser, OFDevice, NSString, NSMutableArray, NSMutableSet;

@interface OFSession : XXUnknownSuperclass <OFCallbackable> {
	NSMutableSet* priorityObservers;
	NSMutableSet* observers;
	NSString* key;
	NSString* secret;
	NSInvocation* postDeviceInvocation;
	NSMutableArray* queuedRequests;
	OFUser* currentUser;
	OFDevice* currentDevice;
	struct {
		BOOL sessionChangeInProgress;
		BOOL createdDeviceSession;
		BOOL createdUserSession;
	} stateFlags;
}
@property(retain, nonatomic) NSMutableSet* priorityObservers;
@property(retain, nonatomic) NSMutableSet* observers;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) NSString* secret;
@property(retain, nonatomic) NSInvocation* postDeviceInvocation;
@property(retain, nonatomic) NSMutableArray* queuedRequests;
@property(retain, nonatomic) OFUser* currentUser;
@property(retain, nonatomic) OFDevice* currentDevice;
+(id)protocolVersion;
-(id)initWithProductKey:(id)productKey secret:(id)secret;
-(void)dealloc;
-(void)addObserver:(id)observer;
-(void)addPriorityObserver:(id)observer;
-(void)removeObserver:(id)observer;
-(void)failWithException:(id)exception;
-(void)performRequest:(id)request;
-(void)processQueuedRequests;
-(void)establishDeviceSession;
-(void)deviceSessionResponse:(id)response;
-(BOOL)sessionChangeAllowed;
-(void)loginNewUser;
-(void)loginUserId:(id)anId password:(id)password;
-(void)establishUserSessionForId:(id)anId password:(id)password;
-(void)userSessionResponse:(id)response;
-(void)logoutUser;
-(void)logoutResponse:(id)response;
-(void)bootstrapSuccess:(id)success;
-(void)bootstrapFailure:(id)failure;
-(bool)canReceiveCallbacksNow;
@end

