/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "OFCallbackable.h"
#import "OFTableControllerHeader.h"

@class OFSendChallengeController, OFImageView, UIView, OFDefaultTextField, UIButton, UILabel;

@interface OFSendChallengeHeaderController : XXUnknownSuperclass <OFTableControllerHeader, OFCallbackable> {
	BOOL finishedDownloadingChallenge;
	OFSendChallengeController* sendChallengeController;
	UILabel* titleLabel;
	UILabel* descriptionLabel;
	UIButton* sendChallengeButton;
	UIButton* tryAgainButton;
	OFImageView* challengeIconImageView;
	UIView* descriptionContainer;
	OFDefaultTextField* userMessageTextField;
	OFRetainedPtr<NSObject> selfRetainer;
	OFRetainedPtr<NSObject> parentRetainer;
}
@property(assign, nonatomic) OFSendChallengeController* sendChallengeController;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain, nonatomic) UIButton* sendChallengeButton;
@property(retain, nonatomic) OFImageView* challengeIconImageView;
@property(retain, nonatomic) UIView* descriptionContainer;
@property(retain, nonatomic) OFDefaultTextField* userMessageTextField;
@property(retain, nonatomic) UIButton* tryAgainButton;
-(void)awakeFromNib;
-(void)dealloc;
-(BOOL)allowCreateStrongerChallenge;
-(void)viewDidLoad;
-(void)_challengeDefinitionDownloadFailed;
-(void)_newChallengeDefinitionDownloaded:(id)downloaded;
-(void)setChallenge:(id)challenge;
-(bool)canReceiveCallbacksNow;
-(void)cancel;
-(void)createStrongerChallenge;
-(void)resizeView:(id)view;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

