/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UILabel, OFImageView;

@interface OFSelectAchievementToShareLeadingCell : OFTableCellHelper {
	UILabel* label;
	OFImageView* gameIcon;
}
@property(retain, nonatomic) UILabel* label;
@property(retain, nonatomic) OFImageView* gameIcon;
-(void)onResourceChanged:(id)changed;
@end

