/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableStaticControllerHelper.h"

@class NSString, NSArray, OFInviteDefinition, OFSelectInviteTypeCell, NSMutableArray, OFSelectInviteTypeHeaderController;

@interface OFSelectInviteTypeController : OFTableStaticControllerHelper {
	NSString* inviteId;
	OFSelectInviteTypeHeaderController* mHeader;
	OFInviteDefinition* mDefinition;
	NSMutableArray* selected[2];
	OFSelectInviteTypeCell* cells[2];
	NSArray* addedContacts;
}
@property(retain, nonatomic) NSString* inviteId;
@property(retain, nonatomic) NSArray* addedContacts;
+(id)inviteTypeControllerWithInviteIdentifier:(id)inviteIdentifier;
-(void)viewWillAppear:(BOOL)view;
-(void)openAsModal;
-(void)openAsModalInDashboard;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(void)createCell:(id)cell withType:(int)type withTitle:(id)title andIconName:(id)name andCreateSelector:(SEL)selector;
-(id)buildTableSectionDescriptions;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)inviteOpenFeintFriends;
-(void)inviteContacts;
-(void)advance;
-(id)getTableHeaderControllerName;
-(void)onTableHeaderCreated:(id)created;
-(void)updateSelectedType:(int)type with:(id)with;
-(id)getSelectedListForType:(int)type;
-(void)updateCell:(id)cell withSelectedCount:(unsigned)selectedCount;
-(void)didGetInviteDefinition:(id)definition;
-(void)didFailGetInviteDefinition;
-(void)dealloc;
@end

