/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "UITextFieldDelegate.h"
#import "OFTableCellHelper.h"

@class UITextField, OFSendSocialNotificationController, OFImageView, UILabel;

@interface OFSendSocialNotificationSubmitTextCell : OFTableCellHelper <UITextFieldDelegate, OFCallbackable> {
	OFImageView* gameIcon;
	UILabel* prePopulatedText;
	UITextField* message;
	unsigned maxMessageCharacters;
	OFSendSocialNotificationController* sendSocialNotificationController;
}
@property(retain, nonatomic) OFImageView* gameIcon;
@property(retain, nonatomic) UILabel* prePopulatedText;
@property(retain, nonatomic) UITextField* message;
@property(assign, nonatomic) unsigned maxMessageCharacters;
@property(retain, nonatomic) OFSendSocialNotificationController* sendSocialNotificationController;
-(void)awakeFromNib;
-(void)setIconUrl:(id)url;
-(void)setDefaultImageName:(id)name;
-(void)setSocialNotificationImageName:(id)name;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)_getSocialNotificationImageSuccess:(id)success;
-(void)_getSocialNotificationImageFailure;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

