/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "OFProfileFrame.h"
#import "OFTableSequenceControllerHelper.h"

@class UIPopoverController, OFUsersCredential, UIBarButtonItem;

@interface OFSelectProfilePictureController : OFTableSequenceControllerHelper <OFProfileFrame, UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate> {
	int refreshCount;
	UIBarButtonItem* refreshButton;
	OFUsersCredential* facebookCredentialWaitingForUpdate;
	OFUsersCredential* twitterCredentialWaitingForUpdate;
	OFUsersCredential* httpBasicCredentialWaitingForUpdate;
	BOOL redownloadOnNextAppear;
	BOOL refreshOnNextRedownload;
	UIPopoverController* imagePickerPopoverController;
}
@property(retain, nonatomic) UIPopoverController* imagePickerPopoverController;
-(void)dealloc;
-(void)orientationDidChange:(id)orientation;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(id)getNoDataFoundMessage;
-(id)getTableHeaderViewName;
-(void)onTableHeaderCreated:(id)created;
-(void)onBeforeResourcesProcessed:(id)processed;
-(void)_redownloadCredentials;
-(void)_refreshFailure;
-(void)_refreshSuccess:(id)success;
-(void)_refreshProfilePictures:(unsigned)pictures;
-(void)_clickedRefresh;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(void)_selectSourceSuccessWithIgnored:(id)ignored andCredential:(id)credential;
-(void)_uploadSuccessWithIgnored:(id)ignored;
-(void)_selectSourceFailure;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)_presentCustomImageActionSheet;
-(void)_showImagePicker:(id)picker usingPopover:(BOOL)popover;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_imageSelected:(id)selected;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)imagePickerController:(id)controller didFinishPickingImage:(id)image editingInfo:(id)info;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
@end

