/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFNotificationView.h"

@class OFImageView, UIImageView, UILabel;

@interface OFServerNotificationView : OFNotificationView {
	OFImageView* icon;
	UILabel* twoLineTopLabel;
	UILabel* twoLineBottomLabel;
	UILabel* numberLabel;
	UIImageView* smallFeintIconForNumber;
	BOOL settingUpView;
	int miDownloadsNeeded;
	int miDownloadsDone;
}
@property(retain, nonatomic) OFImageView* icon;
@property(retain, nonatomic) UILabel* twoLineTopLabel;
@property(retain, nonatomic) UILabel* twoLineBottomLabel;
@property(retain, nonatomic) UILabel* numberLabel;
@property(retain, nonatomic) UIImageView* smallFeintIconForNumber;
+(id)notificationViewName;
+(void)showServerNotification:(id)notification inView:(id)view;
-(void)configureServerNotification:(id)notification inView:(id)view;
-(void)_loadImagesWithNotification:(id)notification;
-(void)_updateText:(id)text;
-(void)_updateNumber:(id)number;
-(void)_setImageViewImage:(id)image withBackupDefaultImage:(id)backupDefaultImage withDefaultImageName:(id)defaultImageName andDesiredImage:(id)image4;
-(void)_imageFinishedDownloading;
@end

