/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UILabel, UIImageView;

@interface OFSelectInviteTypeCell : OFTableCellHelper {
	UIImageView* iconView;
	UILabel* titleLabel;
	UILabel* amountSelectedLabel;
	SEL createControllerSelector;
}
@property(retain, nonatomic) UIImageView* iconView;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UILabel* amountSelectedLabel;
@property(assign, nonatomic) SEL createControllerSelector;
-(void)dealloc;
@end

