/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"

@class NSArray;

@interface OFSelectChatRoomInstanceController : OFTableSequenceControllerHelper {
	NSArray* preLoadedChatRoomInstances;
}
@property(retain, nonatomic) NSArray* preLoadedChatRoomInstances;
+(void)pushChatRoom:(id)room navController:(id)controller;
+(void)pushRoomFullScreen:(id)screen;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)onJoinedRoom;
-(void)onFailedToJoinRoom;
-(id)getTableHeaderControllerName;
-(id)getNoDataFoundMessage;
-(void)dealloc;
@end

