/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFTableSequenceControllerHelper.h"

@class OFSelectInviteTypeController, NSMutableArray;

@interface OFSelectFriendsToInviteController : OFTableSequenceControllerHelper <OFCallbackable> {
	NSMutableArray* selectedUsers;
	OFSelectInviteTypeController* inviteTypeController;
	BOOL stallNextRefresh;
	BOOL friendsDownloadOutstanding;
	BOOL anyFriendsDownloadOutstanding;
	BOOL followingAnyone;
}
@property(retain, nonatomic) OFSelectInviteTypeController* inviteTypeController;
@property(retain, nonatomic) NSMutableArray* selectedUsers;
+(id)inviteController:(id)controller withAlreadySelectedUsers:(id)alreadySelectedUsers;
-(void)hideLoadingScreen;
-(void)_onDataLoadedWrapper:(id)wrapper isIncremental:(BOOL)incremental;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(bool)autoLoadData;
-(id)getNoDataFoundViewController;
-(id)getNoDataFoundMessage;
-(id)getDataNotLoadedYetMessage;
-(void)localUserFollowingAnyoneFail;
-(void)localUserFollowingAnyone:(id)anyone;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(bool)usePlainTableSectionHeaders;
-(void)onSectionsCreated:(id)created;
-(void)toggleSelectionOfUser:(id)user;
-(void)onCell:(id)cell resourceChanged:(id)changed;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getUserMessage:(id)message;
-(void)cancel;
-(void)done;
-(void)viewWillDisappear:(BOOL)view;
-(bool)canReceiveCallbacksNow;
-(BOOL)shouldAlwaysShowNavBar;
-(void)_refreshData;
-(void)_refreshDataNow;
-(unsigned)_userIsAtSelectedIndex:(id)selectedIndex;
-(void)dealloc;
@end

