/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString;

@interface OFSocialNotification : XXUnknownSuperclass {
	NSString* text;
	NSString* imageType;
	NSString* imageIdentifier;
	NSString* imageUrl;
	NSString* url;
	NSMutableArray* sendToNetworks;
}
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSString* imageType;
@property(retain, nonatomic) NSString* imageIdentifier;
@property(retain, nonatomic) NSString* imageUrl;
@property(retain, nonatomic) NSString* url;
@property(retain, nonatomic) NSMutableArray* sendToNetworks;
-(id)initWithText:(id)text imageType:(id)type imageIdentifier:(id)identifier linkedUrl:(id)url;
-(id)initWithText:(id)text imageNamed:(id)named linkedUrl:(id)url;
-(id)initWithText:(id)text imageNamed:(id)named;
-(id)initWithText:(id)text;
-(id)initWithText:(id)text imageType:(id)type imageId:(id)anId;
-(id)initWithText:(id)text imageType:(id)type imageId:(id)anId linkedUrl:(id)url;
-(void)addSendToNetwork:(int)network;
-(void)clearSendToNetworks;
-(void)dealloc;
@end

