/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OFSocialNotificationApi : XXUnknownSuperclass {
}
+(void)setDelegate:(id)delegate;
+(void)setCustomUrl:(id)url;
+(void)sendWithPrepopulatedText:(id)prepopulatedText originalMessage:(id)message imageNamed:(id)named;
+(void)sendSuccess;
+(void)sendFailure;
-(bool)canReceiveCallbacksNow;
@end

