/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFSubmitAchievementToGameCenterOnly : XXUnknownSuperclass {
	unsigned achievementStillToRecieveCallbackCount;
	BOOL encounteredAnError;
	BOOL sentFailure;
}
-(void)submitToGameCenterOnlyWithIds:(id)ids andPercentCompletes:(id)completes onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
@end

