/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol OFTabBarDelegate <NSObject>
@optional
-(void)tabBar:(id)bar didSelectViewController:(id)controller;
-(id)tabBar:(id)bar loadViewController:(id)controller forTab:(id)tab;
-(void)tabBar:(id)bar didLoadViewController:(id)controller fromTab:(id)tab;
-(void)tabBar:(id)bar willUnloadViewController:(id)controller fromTab:(id)tab;
-(void)tabBar:(id)bar didSelectTabItem:(id)item;
-(void)tabBar:(id)bar didSelectTabNamed:(id)named;
-(void)tabBar:(id)bar didSelectTabAtIndex:(int)index;
-(void)tabBar:(id)bar didDisableTabItem:(id)item;
-(void)tabBar:(id)bar didDisableTabNamed:(id)named;
-(void)tabBar:(id)bar didDisableTabAtIndex:(int)index;
@end

