/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, OFTabBar, NSString, UIImageView, UIImage, OFBadgeView, UIView, UILabel, UIButton;

@interface OFTabBarItem : XXUnknownSuperclass {
	OFTabBar* parent;
	UIButton* button;
	UIImageView* imageView;
	UILabel* nameLabel;
	OFBadgeView* badgeView;
	UIImageView* borderImageView;
	UIImageView* backgroundView;
	UIImageView* hitImageView;
	UIView* overlayView;
	BOOL active;
	BOOL disabled;
	NSString* viewControllerName;
	NSString* openFeintDisabledViewControllerName;
	UIViewController* viewController;
	NSString* name;
	UIImage* activeImage;
	UIImage* inactiveImage;
	UIImage* disabledImage;
	NSString* badgeSelector;
}
@property(retain, nonatomic) UIButton* button;
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) OFBadgeView* badgeView;
@property(retain, nonatomic) UIImageView* borderImageView;
@property(retain, nonatomic) UIImageView* backgroundView;
@property(retain, nonatomic) UIImageView* hitImageView;
@property(assign, nonatomic) BOOL active;
@property(retain, nonatomic) UIViewController* viewController;
@property(retain, nonatomic) NSString* viewControllerName;
@property(retain, nonatomic) NSString* openFeintDisabledViewControllerName;
@property(copy, nonatomic) NSString* name;
@property(retain, nonatomic) UIImage* activeImage;
@property(retain, nonatomic) UIImage* inactiveImage;
@property(assign, nonatomic) BOOL disabled;
@property(retain, nonatomic) UIImage* disabledImage;
@property(retain, nonatomic) NSString* badgeSelector;
-(id)initWithParent:(id)parent viewController:(id)controller named:(id)named activeImage:(id)image inactiveImage:(id)image5 disabledImage:(id)image6;
-(void)didTapTabItem;
-(void)didHit;
-(void)didCancelHit;
-(void)_removeDisabledOverlay;
-(void)_addDisabledOverlay;
-(void)layoutSubviews;
-(void)animatePulse;
-(void)setBadgeValue:(id)value;
-(void)refreshBadge;
-(void)setOnlineStatus:(BOOL)status;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void*)context;
-(void)dealloc;
@end

