/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFTableControllerHeader.h"
#import "OFTabBarDelegate.h"

@class NSMutableDictionary, OFTabBar;

@interface OFTabbedPageHeaderController : XXUnknownSuperclass <OFTabBarDelegate, OFTableControllerHeader> {
	NSMutableDictionary* mTabCallbacks;
	OFTabBar* tabBar;
	id callbackTarget;
}
@property(readonly, assign, nonatomic) OFTabBar* tabBar;
@property(assign, nonatomic) id callbackTarget;
-(void)addTab:(id)tab andSelectedCallback:(SEL)callback;
-(void)showTab:(id)tab;
-(void)setBadgeValue:(int)value forTabNamed:(id)tabNamed;
-(void)resizeView:(id)view;
-(void)tabBar:(id)bar didSelectTabNamed:(id)named;
-(void)dealloc;
@end

