/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UIImageView, OFPaginatedSeriesHeader;

@interface OFTableSequenceControllerLoadMoreCell : OFTableCellHelper {
	OFPaginatedSeriesHeader* lastLoadedPageHeader;
	UIImageView* backgroundImageView;
}
@property(assign, nonatomic) bool isLoading;
@property(retain, nonatomic) OFPaginatedSeriesHeader* lastLoadedPageHeader;
-(void)awakeFromNib;
-(void)dealloc;
-(void)onResourceChanged:(id)changed;
@end

