/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIColor, OFTabBarItem, UIImage, NSMutableArray, UIViewController;
@protocol OFTabBarDelegate;

@interface OFTabBar : XXUnknownSuperclass {
	UIImageView* backgroundImageView;
	NSMutableArray* items;
	OFTabBarItem* selectedTab;
	id<OFTabBarDelegate> delegate;
	int style;
	UIColor* inactiveTextColor;
	UIColor* inactiveShadowColor;
	UIColor* activeTextColor;
	UIColor* activeShadowColor;
	UIColor* disabledTextColor;
	UIColor* disabledShadowColor;
	CGPoint badgeOffset;
	BOOL placeBadgeTopRight;
	UIImage* dividerImage;
	UIImage* activeItemBackgroundImage;
	UIImage* inactiveItemBackgroundImage;
	UIImage* disabledItemBackgroundImage;
	UIImage* hitOverlayImage;
	UIImage* disabledOverlayIconImage;
	float leftPadding;
	float rightPadding;
	float overlap;
	CGRect labelPadding;
	BOOL pulse;
	int textAlignment;
	BOOL changeZOrderOnTap;
}
@property(readonly, assign, nonatomic) NSMutableArray* items;
@property(assign, nonatomic) int style;
@property(retain, nonatomic) UIColor* activeTextColor;
@property(retain, nonatomic) UIColor* activeShadowColor;
@property(retain, nonatomic) UIColor* inactiveTextColor;
@property(retain, nonatomic) UIColor* inactiveShadowColor;
@property(assign, nonatomic) CGPoint badgeOffset;
@property(assign, nonatomic) BOOL placeBadgeTopRight;
@property(retain, nonatomic) UIImage* dividerImage;
@property(retain, nonatomic) UIImage* activeItemBackgroundImage;
@property(retain, nonatomic) UIImage* inactiveItemBackgroundImage;
@property(retain, nonatomic) UIImage* hitOverlayImage;
@property(retain, nonatomic) UIColor* disabledTextColor;
@property(retain, nonatomic) UIColor* disabledShadowColor;
@property(retain, nonatomic) UIImage* disabledItemBackgroundImage;
@property(retain, nonatomic) UIImage* disabledOverlayIconImage;
@property(assign, nonatomic) float leftPadding;
@property(assign, nonatomic) float rightPadding;
@property(assign, nonatomic) float overlap;
@property(assign, nonatomic) CGRect labelPadding;
@property(assign, nonatomic) BOOL pulse;
@property(assign, nonatomic) int textAlignment;
@property(assign, nonatomic) id<OFTabBarDelegate> delegate;
@property(readonly, assign, nonatomic) OFTabBarItem* selectedTab;
@property(assign, nonatomic) BOOL changeZOrderOnTap;
@property(readonly, assign, nonatomic) UIViewController* selectedViewController;
-(void)_commonInit;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)layoutSubviews;
-(void)setBackgroundImage:(id)image;
-(id)backgroundImage;
-(void)addViewController:(id)controller named:(id)named activeImage:(id)image inactiveImage:(id)image4 disabledImage:(id)image5;
-(void)addViewController:(id)controller ofDisabledViewController:(id)disabledViewController named:(id)named activeImage:(id)image inactiveImage:(id)image5 disabledImage:(id)image6;
-(void)addSegmentNamed:(id)named activeImage:(id)image inactiveImage:(id)image3 disabledImage:(id)image4;
-(void)showTab:(id)tab;
-(void)showTab:(id)tab showAtRoot:(BOOL)root;
-(void)showTab:(id)tab notifyDelegate:(BOOL)delegate;
-(void)showTab:(id)tab showAtRoot:(BOOL)root notifyDelegate:(BOOL)delegate;
-(void)showTabAtIndex:(int)index showAtRoot:(BOOL)root;
-(void)showTabAtIndex:(int)index;
-(void)showTabAtIndex:(int)index notifyDelegate:(BOOL)delegate;
-(void)showTabAtIndex:(int)index showAtRoot:(BOOL)root notifyDelegate:(BOOL)delegate;
-(void)showTabNamed:(id)named;
-(void)showTabNamed:(id)named showAtRoot:(BOOL)root;
-(void)showTabNamed:(id)named notifyDelegate:(BOOL)delegate;
-(void)showTabNamed:(id)named showAtRoot:(BOOL)root notifyDelegate:(BOOL)delegate;
-(void)showTabViewControllerNamed:(id)named;
-(void)showTabViewControllerNamed:(id)named showAtRoot:(BOOL)root;
-(void)showTabViewControllerNamed:(id)named notifyDelegate:(BOOL)delegate;
-(void)showTabViewControllerNamed:(id)named showAtRoot:(BOOL)root notifyDelegate:(BOOL)delegate;
-(void)enableAllTabs;
-(void)disableTab:(id)tab notifyDelegate:(BOOL)delegate;
-(void)disableTabAtIndex:(int)index notifyDelegate:(BOOL)delegate;
-(void)disableTabViewControllerNamed:(id)named notifyDelegate:(BOOL)delegate;
-(void)disableTabViewControllerNamed:(id)named;
-(void)disableTabNamed:(id)named notifyDelegate:(BOOL)delegate;
-(void)disableTab:(id)tab;
-(void)disableTabAtIndex:(int)index;
-(void)disableTabNamed:(id)named;
-(void)disableInactiveTabs;
-(void)updateZOrder;
-(void)hideTabBar;
-(void)showTabBar;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void*)context;
-(void)setOnlineStatus:(BOOL)status;
-(void)setBadgeValue:(int)value forItemNamed:(id)itemNamed;
-(void)unloadTabBarItem:(id)item;
-(void)unloadTabBarItemNamed:(id)named;
-(void)unloadAllInactiveTabs;
-(void)forceUnloadAllTabs;
-(id)_loadTabItemViewController:(id)controller forTab:(id)tab;
-(void)dealloc;
@end

