/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTickerProxyRecipient.h"
#import "OFTickerViewDelegate.h"
#import "OFTabBarControllerDelegate.h"
#import "OFTabBarController.h"

@class UIView, NSString, OFTickerView, OFWebNavController, NSTimer;

@interface OFTabbedDashboardController : OFTabBarController <OFTabBarControllerDelegate, OFTickerViewDelegate, OFTickerProxyRecipient> {
	UIView* hostView;
	OFTickerView* tickerView;
	NSTimer* tickerTimer;
	OFWebNavController* mModalDashboardContentController;
	NSString* defaultTabName;
	NSString* offlineTabName;
}
@property(retain, nonatomic) UIView* hostView;
@property(retain, nonatomic) OFTickerView* tickerView;
@property(retain, nonatomic) OFWebNavController* mModalDashboardContentController;
@property(retain, nonatomic) NSString* defaultTabName;
@property(retain, nonatomic) NSString* offlineTabName;
+(void)_setOnlineMode:(id)mode;
+(void)_setOfflineMode:(id)mode;
+(void)setOnlineMode:(id)mode;
+(void)setOfflineMode:(id)mode;
-(void)tabBarController:(id)controller didLoadViewController:(id)controller2 fromTab:(id)tab;
-(void)newTickerMessage:(id)message;
-(void)textFinishedScrolling;
-(id)tabBar:(id)bar loadViewController:(id)controller forTab:(id)tab;
-(id)createTabBar;
-(id)imageProcessFromString:(id)string andSuffix:(id)suffix;
-(id)badgeValueProcess:(id)process;
-(void)_addAllViewControllers;
-(void)_presentModalContentController;
-(void)_addModalContentController;
-(void)_commonInit;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)view;
-(void)tabBarController:(id)controller didSelectViewController:(id)controller2;
-(id)defaultTab;
-(id)offlineTab;
-(void)onXPressed;
-(void)dealloc;
@end

