/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFFramedNavigationController.h"


@interface OFTabbedDashboardPageController : OFFramedNavigationController {
}
+(id)pageWithController:(id)controller;
+(id)pageWithInstantiatedController:(id)instantiatedController;
-(void)viewDidLoad;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)navigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)_orderViewDepths;
@end

