/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableStaticControllerHelper.h"
#import "DoodleJump-Structs.h"
#import "OFTableControllerHelper.h"


@interface OFTableStaticControllerHelper : OFTableControllerHelper {
}
-(id)getResourceFromSection:(id)section atRow:(unsigned)row;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
@end

@interface OFTableStaticControllerHelper (Overridables)
-(id)buildTableSectionDescriptions;
@end

