/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"


@interface OFTableCellHelperActionCell : OFTableCellHelper {
}
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)buttonPressed:(id)pressed;
-(void)dealloc;
@end

