/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIImage;

@interface OFTableCellBackgroundView : XXUnknownSuperclass {
	UIImage* mImage;
	int mEdgeStyle;
	BOOL mTileImage;
}
@property(retain, nonatomic) UIImage* image;
@property(assign, nonatomic) int edgeStyle;
@property(assign, nonatomic) BOOL tileImage;
+(id)defaultBackgroundView;
-(id)initWithFrame:(CGRect)frame andImageName:(id)name andRoundedEdge:(int)edge;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

