/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class OFResource, NSString;

@interface OFTableSectionCellDescription : XXUnknownSuperclass {
	OFResource* resource;
	NSString* controllerName;
}
@property(retain, nonatomic) OFResource* resource;
@property(retain, nonatomic) NSString* controllerName;
+(id)cellController:(id)controller andResource:(id)resource;
-(void)dealloc;
@end

