/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OFTableSectionDescription.h"

@class OFPaginatedSeries, NSString, NSMutableArray, UIView;

@interface OFTableSectionDescription : XXUnknownSuperclass {
	NSString* title;
	NSString* identifier;
	OFPaginatedSeries* page;
	NSString* leadingCellName;
	NSString* trailingCellName;
	UIView* headerView;
	UIView* footerView;
	NSMutableArray* staticCells;
	NSMutableArray* expandedViews;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* identifier;
@property(retain, nonatomic) OFPaginatedSeries* page;
@property(retain, nonatomic) NSString* leadingCellName;
@property(retain, nonatomic) NSString* trailingCellName;
@property(retain, nonatomic) UIView* headerView;
@property(retain, nonatomic) UIView* footerView;
@property(retain, nonatomic) NSMutableArray* staticCells;
@property(retain, nonatomic) NSMutableArray* expandedViews;
+(id)sectionWithTitle:(id)title andPage:(id)page;
+(id)sectionWithTitle:(id)title andCell:(id)cell;
+(id)sectionWithTitle:(id)title andStaticCells:(id)cells;
+(void)testRowGathering;
-(void)matchupExpandedViews;
-(id)initWithTitle:(id)title andPage:(id)page;
-(void)dealloc;
-(unsigned)_countWithAssumption:(unsigned)assumption;
-(unsigned)countEntireItemSet;
-(unsigned)countPageItems;
-(BOOL)isRowFirstObject:(unsigned)object;
-(BOOL)isRowLastObject:(unsigned)object;
-(void)gatherDataForRow:(unsigned)row dataRow:(unsigned*)row2 cellType:(unsigned*)type;
-(void)runTestLength:(unsigned)length;
@end

@interface OFTableSectionDescription (ResourceAdditions)
-(id)arrayWithoutDuplicates:(id)duplicates areSortedDescending:(BOOL)descending;
-(unsigned)addContentsOfSectionWhereUnique:(id)sectionWhereUnique areSortedDescending:(BOOL)descending shouldPrependContents:(BOOL)contents;
@end

