/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFTextView : XXUnknownSuperclass {
	float lineHeight;
}
@property(assign) float lineHeight;
-(void)setContentSize:(CGSize)size;
-(void)setContentInset:(UIEdgeInsets)inset;
@end

