/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;

@interface OFTimerHeartbeat : XXUnknownSuperclass {
	NSObject* mTarget;
	SEL mSelector;
}
+(id)scheduledTimerWithInterval:(double)interval target:(id)target selector:(SEL)selector;
-(id)initWithTarget:(id)target andSelector:(SEL)selector;
-(void)pulse;
@end

