/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"
#import "OFCallbackable.h"

@class NSDate;

@interface OFTimeStamp : OFResource <OFCallbackable> {
	NSDate* time;
	int secondsSinceEpoch;
}
@property(readonly, assign, nonatomic) NSDate* time;
@property(readonly, assign, nonatomic) int secondsSinceEpoch;
+(void)setDelegate:(id)delegate;
+(id)getServerTime;
+(void)_getServerTimeSuccess:(id)success;
+(void)_getServerTimeFailure;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(bool)canReceiveCallbacksNow;
-(void)setTime:(id)time;
-(void)setSecondsSinceEpoch:(id)epoch;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

