/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;
@protocol OFTickerProxyRecipient;

@interface OFTickerProxy : XXUnknownSuperclass <OFCallbackable> {
	NSMutableArray* tickerMessages;
	unsigned currMessageIndex;
	id<OFTickerProxyRecipient> recipient;
}
+(id)instance;
+(void)getNextMessage:(id)message;
+(void)neverMind:(id)mind;
+(void)queueNewMessage:(id)message;
-(void)_kickTicker;
-(void)getNextMessage:(id)message;
-(void)neverMind:(id)mind;
-(void)_tickerMessagesRecieved:(id)recieved;
-(void)queueNewMessage:(id)message;
-(bool)canReceiveCallbacksNow;
@end

