/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DoodleJump-Structs.h"

@class UIImage;

@interface OFToggleControl : XXUnknownSuperclass {
	UIImage* mImageLeftSelected;
	UIImage* mImageRightSelected;
	bool mIsLeftSelected;
}
@property(readonly, assign, nonatomic) bool isLeftSelected;
-(void)_commonInit;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)drawRect:(CGRect)rect;
-(void)setLeftSelected:(BOOL)selected;
-(void)setImageForLeftSelected:(id)leftSelected;
-(void)setImageForRightSelected:(id)rightSelected;
@end

