/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol OFTouchReceiverDelegate;

@interface OFTouchReceiverView : XXUnknownSuperclass {
	id<OFTouchReceiverDelegate> delegate;
}
@property(assign) id<OFTouchReceiverDelegate> delegate;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

