/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFAccountSetupBaseController.h"
#import "DoodleJump-Structs.h"

@class UIViewController, UIView, UIButton, UILabel;

@interface OFTwitterAccountLoginController : OFAccountSetupBaseController {
	UIButton* submitButton;
	UIView* contentView;
	UILabel* integrationInfoLabel;
	UIViewController* controllerToPopTo;
}
@property(retain, nonatomic) UIButton* submitButton;
@property(retain, nonatomic) UIView* contentView;
@property(retain, nonatomic) UILabel* integrationInfoLabel;
@property(retain, nonatomic) UIViewController* controllerToPopTo;
-(void)setupForConnectTwitter;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(bool)shouldUseOAuth;
-(void)populateViewDataMap:(OFViewDataMap*)map;
-(void)addHiddenParameters:(OFISerializer*)parameters;
-(void)registerActionsNow;
-(id)singularResourceName;
-(id)getFormSubmissionUrl;
-(id)getLoadingScreenText;
-(id)controllerToPushOnCompletion;
-(id)getControllerToPopTo;
-(void)dealloc;
@end

