/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFUIInvisibleKeyboardTrap : XXUnknownSuperclass {
}
-(void)didAddSubview:(id)subview;
-(void)willRemoveSubview:(id)subview;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

