/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFResource.h"
#import "DoodleJump-Structs.h"

@class OFAchievement;

@interface OFUnlockedAchievement : OFResource {
	OFAchievement* achievement;
	bool isInvalidResult;
	double percentComplete;
}
@property(readonly, assign, nonatomic) OFAchievement* achievement;
@property(readonly, assign, nonatomic) double percentComplete;
@property(readonly, assign, nonatomic) bool isInvalidResult;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setPercentComplete:(id)complete;
-(void)setResult:(id)result;
-(void)setAchievement:(id)achievement;
-(void)dealloc;
@end

