/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSString;

@interface OFUserGameStat : OFResource {
	BOOL userHasGame;
	NSString* userId;
	unsigned userGamerScore;
	BOOL userFavoritedGame;
}
@property(readonly, assign, nonatomic) BOOL userHasGame;
@property(readonly, retain, nonatomic) NSString* userId;
@property(readonly, assign, nonatomic) unsigned userGamerScore;
@property(readonly, assign, nonatomic) BOOL userFavoritedGame;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setUserHasGame:(id)game;
-(void)setUserId:(id)anId;
-(void)setUserGamerscore:(id)gamerscore;
-(void)setUserFavoritedGame:(id)game;
-(void)dealloc;
@end

