/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface OFUserData : XXUnknownSuperclass {
	NSString* userId;
	NSString* cachePath;
	BOOL isLoaded;
	NSMutableDictionary* userData_;
}
-(id)initWithUserId:(id)userId;
-(void)dealloc;
-(id)userId;
-(BOOL)isLoaded;
-(void)load;
-(void)createDefault:(id)aDefault forKey:(id)key;
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(void)removeAllObjects;
-(void)synchronize;
@end

