/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import "OFTableCellHelper.h"

@class OFTableSequenceControllerHelper;

@interface OFUserSettingActionCell : OFTableCellHelper <OFCallbackable> {
	OFTableSequenceControllerHelper* owner;
}
@property(readonly, assign, nonatomic) OFTableSequenceControllerHelper* owner;
-(void)onResourceChanged:(id)changed;
-(bool)canReceiveCallbacksNow;
-(void)dealloc;
@end

