/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSString;

@interface OFUserSetting : OFResource {
	NSString* name;
	NSString* value;
	NSString* valueType;
	NSString* key;
}
@property(readonly, retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* value;
@property(readonly, retain, nonatomic) NSString* valueType;
@property(readonly, retain, nonatomic) NSString* key;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
-(void)setName:(id)name;
-(void)setValueType:(id)type;
-(void)setKey:(id)key;
-(void)dealloc;
@end

