/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableCellHelper.h"

@class OFTableSequenceControllerHelper;

@interface OFUsersCredentialCell : OFTableCellHelper {
	OFTableSequenceControllerHelper* owner;
}
@property(readonly, assign, nonatomic) OFTableSequenceControllerHelper* owner;
+(OFKnownCredential*)getKnownCredential:(id)credential;
+(id)getCredentialImage:(id)image;
+(id)getCredentialControllerName:(id)name;
+(id)getCredentialCellText:(id)text;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

