/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFUserService.h"
#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFUserService : OFService {
}
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(id)getUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)findUsersByName:(id)name pageIndex:(int)index onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)findUsersForLocalDeviceOnSuccess:(const OFDelegate*)localDeviceOnSuccess onFailure:(const OFDelegate*)failure;
+(void)getEmailForUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(void)setUserLocation:(id)location location:(id)location2 allowed:(BOOL)allowed onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

@interface OFUserService (Private)
+(void)setupOfflineSupport:(bool)support;
+(bool)createLocalUser:(id)user userName:(id)name profilePictureUrl:(id)url;
+(void)getLocalUser:(id)user onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
+(id)getLocalUser:(id)user;
-(id)init;
-(void)dealloc;
@end

