/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFCallbackable.h"
#import "OFTableCellHelper.h"

@class OFTableSequenceControllerHelper, UISwitch, UILabel;

@interface OFUserSettingCell : OFTableCellHelper <OFCallbackable> {
	UILabel* name;
	UISwitch* booleanSwitch;
	OFTableSequenceControllerHelper* owner;
}
@property(readonly, assign, nonatomic) UILabel* name;
@property(readonly, assign, nonatomic) UISwitch* booleanSwitch;
@property(readonly, assign, nonatomic) OFTableSequenceControllerHelper* owner;
-(void)dealloc;
-(void)setControlToSettingValue:(id)settingValue;
-(void)setSettingToControlValue:(id)controlValue;
-(void)onResourceChanged:(id)changed;
-(void)switchToggled;
-(void)onSubmitFailure;
-(void)onSubmitSuccess;
-(bool)canReceiveCallbacksNow;
@end

