/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFResource.h"

@class NSString;

@interface OFUsersCredential : OFResource {
	NSString* credentialType;
	NSString* credentialProfilePictureUrl;
	NSString* profilePictureUpdatedAt;
	BOOL hasGlobalPermissions;
	BOOL isLinked;
}
@property(readonly, retain, nonatomic) NSString* credentialType;
@property(readonly, retain, nonatomic) NSString* credentialProfilePictureUrl;
@property(readonly, retain, nonatomic) NSString* profilePictureUpdatedAt;
@property(readonly, assign) BOOL hasGlobalPermissions;
@property(readonly, assign) BOOL isLinked;
+(id)getService;
+(OFResourceDataMap*)getDataMap;
+(id)getResourceName;
+(id)getResourceDiscoveredNotification;
+(id)getDisplayNameForCredentialType:(id)credentialType;
-(void)setCredentialType:(id)type;
-(void)setCredentialProfilePictureUrl:(id)url;
-(void)setProfilePictureUpdatedAt:(id)at;
-(void)setHasGlobalPermissions:(id)permissions;
-(void)setIsLinked:(id)linked;
-(BOOL)isFacebook;
-(BOOL)isTwitter;
-(BOOL)isHttpBasic;
-(void)dealloc;
@end

