/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class OFImageView, UIImageView, OFUserRelationshipIndicator, UILabel;

@interface OFUserCell : OFTableCellHelper {
	OFImageView* profilePictureView;
	UILabel* nameLabel;
	UILabel* lastPlayedGameLabel;
	UILabel* gamerScoreLabel;
	OFUserRelationshipIndicator* relationshipIndicator;
	UIImageView* feintScoreIconImageView;
	UILabel* relationshipDescription;
	UIImageView* presenceIcon;
	UILabel* onlineLabel;
}
@property(retain, nonatomic) OFImageView* profilePictureView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UILabel* lastPlayedGameLabel;
@property(retain, nonatomic) UILabel* gamerScoreLabel;
@property(retain, nonatomic) OFUserRelationshipIndicator* relationshipIndicator;
@property(retain, nonatomic) UIImageView* feintScoreIconImageView;
@property(retain, nonatomic) UILabel* relationshipDescription;
@property(retain, nonatomic) UIImageView* presenceIcon;
@property(retain, nonatomic) UILabel* onlineLabel;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)dealloc;
@end

