/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFWebViewController.h"

@class NSString;

@interface OFViewInviteController : OFWebViewController {
	NSString* resourceId;
}
@property(retain, nonatomic) NSString* resourceId;
+(id)viewInviteControllerWithInviteId:(id)inviteId;
-(id)getAction;
-(BOOL)_webActionIgnoreInvite:(id)invite;
-(id)getDispatchDictionary;
-(id)getTitle;
-(void)dealloc;
@end

