/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFWebNavController.h"
#import "DoodleJump-Structs.h"


@interface OFWebNavIntroFlowController : OFWebNavController {
	OFDelegate approvedDelegate;
	OFDelegate deniedDelegate;
	BOOL createdNewAccount;
}
+(id)controller;
-(id)initWithTitle:(id)title htmlPath:(id)path useContentFrame:(BOOL)frame;
-(void)viewDidAppear:(BOOL)view;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(void)setNavbarVisibility;
-(void)setApprovedDelegate:(const OFDelegate*)delegate andDeniedDelegate:(const OFDelegate*)delegate2;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)serverDidTimeout;
-(void)showOfflinePage:(id)page;
-(OFFramedNavigationControllerVisibilityFlags)_visibilityFlagsForController:(id)controller;
-(void)bootstrapSuccess;
-(void)bootstrapFailed;
-(void)actionApprove:(id)approve;
-(void)actionNavigateToURLWithUDID:(id)udid;
-(void)actionDismissNavController;
-(void)actionBootstrap:(id)bootstrap;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

