/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFService.h"
#import "DoodleJump-Structs.h"


@interface OFWebViewManifestService : OFService {
}
+(void)_start;
+(id)sharedInstance;
+(void)initializeService;
+(void)shutdownService;
+(void)updateToManifest;
+(BOOL)isPathLoaded:(id)loaded;
+(BOOL)isPathValid:(id)valid;
+(BOOL)trackPath:(id)path forMe:(id)me;
+(void)prioritizePath:(id)path;
+(id)rootPath;
+(void)enableLoad;
+(void)disableLoad;
+(void)setManifestApplication:(id)application;
+(void)resetCache;
+(void)startOver;
+(id)sha1Errors;
-(id)init;
-(void)dealloc;
-(void)populateKnownResources:(OFResourceNameMap*)resources;
@end

