/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFFramedNavigationController.h"
#import "DoodleJump-Structs.h"
#import "OFCallbackable.h"
#import "OFWebViewManifestDelegate.h"
#import "UIWebViewDelegate.h"

@class UIImageView, UIWebView, NSURL, NSMutableDictionary;

@interface OFWebNavController : OFFramedNavigationController <UIWebViewDelegate, OFCallbackable, OFWebViewManifestDelegate> {
	NSURL* url;
	NSMutableDictionary* actionMap;
	BOOL dismissOnPopToRoot;
	BOOL useContentFrame;
	UIWebView* webView;
	UIImageView* transitionImage;
}
@property(copy, nonatomic) NSURL* url;
@property(retain, nonatomic) NSMutableDictionary* actionMap;
@property(assign, nonatomic) BOOL dismissOnPopToRoot;
@property(retain, nonatomic) UIWebView* webView;
@property(retain, nonatomic) UIImageView* transitionImage;
+(id)controllerWithTitle:(id)title htmlPath:(id)path useContentFrame:(BOOL)frame;
-(id)initWithTitle:(id)title htmlPath:(id)path useContentFrame:(BOOL)frame;
-(void)dealloc;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)webViewCacheItemReady:(id)ready;
-(void)_fixNavBar;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadInitialRequest;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(unsigned)type;
-(void)webViewDidFinishLoad:(id)webView;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;
-(OFFramedNavigationControllerVisibilityFlags)_visibilityFlagsForController:(id)controller;
-(id)optionsForAction:(id)action;
-(void)mapAction:(id)action toSelector:(SEL)selector;
-(void)performAction:(id)action;
-(void)didTapBarButton;
-(void)pushURLString:(id)string;
-(void)pushControllerURL:(id)url;
-(void)pushControllerName:(id)name options:(id)options;
-(bool)canReceiveCallbacksNow;
-(void)actionNavPop;
-(void)actionStartLoading:(id)loading;
-(void)actionDomLoaded:(id)loaded;
-(void)actionAlert:(id)alert;
-(void)actionAddBarButton:(id)button;
-(void)actionDismissNavController;
-(void)actionLog:(id)log;
@end

