/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, OFWebViewManifestData, NSObject, NSString, OFRunLoopThread, NSLock, NSMutableSet;
@protocol OFWebViewManifestDelegate;

@interface OFWebViewCacheLoader : XXUnknownSuperclass {
	NSString* manifestApplication;
	NSObject<OFWebViewManifestDelegate>* delegate;
	NSString* rootPath;
	NSMutableDictionary* localManifest;
	OFWebViewManifestData* serverManifest;
	NSMutableSet* pathsToLoad;
	NSMutableDictionary* tracked;
	NSMutableSet* globals;
	NSMutableSet* priority;
	BOOL defaultCopied;
	BOOL abortedByReset;
	NSMutableDictionary* observers;
	NSLock* trackingLock;
	OFRunLoopThread* thread;
}
@property(assign) NSObject<OFWebViewManifestDelegate>* delegate;
@property(retain, nonatomic) NSString* rootPath;
@property(retain, nonatomic) NSMutableSet* pathsToLoad;
@property(retain, nonatomic) NSMutableDictionary* tracked;
@property(retain, nonatomic) NSMutableSet* globals;
@property(retain, nonatomic) NSMutableSet* priority;
@property(retain, nonatomic) OFWebViewManifestData* serverManifest;
@property(retain, nonatomic) NSMutableDictionary* localManifest;
@property(retain, nonatomic) NSString* manifestApplication;
@property(assign, nonatomic) BOOL abortedByReset;
@property(retain, nonatomic) NSMutableDictionary* observers;
@property(assign, nonatomic) BOOL defaultCopied;
@property(retain, nonatomic) NSLock* trackingLock;
@property(retain, nonatomic) OFRunLoopThread* thread;
-(id)initForApplication:(id)application;
-(void)dealloc;
-(BOOL)trackPath:(id)path forMe:(id)me;
-(void)prioritizePath:(id)path;
-(BOOL)isPathLoaded:(id)loaded;
-(BOOL)isPathValid:(id)valid;
-(void)enable;
-(void)disable;
-(void)resetToSeed;
-(id)documentsPath;
-(void)copyDefaultManifest;
-(void)getServerManifest;
-(void)_notifyItemReady:(id)ready;
-(void)_getServerManifest;
-(void)finishItem:(id)item success:(BOOL)success;
-(void)didSucceedDataForHelper:(id)helper;
-(void)didFailDataForHelper:(id)helper;
-(void)loadNextItem;
-(void)loaderIsFinished;
@end

