/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import "OFViewController.h"
#import "OFWebViewController.h"

@class UIWebView, NSDictionary, UIActivityIndicatorView;

@interface OFWebViewController : OFViewController <UIWebViewDelegate> {
	UIWebView* mWebView;
	UIActivityIndicatorView* mLoadingView;
	NSDictionary* mDispatch;
	BOOL didFirstLoad;
}
-(void)loadWebContent;
-(void)viewWillAppear:(BOOL)view;
-(id)webView;
-(void)viewWillDisappear:(BOOL)view;
-(void)loadView;
-(void)webViewDidStartLoad:(id)webView;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)_webActionPopController:(id)controller;
-(BOOL)_webActionPushController:(id)controller;
-(BOOL)_webActionPushIPurchase:(id)purchase;
-(id)getDispatchDictionary;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(unsigned)type;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
@end

@interface OFWebViewController (Overridables)
-(id)getAction;
-(id)getTitle;
-(id)notificationString;
-(id)getParameters;
@end

