/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSMutableDictionary;

@interface OFWebViewManifestData : XXUnknownSuperclass {
	NSMutableDictionary* objects;
	NSMutableSet* globalObjects;
}
@property(retain, nonatomic) NSMutableDictionary* objects;
@property(retain, nonatomic) NSMutableSet* globalObjects;
-(id)init;
-(void)dealloc;
-(void)populateWithData:(id)data;
@end

