/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol OFWebUICrashReporterDelegate;

@interface OFWebUICrashReporter : XXUnknownSuperclass <UIAlertViewDelegate> {
	id<OFWebUICrashReporterDelegate> delegate;
}
-(id)initWithDelegate:(id)delegate;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
@end

