/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class OFWebUIController, NSString;

@interface OFWebUIConfirmationDelegate : XXUnknownSuperclass <UIAlertViewDelegate> {
	OFWebUIController* webNav;
	NSString* cb;
}
@property(retain, nonatomic) OFWebUIController* webNav;
@property(retain, nonatomic) NSString* cb;
+(id)delegateWithNav:(id)nav andCb:(id)cb;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)alertViewCancel:(id)cancel;
-(void)dealloc;
@end

