/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OFTableCellHelper.h"

@class UILabel, OFImageView;

@interface OFWhosPlayingCell : OFTableCellHelper {
	OFImageView* profilePictureView;
	UILabel* nameLabel;
	UILabel* lastPlayedGameLabel;
	UILabel* gamerScoreLabel;
	UILabel* appGamerScoreLabel;
	UILabel* onlineLabel;
}
@property(retain, nonatomic) OFImageView* profilePictureView;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) UILabel* lastPlayedGameLabel;
@property(retain, nonatomic) UILabel* gamerScoreLabel;
@property(retain, nonatomic) UILabel* appGamerScoreLabel;
@property(retain, nonatomic) UILabel* onlineLabel;
-(BOOL)hasConstantHeight;
-(void)onResourceChanged:(id)changed;
-(void)dealloc;
@end

