/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import "OFTableSequenceControllerHelper.h"

@class NSString;

@interface OFWhosPlayingController : OFTableSequenceControllerHelper {
	NSString* applicationName;
	NSString* applicationId;
	NSString* applicationIconUrl;
	NSString* userId;
}
@property(retain, nonatomic) NSString* userId;
@property(retain, nonatomic) NSString* applicationName;
@property(retain, nonatomic) NSString* applicationId;
@property(retain, nonatomic) NSString* applicationIconUrl;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)dealloc;
-(void)populateResourceMap:(OFResourceControllerMap*)map;
-(id)getService;
-(void)onCellWasClicked:(id)clicked indexPathInTable:(id)table;
-(id)getNoDataFoundMessage;
-(id)getNoDataFoundViewController;
-(void)doIndexActionWithPage:(unsigned)page onSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(void)doIndexActionOnSuccess:(const OFDelegate*)success onFailure:(const OFDelegate*)failure;
-(bool)usePlainTableSectionHeaders;
-(id)createPlainTableSectionHeader:(unsigned)header;
-(void)friendPresenceDidChange:(id)friendPresence;
@end

