/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface OFXmlDocument : XXUnknownSuperclass {
	OFPointer<OFXmlElement> mDocumentRoot;
	vector<OFPointer<OFXmlElement>,std::allocator<OFPointer<OFXmlElement> > > mActiveElements;
}
+(id)xmlDocumentWithData:(id)data;
+(id)xmlDocumentWithString:(id)string;
-(id)initWithData:(id)data;
-(id)getElementValue:(const char*)value;
-(OFPointer<OFXmlElement>)readNextElement;
-(void)pushNextScope:(const char*)scope;
-(void)popScope;
-(void)pushNextUnreadScope;
-(bool)pushNextUnreadScopeWithNameIfAvailable:(const char*)nameIfAvailable;
-(id)getCurrentScopeShortName;
-(bool)nextValueAtCurrentScopeWithKey:(const char*)key outValue:(id*)value;
-(void)elementStarted:(OFXmlElement*)started;
-(void)elementEnded;
-(OFXmlElement*)activeElement;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

