/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

@interface OFXmlResourceNode : XXUnknownSuperclass {
	NSMutableArray* children;
	NSString* key;
	NSString* value;
}
@property(retain, nonatomic) NSMutableArray* children;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) NSString* value;
+(id)nodeWithKey:(id)key andValue:(id)value;
+(id)nodeWithKey:(id)key andChildren:(id)children;
-(id)initWithKey:(id)key andValue:(id)value;
-(id)initWithKey:(id)key andChildren:(id)children;
-(void)openScope:(id)scope;
-(void)closeScope:(id)scope;
-(void)writeContent:(id)content;
-(void)appendXmlToString:(id)string;
-(id)toXmlString;
-(void)dealloc;
@end

