/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"
#import "DoodleJump-Structs.h"

@class UIAlertView, UIButton;

@interface OptionsView : XXUnknownSuperclass <UIAlertViewDelegate> {
	UIButton* gameModeFullButton;
	UIButton* gameModeClassicButton;
	UIButton* markersOffButton;
	UIButton* markersGlobalButton;
	UIButton* markersLocalButton;
	UIButton* submissionOffButton;
	UIButton* submissionAutoButton;
	UIButton* soundsOffButton;
	UIButton* soundsOnButton;
	UIButton* shootingOffButton;
	UIButton* shootingOnButton;
	UIButton* calibrateAutoButton;
	UIButton* calibrateManualButton;
	UIButton* menuButton;
	UIButton* resetScoresButton;
	UIButton* importScoresButton;
	UIButton* openFeintDashboardButton;
	UIButton* openFeintOffButton;
	UIButton* openFeintOnButton;
	UIAlertView* resetScoresAlert;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setButtonStatesWithValuesForScoreMarkers:(int)scoreMarkers scoreSubmissions:(int)submissions sounds:(int)sounds shooting:(int)shooting calibration:(int)calibration gameMode:(int)mode openFeint:(int)feint;
-(void)gameModeFullButtonTouched;
-(void)gameModeClassicButtonTouched;
-(void)markersOffButtonTouched;
-(void)markersGlobalButtonTouched;
-(void)markersLocalButtonTouched;
-(void)submissionOffButtonTouched;
-(void)submissionAutoButtonTouched;
-(void)soundsOffButtonTouched;
-(void)soundsOnButtonTouched;
-(void)shootingOffButtonTouched;
-(void)shootingOnButtonTouched;
-(void)calibrateAutoButtonTouched;
-(void)calibrateManualButtonTouched;
-(void)openFeintButtonTouched;
-(void)openFeintOnButtonTouched;
-(void)openFeintOffButtonTouched;
-(void)menuButtonTouched;
-(void)returnFromOptions;
-(void)resetScoresButtonTouched;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)removeAlertViewIfNeeded;
-(void)importScoresButtonTouched;
-(void)hideImportButtonIfNeeded;
-(void)showImportButtonIfNeeded;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

