/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface ProjectileObject : XXUnknownSuperclass {
	CGSize sizeOfType[2];
	CGPoint objPosition;
	float objSpeed;
	float objDirectionOffset;
	int objType;
	int objRotation;
	int objId;
}
@property(assign, nonatomic) CGPoint objPosition;
@property(assign, nonatomic) float objSpeed;
@property(assign, nonatomic) float objDirectionOffset;
@property(assign, nonatomic) int objType;
@property(assign, nonatomic) int objRotation;
@property(assign, nonatomic) int objId;
-(id)initWithType:(int)type;
-(id)initWithType:(int)type objId:(int)anId;
-(void)tick;
-(void)moveWithOffsetY:(float)offsetY;
-(void)dealloc;
@end

