/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class Texture2D;

@interface RainParticles : XXUnknownSuperclass {
	unsigned verticesBufferId;
	RainParticle* rainParticles;
	PointSprite* vertices;
	unsigned maxParticles;
	Texture2D* particleTexture;
	int particleIndex;
	int targetActiveParticles;
	int currentActiveParticles;
	int activeParticlesChange;
	int changeDelay;
	int maxChangeDelay;
	int stormTimer;
	float stormAlpha;
	int inSceneIndex;
	int finished;
	int (*currentRainScene)[3];
	int sizeRangeStart;
	int sizeRangeEnd;
}
@property(assign, nonatomic) float stormAlpha;
@property(assign, nonatomic) int currentActiveParticles;
-(id)init;
-(void)resetParticles;
-(void)startRaining;
-(void)stopRainingFast;
-(BOOL)updateParticlesWithOffset:(float)offset;
-(void)dealloc;
@end

