/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableArray;

@interface SBJsonBase : XXUnknownSuperclass {
	NSMutableArray* errorTrace;
	unsigned depth;
	unsigned maxDepth;
}
@property(readonly, copy) NSArray* errorTrace;
@property(assign) unsigned maxDepth;
-(id)init;
-(void)dealloc;
-(void)addErrorWithCode:(unsigned)code description:(id)description;
-(void)clearErrorTrace;
@end

