/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Texture2D.h"


@interface Texture2D : XXUnknownSuperclass {
	unsigned _name;
	CGSize _contentSize;
	unsigned _textureWidth;
	unsigned _textureHeight;
	int _format;
	float _maxS;
	float _maxT;
	unsigned _framesInRow;
	unsigned _framesInCol;
	unsigned _contentSizeWidth;
	unsigned _contentSizeHeight;
	float _halfFrameWidth;
	float _halfFrameHeight;
	float _texCoordinates[8];
}
@property(readonly, assign, nonatomic) CGSize contentSize;
@property(readonly, assign) int pixelFormat;
@property(readonly, assign) unsigned pixelsWide;
@property(readonly, assign) unsigned pixelsHigh;
@property(readonly, assign) unsigned name;
@property(readonly, assign) float maxS;
@property(readonly, assign) float maxT;
-(id)initWithData:(const void*)data pixelFormat:(int)format pixelsWide:(unsigned)wide pixelsHigh:(unsigned)high contentSize:(CGSize)size textureParameters:(TexParams*)parameters;
-(void)dealloc;
@end

@interface Texture2D (Drawing)
-(void)preload;
-(void)drawAtPoint:(CGPoint)point precise:(BOOL)precise;
-(void)setNumberOfFramesInRow:(int)row column:(int)column;
-(void)drawFrame:(int)frame atPoint:(CGPoint)point flipH:(BOOL)h;
-(void)drawInRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect inRect:(CGRect)rect2;
@end

@interface Texture2D (Text)
-(id)initWithString:(id)string dimensions:(CGSize)dimensions alignment:(int)alignment fontName:(id)name fontSize:(float)size lineBreakMode:(int)mode textureParameters:(TexParams*)parameters;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions alignment:(int)alignment fontName:(id)name fontSize:(float)size lineBreakMode:(int)mode color:(RGBColorParams)color textureParameters:(TexParams*)parameters;
@end

@interface Texture2D (Image)
-(id)initWithImageName:(id)imageName pixelFormat:(int)format textureParameters:(TexParams*)parameters;
-(id)initWithCGImage:(CGImageRef)cgimage pixelFormat:(int)format textureParameters:(TexParams*)parameters shouldScaleImage:(int)image;
@end

