/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface ThemeScrollView : XXUnknownSuperclass {
	int touchBeganInNewsButtonArea;
	CGRect newsButtonRect;
	int newsButtonEnabled;
}
@property(assign) int newsButtonEnabled;
-(id)initWithFrame:(CGRect)frame;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)dealloc;
@end

