/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UINavigationBarDelegate <NSObject>
@optional
-(BOOL)navigationBar:(id)bar shouldPushItem:(id)item;
-(void)navigationBar:(id)bar didPushItem:(id)item;
-(BOOL)navigationBar:(id)bar shouldPopItem:(id)item;
-(void)navigationBar:(id)bar didPopItem:(id)item;
@end

