/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DoodleJump-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLConnection;

@interface UploaderThread : XXUnknownSuperclass {
	NSURLConnection* _uploadConnection;
	int _responseStatusCode;
	BOOL _isUploading;
}
@property(retain, nonatomic) NSURLConnection* uploadConnection;
@property(assign) BOOL isUploading;
+(id)sharedUploaderThread;
+(id)allocWithZone:(NSZone*)zone;
-(void)uploaderThreadwithApplicationKey:(id)key;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)complete;
-(id)gzipDeflatedDataWithData:(id)data;
-(void)logMessage:(id)message;
-(id)copyWithZone:(NSZone*)zone;
-(id)retain;
-(unsigned)retainCount;
-(oneway void)release;
-(id)autorelease;
-(void)dealloc;
@end

